- source/Api/Configuration/IntegrationEvents/EventDetails.cs
- source/Api/Configuration/IntegrationEvents/FunctionContextExtensions.cs
- source/Api/EventListeners/BalanceFixingWasCompletedListener.cs
Extract integration event details for use in generic integration event receiver
> Extract integration event details for use in generic integration event receiver

- source/Api/Configuration/IntegrationEvents/FunctionContextExtensions.cs
> Fix error in reading metadata

- source/Api/Api.csproj
- source/Api/EventListeners/BalanceFixingWasCompletedListener.cs
- source/Api/EventListeners/EventDetails.cs
- source/Api/EventListeners/FunctionContextExtensions.cs
- source/Api/EventListeners/IntegrationEventListener.cs
- source/Application/Transactions/Aggregations/NewResultAvailableNotification.cs
- source/Application/Transactions/Aggregations/NewResultAvailableNotificationHandler.cs
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/Configuration/IntegrationEvents/IntegrationEventReceiver.cs
- source/Infrastructure/Configuration/IntegrationEvents/IntegrationEventsConfiguration.cs
- source/Infrastructure/Infrastructure.csproj
- source/Infrastructure/Transactions/Aggregations/AggregationsConfiguration.cs
- source/Infrastructure/Transactions/Aggregations/BalanceFixingCompletedEventMapper.cs
- source/IntegrationTests/Application/Transactions/Aggregations/SampleData.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenAggregationOfTotalProductionIsCompletedTests.cs
- source/IntegrationTests/Infrastructure/Configuration/IntegrationEvents/TestNotificationHandlerSpy.cs
- source/IntegrationTests/Infrastructure/Configuration/IntegrationEvents/WhenAnIntegrationEventIsReceivedTests.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/IntegrationTests/TestBase.cs
Initiate transaction via generic integration event receiver
> Initiate transactions via generic integration event receiver

- source/Application/Transactions/Aggregations/StartTransactionHandler.cs
- source/Domain/Actors/MarketRole.cs
- source/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataMessageWriter.cs
- source/IntegrationTests/Application/Transactions/Aggregations/RetrieveAggregationResultTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenAggregationOfTotalProductionIsCompletedTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
Bugfix: Add product type and changed message receiver role
> Bugfix: Add product type and changed receiver role

- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/Configuration/IntegrationEvents/ProcessIntegrationEventsOnTenSecondsHasPassed.cs
- source/Infrastructure/Configuration/InternalCommands/InternalCommandProcessing.cs
- source/Infrastructure/Transactions/MoveIn/MoveInConfiguration.cs
- source/IntegrationTests/TestBase.cs
Add timer based handler for processing integration events
> Add timer based handler for processing integration events

- source/Infrastructure/Configuration/Authentication/ClaimsMap.cs
> Add metered data responsible role to claims map

- source/PerformanceTest/jmeter/runtests.sh
Add script for running the jmeter performance test from the terminal
> Add script for running the jmeter performance test from the terminal

- source/PerformanceTest/Controllers/PeekDequeuePerformanceTestController.cs
- source/PerformanceTest/PerformanceTest.csproj
- source/PerformanceTest/Program.cs
Enabled logging for PerformanceTest App-Service
> Enabled logging for PerformanceTest App-Service

- source/PerformanceTest/Controllers/PeekDequeuePerformanceTestController.cs
> Change log message to Warning

- source/PerformanceTest/Controllers/PeekDequeuePerformanceTestController.cs
> Print exception

- source/PerformanceTest/Controllers/PeekDequeuePerformanceTestController.cs
Enabled both parallel and non-parallel insertion of MoveIns test data
> Enabled both parallel and non-parallel insertion of MoveIns test data

- source/Application/Transactions/Aggregations/HourlyConsumption/PrepareTransactions.cs
- source/Application/Transactions/Aggregations/HourlyConsumption/PrepareTransactionsHandler.cs
- source/Application/Transactions/Aggregations/HourlyConsumption/PrepareTransactionsWhenBalanceFixingIsCompleted.cs
- source/Application/Transactions/Aggregations/HourlyConsumption/StartTransaction.cs
- source/Application/Transactions/Aggregations/HourlyConsumption/StartTransactionHandler.cs
- source/Application/Transactions/Aggregations/IAggregationResults.cs
- source/Application/Transactions/Aggregations/RetreiveAggregationResult.cs
- source/Application/Transactions/Aggregations/StartTransactionHandler.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202302011542 Remove period start and end.sql
- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Domain/Transactions/Aggregations/AggregatedTimeSeriesResult.cs
- source/Domain/Transactions/Aggregations/AggregationResultForwarding.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultDto.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultForwardingEntityConfiguration.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultMapper.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultsOverHttp.cs
- source/IntegrationTests/Application/Transactions/Aggregations/HourlyConsumption/WhenATransactionIsStartedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/HourlyConsumption/WhenBalanceFixingIsCompletedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/RetrieveAggregationResultTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenAggregationOfTotalProductionIsCompletedTests.cs
- source/IntegrationTests/TestDoubles/AggregationResultsStub.cs
- source/LearningTests/Infrastructure/Transactions/Aggregations/AggregationResultOverHttpTests.cs
Include period in aggregation result
> Include period in aggregation result

- source/Application/Transactions/Aggregations/HourlyConsumption/PrepareTransactionsWhenBalanceFixingIsCompleted.cs
Use command scheduler facade since no unit of work is active
> Use command scheduler facade since no unit of work is active

- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-orchestrator.yml
- .github/workflows/detect-changes.yml
> add split ci flows

- source/Application/Transactions/Aggregations/HourlyConsumption/StartTransactionHandler.cs
- source/Domain/OutgoingMessages/MeteringPointType.cs
- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Domain/Transactions/Aggregations/AggregatedTimeSeriesResult.cs
- source/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataMessageWriter.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultMapper.cs
- source/IntegrationTests/Application/Transactions/Aggregations/HourlyConsumption/WhenATransactionIsStartedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/HourlyConsumption/WhenBalanceFixingIsCompletedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/RetrieveAggregationResultTests.cs
- source/IntegrationTests/TestDoubles/AggregationResultsStub.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
Send  non-profiled aggregation result to target energy suppliers
> Send  non-profiled aggregation result to target energy suppliers

- source/Domain/OutgoingMessages/MeteringPointType.cs
- source/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataMessageWriter.cs
- source/Tests/Domain/OutgoingMessages/MeteringPointTypeTests.cs
Add metering point type to EDI code parsing helper
> Add metering point type to EDI code parsing helper

- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataMessageWriter.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
Include settlement method in message when aggregation result is of consumption
> Include settlement method in message when aggregation result is of consumption

- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Domain/Transactions/Aggregations/AggregationResult.cs
- source/Domain/Transactions/GridArea.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultMapper.cs
- source/IntegrationTests/Application/Transactions/Aggregations/HourlyConsumption/WhenATransactionIsStartedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/HourlyConsumption/WhenBalanceFixingIsCompletedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/RetrieveAggregationResultTests.cs
- source/IntegrationTests/TestDoubles/AggregationResultsStub.cs
- source/Tests/Domain/Transactions/Aggregations/AggregationResultTests.cs
Introduce value object for grid area
> Introduce value object for grid area

- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Domain/Transactions/Aggregations/AggregationResult.cs
- source/Domain/Transactions/Resolution.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultMapper.cs
- source/IntegrationTests/Application/Transactions/Aggregations/HourlyConsumption/WhenATransactionIsStartedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/HourlyConsumption/WhenBalanceFixingIsCompletedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/RetrieveAggregationResultTests.cs
- source/Tests/Domain/Transactions/Aggregations/AggregationResultTests.cs
- source/Tests/Domain/Transactions/ResolutionTests.cs
Introduce value object for resolution
> Introduce value object for resolution

- source/Domain/Actors/ActorNumber.cs
- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataMessageWriter.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/SampleData.cs
RSM-014: nonprofiled consumption add actor attributes (energysupplier/balanceresponsibleparty)
> RSM-014: nonprofiled consumption add actor attributes

- docs/c4-model-edi-component-level.dsl
- Added C4 model dsl file of EDI to repo
- Changed to use model as described in ADR-105
> Added C4 model dsl file

- source/Application/Transactions/Aggregations/SendAggregationResult.cs
- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Domain/Transactions/Aggregations/Quality.cs
- source/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataMessageWriter.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultMapper.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenResultsAreRetrievedTests.cs
- source/IntegrationTests/Factories/AggregationResultBuilder.cs
- source/Tests/Domain/Transactions/Aggregations/QualityTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
Introduce Quality value object
> Introduce Quality value object

- source/Infrastructure/Configuration/Authentication/ClaimsMap.cs
Add claim mapping for balance responsible market role
> Add claim mapping for balance responsible market role

- source/Infrastructure/Transactions/Aggregations/AggregationResultsOverHttp.cs
- source/LearningTests/Infrastructure/Transactions/Aggregations/AggregationResultOverHttpTests.cs
> Fix wholesale api call

- source/Domain/OutgoingMessages/ProcessType.cs
- source/Domain/Transactions/Aggregations/SettlementType.cs
- source/Tests/Factories/TimeSeriesBuilder.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
Verify correct translation of:
- ProcessType
- MeteringPoint type
- Measurement unit
- Resolution
- Quality
> Verify message writer

- README.md
ReadMe has been updated with new sprint goals
* #0000
> Update readme with new goals

- source/Application/Transactions/MoveIn/Notifications/MoveInNotifications.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202303141135 Change process type from code to name.sql
- source/Domain/OutgoingMessages/CharacteristicsOfACustomerAtAnAp/CharacteristicsOfACustomerAtAnApMessage.cs
- source/Domain/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierMessage.cs
- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Domain/OutgoingMessages/ProcessType.cs
- source/Domain/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierMessage.cs
- source/Infrastructure/OutgoingMessages/Common/CimCode.cs
- source/Infrastructure/OutgoingMessages/Common/Xml/HeaderWriter.cs
- source/IntegrationTests/Application/IncomingMessages/IncomingMessageBuilder.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenADequeueIsRequestedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenMessageCountIsRequestedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenOutgoingMessagesAreCreatedTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenResultsAreRetrievedTests.cs
- source/IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/SendCustomerMasterDataToGridOperatorTests.cs
- source/IntegrationTests/Application/Transactions/MoveIn/MasterDataDelivery/WhenRequestedCustomerMasterDataIsReceivedTests.cs
- source/IntegrationTests/Application/Transactions/MoveIn/Notifications/NotifyGridOperatorHandlerTests.cs
- source/IntegrationTests/Application/Transactions/MoveIn/RequestMoveInTests.cs
- source/IntegrationTests/Assertions/AssertXmlMessage.cs
- source/Tests/Infrastructure/OutgoingMessages/AccountingPointCharacteristics/AccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/Asserts/AssertXmlMessage.cs
- source/Tests/Infrastructure/OutgoingMessages/CharacteristicsOfACustomerAtAnAP/CharacteristicsOfACustomerAtAnApDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeAccountingPointCharacteristics/ConfirmRequestChangeAccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/GenericNotification/GenericNotificationDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierDocumentWriterTests.cs
Refactor: Persist process type name instead of EDI code
> Refactor: Persist process type name instead of EDI code

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202303151517 Change payload column to nvarchar.sql
- source/Infrastructure/Configuration/IntegrationEvents/IIntegrationEventMapper.cs
- source/Infrastructure/Configuration/IntegrationEvents/IntegrationEventReceiver.cs
- source/Infrastructure/Configuration/IntegrationEvents/ReceivedIntegrationEvent.cs
- source/Infrastructure/Transactions/Aggregations/CalculationResultCompletedEventMapper.cs
- source/IntegrationTests/Infrastructure/Configuration/IntegrationEvents/TestIntegrationEventMapper.cs
Persist received events as JSON to enable readability
> Persist received events as JSON to enable readability

- .github/workflows/cd.yml
- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-orchestrator.yml
- .github/workflows/detect-changes.yml
After the introduction of ci-orchestrator this is no longer needed
> remove allow_merge

- source/Application/Transactions/Aggregations/ForwardAggregationResult.cs
- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Domain/Transactions/Aggregations/Aggregation.cs
- source/Infrastructure/Transactions/Aggregations/CalculationResultCompletedEventMapper.cs
- source/Tests/Factories/AggregationResultBuilder.cs
Refactor: Remove unused properties in aggregation result
> Refactor: Remove unused properties in aggregation result

- source/Application/Application.csproj
- source/Application/Transactions/MoveIn/Notifications/NotifyGridOperatorHandler.cs
- source/Domain/Domain.csproj
- source/Infrastructure/Configuration/Processing/EnqueueOutgoingMessagesBehaviour.cs
- source/Infrastructure/Configuration/Processing/RaiseDomainEventsBehaviour.cs
- source/Infrastructure/Configuration/Processing/UnitOfWorkBehaviour.cs
- source/Infrastructure/Infrastructure.csproj
> Upgrade MediatR

- source/Api/Program.cs
- source/Application/Actors/IActorRegistry.cs
- source/Infrastructure/Actors/ActorRegistry.cs
- source/Infrastructure/Configuration/Authentication/DevMarketActorAuthenticator.cs
Fix issues with development authenticator
> Fix issues with development authenticator

- source/Application/Configuration/Authentication/MarketActorIdentity.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202303171350 Change sender role and receiver role to role names.sql
- source/CimMessageAdapter/Messages/RequestChangeCustomerCharacteristics/SenderAuthorizer.cs
- source/CimMessageAdapter/Messages/RequestChangeOfSupplier/SenderAuthorizer.cs
- source/Domain/Actors/MarketRole.cs
- source/Infrastructure/OutgoingMessages/Common/CimCode.cs
- source/Infrastructure/OutgoingMessages/Common/Xml/HeaderWriter.cs
- source/Tests/Infrastructure/OutgoingMessages/AccountingPointCharacteristics/AccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/Asserts/AssertXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/Asserts/AssertXmlMessage.cs
- source/Tests/Infrastructure/OutgoingMessages/CharacteristicsOfACustomerAtAnAP/CharacteristicsOfACustomerAtAnApDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeAccountingPointCharacteristics/ConfirmRequestChangeAccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/GenericNotification/GenericNotificationDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierDocumentWriterTests.cs
Refactor: Persist market role name instead of EDI code
> Refactor: Persist market role name instead of EDI code

- source/Infrastructure/OutgoingMessages/Common/Json/JsonHeaderWriter.cs
- source/Tests/Factories/MessageHeaderFactory.cs
- source/Tests/Infrastructure/OutgoingMessages/AccountingPointCharacteristics/AccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/Asserts/AssertJsonMessage.cs
- source/Tests/Infrastructure/OutgoingMessages/CharacteristicsOfACustomerAtAnAP/CharacteristicsOfACustomerAtAnApDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeAccountingPointCharacteristics/ConfirmRequestChangeAccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierJsonDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/GenericNotification/GenericNotificationDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/JsonDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierDocumentWriterTests.cs
Refactor: Introduce message header factor to remove duplication
> Refactor: Introduce message header factor to remove duplication

- source/Api/OutgoingMessages/DequeueRequestListener.cs
- source/Application/OutgoingMessages/Dequeue/DequeueRequestHandler.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenADequeueIsRequestedTests.cs
Validate message id in dequeue request
> Validate message id in dequeue request

- source/Api/Api.csproj
- source/Application/Application.csproj
- source/CimMessageAdapter/CimMessageAdapter.csproj
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
> Upgrade packages

- README.md
Updated architecture diagram
* #0000
> Update EDI diagram

- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/OutgoingMessages/AccountingPointCharacteristics/AccountingPointCharacteristicsXmlDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/CharacteristicsOfACustomerAtAnAp/CharacteristicsOfACustomerAtAnApDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/ConfirmRequestChangeAccountingPointCharacteristics/ConfirmRequestChangeAccountingPointCharacteristicsXmlDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmChangeOfSupplierXmlDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/GenericNotification/GenericNotificationXmlDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataXmlDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsXmlDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierJsonDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierXmlDocumentWriter.cs
- source/Tests/Infrastructure/OutgoingMessages/AccountingPointCharacteristics/AccountingPointCharacteristicsXmlDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/CharacteristicsOfACustomerAtAnAP/CharacteristicsOfACustomerAtAnApXmlDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeAccountingPointCharacteristics/ConfirmRequestChangeAccountingPointCharacteristicsXmlDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/ConfirmRequestChangeOfSupplier/ConfirmRequestChangeOfSupplierXmlDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/GenericNotification/GenericNotificationXmlDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataXmlDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsXmlDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierJsonDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierXmlDocumentWriterTests.cs
Renamed all "MessageWriter" to "DocumentWriter" and specify format
> Rename to DocumentWriter

- source/Api/Api.csproj
- source/Application/Application.csproj
- source/Application/Transactions/Aggregations/ForwardAggregationResultHandler.cs
- source/Application/Transactions/MoveIn/BusinessService.cs
- source/Application/Transactions/MoveIn/GridOperator.cs
- source/Application/Transactions/MoveIn/MessageDelivery.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/CimMessageAdapter/CimMessageAdapter.csproj
- source/DocumentValidation/DocumentValidation.csproj
- source/Domain/Domain.csproj
- source/EnergySupplying.Contracts/EnergySupplying.Contracts.csproj
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/PerformanceTest/PerformanceTest.csproj
- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeAccountingPointCharacteristics/RejectRequestChangeAccountingPointCharacteristicsXmlDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierJsonDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestChangeOfSupplier/RejectRequestChangeOfSupplierXmlDocumentWriterTests.cs
- source/Tests/Tests.csproj
> Update NuGet packages

- source/DocumentValidation/DocumentValidation.csproj
- source/DocumentValidation/Schemas/Json/Notify-Aggregated-Measure-Data-assembly-model.schema.json
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultJsonDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultXmlDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/Common/Json/JsonHeaderWriter.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AssertAggregationResultJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AssertAggregationResultXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/IAssertAggregationResultDocument.cs
Add JSON document writer for aggregation result
> Add JSON document writer for aggregation result

- source/Infrastructure/OutgoingMessages/Common/Xml/MessageWriter.cs
- source/Infrastructure/OutgoingMessages/Common/Xml/XmlHeaderWriter.cs
Refactor: Remove hardcode values from header writer
> Refactor: Remove hardcode values from header writer

- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultJsonDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultXmlDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/Common/GeneralValues.cs
- source/Infrastructure/OutgoingMessages/Common/Json/JsonHeaderWriter.cs
- source/Infrastructure/OutgoingMessages/Common/Xml/HeaderWriter.cs
Refactor: Remove hardcoded values and cleanup
> Refactor: Remove hardcoded values and cleanup

- source/Domain/Transactions/Aggregations/Aggregation.cs
- source/Domain/Transactions/Aggregations/Period.cs
- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultJsonDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultXmlDocumentWriter.cs
- source/Tests/Domain/Transactions/Aggregations/PeriodTests.cs
- source/Tests/Factories/TimeSeriesBuilder.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AssertAggregationResultJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AssertAggregationResultXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/IAssertAggregationResultDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/SampleData.cs
Refactor: Encapsulate date format rules in Period value object
> Refactor: Encapsulate date format rules in Period value object

- source/Application/SearchMessages/GetMessageQueryHandler.cs
- source/Application/SearchMessages/GetMessagesQuery.cs
- source/Application/SearchMessages/MessageInfo.cs
- source/Application/SearchMessages/MessageSearchResult.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202304131240 Create ArchivedMessage table.sql
- source/Domain/ArchivedMessages/ArchivedMessage.cs
- source/Domain/ArchivedMessages/IArchivedMessageRepository.cs
- source/Infrastructure/ArchivedMessages/ArchivedMessageConfiguration.cs
- source/Infrastructure/ArchivedMessages/ArchivedMessageEntityConfiguration.cs
- source/Infrastructure/ArchivedMessages/ArchivedMessageRepository.cs
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/Configuration/DataAccess/B2BContext.cs
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
- source/IntegrationTests/TestBase.cs
> Add message archive query

- source/Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/IntegrationTests/Fixtures/DatabaseFixture.cs
- source/IntegrationTests/TestBase.cs
Outgoing message are archived upon peek requests
> Outgoing message are archived upon peek requests

- source/Api/OutgoingMessages/PeekRequestListener.cs
- source/Api/SearchMessages/SearchMessagesListener.cs
- source/Application/Configuration/Authentication/Authenticated.cs
- source/Application/Configuration/Authentication/MarketActorIdentity.cs
- source/CimMessageAdapter/Messages/RequestChangeCustomerCharacteristics/SenderAuthorizer.cs
- source/CimMessageAdapter/Messages/RequestChangeOfSupplier/SenderAuthorizer.cs
- source/Infrastructure/Configuration/Authentication/MarketActorAuthenticator.cs
- source/IntegrationTests/Infrastructure/Authentication/MarketActors/MarketActorAuthenticatorTests.cs
Add http endpoint for document search
> Add http endpoint for document search

- source/Infrastructure/Configuration/Authentication/MarketActorAuthenticator.cs
Fix portal user authentication
> Fix portal user authentication

- source/Application/SearchMessages/GetMessageQueryHandler.cs
- source/Application/SearchMessages/GetMessagesQuery.cs
- source/Application/SearchMessages/MessageInfo.cs
- source/Domain/ArchivedMessages/IArchivedMessageRepository.cs
- source/Infrastructure/ArchivedMessages/ArchivedMessageRepository.cs
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/Configuration/QueryHandlingConfiguration.cs
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
Archived messages can be filtered on creation date
> Archived messages can be filtered on creation date

- source/Api/SearchMessages/SearchMessagesListener.cs
Add endpoint for searching archived messages
> Add endpoint for searching archived messages

- source/Api/SearchMessages/SearchMessagesListener.cs
Bugfix: Serialize response using custom serializer
> Bugfix: Serialize response using custom serializer

- .github/workflows/cd.yml
- .github/workflows/codeql.yml
> move codeql cd trigger

- source/Api/SearchMessages/SearchMessagesListener.cs
> Added a search criteria (message id)

- .github/workflows/cd.yml
> remove dotnet coverage report

- source/Domain/OutgoingMessages/ProcessType.cs
- source/Infrastructure/OutgoingMessages/Common/CimCode.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AssertAggregationResultJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AssertAggregationResultXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/IAssertAggregationResultDocument.cs
> New aggregation process added

- source/Application/SearchMessages/GetMessagesQuery.cs
- source/Application/SearchMessages/QueryBuilder.cs
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
> Search archive messages by receiver number

- source/Api/Api.csproj
- source/CimMessageAdapter/CimMessageAdapter.csproj
- source/DocumentValidation/DocumentValidation.csproj
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/PerformanceTest/PerformanceTest.csproj
- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
> updated nuget packages

- source/Api/ArchivedMessages/ArchivedMessageGetDocumentListener.cs
- source/Api/ArchivedMessages/ArchivedMessageSearchListener.cs
> refactor naming

- source/Application/Configuration/Authentication/MarketActorIdentity.cs
- source/CimMessageAdapter/Messages/MessageReceiver.cs
> refac: removed unneeded code 

- .github/workflows/cd.yml
- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-orchestrator.yml
Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1141
> Bump use of GitHub actions/workflows to v11

- .github/CODEOWNERS
> Codeowner: LRN

- source/Api/Api.csproj
- source/Application/Application.csproj
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/CimMessageAdapter/CimMessageAdapter.csproj
- source/DocumentValidation/DocumentValidation.csproj
- source/Domain/Domain.csproj
- source/EnergySupplying.Contracts/EnergySupplying.Contracts.csproj
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/PerformanceTest/PerformanceTest.csproj
- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/Tests/Tests.csproj
> chore: update nuget packages

- .github/CODEOWNERS
> remove kft from CODEOWNERS

- docs/diagrams/sequence/Request aggregated measure data.txt
- docs/diagrams/sequence/Request change of supplier.txt
- docs/diagrams/sequence/Request dequeue.txt
- docs/diagrams/sequence/Request message search.txt
- docs/diagrams/sequence/Request peek.txt
> doc: Added sequence diagrams

- source/Infrastructure/Infrastructure.csproj
- source/Infrastructure/Transactions/Aggregations/CalculationResultCompletedEventMapper.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenAnAggregationResultIsAvailableTests.cs
- source/IntegrationTests/IntegrationTests.csproj
> refac: using const to match event type from wholesale

- source/ApplyDBMigrationsApp/Scripts/Model/202305171026 Rename Process Type to BusinessReason.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202305221044 Add Document to ArchivedMessage.sql
> fix: ensure sql idempotent

- source/Api/Configuration/Middleware/UnHandledExceptionMiddleware.cs
- source/Api/Program.cs
> feat: ensure we done expose exception and stack traces for exceptions

- source/Api/Program.cs
> refac: ensure we catch exception triggered from other middleware

- source/Api/IncomingMessages/RequestAggregatedMeasureMessageReceiver.cs
- source/Application/OutgoingMessages/Peek/PeekRequestHandler.cs
- source/ApplyDBMigrationsApp/Scripts/Model/202305161024 Add Process Type to ArchivedMassage.sql
- source/Domain/ArchivedMessages/ArchivedMessage.cs
- source/Domain/OutgoingMessages/BusinessReason.cs
- source/Infrastructure/ArchivedMessages/ArchivedMessageEntityConfiguration.cs
- source/IntegrationTests/Application/ArchivedMessages/WhenADocumentIsRequestedTests.cs
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
> fix: remove outgoing messages business reason dependency from archive messages

- README.md
Added 7 flow diagrams showing flows in EDI.
[## References](https://app.zenhub.com/workspaces/phoenix--60a6105157304f00119be86e/issues/gh/energinet-datahub/team-phoenix/26)
* #0000
> doc: updated README.md with flow diagrams.

- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Domain/Transactions/AggregatedMeasureData/Events/AggregatedMeasureProcessWasStarted.cs
- source/Tests/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcessTests.cs
- source/Tests/Domain/Transactions/AggregatedMeasureData/SampleData.cs
> feat: Added aggregated measure data process was started event

- source/Application/Transactions/AggregatedMeasureData/Notifications/NotifyWholesale.cs
- source/Application/Transactions/AggregatedMeasureData/Notifications/NotifyWholesaleWhenAggregatedMeasureProcessWasStarted.cs
- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Infrastructure/Configuration/InternalCommands/InternalCommandProcessing.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/RequestedAggregatedMeasureDataConfiguration.cs
- source/Tests/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcessTests.cs
> feat: Created internal command when aggregated measure process was started

- .github/workflows/cd.yml
- .github/workflows/ci-orchestrator.yml
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1251
> bumped to v12 in .github

- source/Application/OutgoingMessages/Queueing/PeekHandler.cs
> refac: peek must update bundles IsClosed in DB before result is generatedd

- source/Infrastructure/Configuration/Queueing/RemoveDequeuedBundlesWhenADayHasPassed.cs
- source/Infrastructure/OutgoingMessages/Dequeue/DequeueConfiguration.cs
> feat: Remove dequeued bundles and messages after a day

- source/Application/OutgoingMessages/Dequeue/DequeueHandler.cs
- source/Domain/OutgoingMessages/Queueing/IActorMessageQueueRepository.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingTests.cs
> refac: dequeuehandler

- source/Application/OutgoingMessages/Queueing/PeekHandler.cs
> refac: fix peek racecondition

- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcessFactory.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/RequestAggregatedMeasuredDataFromWholesale.cs
- source/Infrastructure/WholeSale/WholeSaleInboxConfiguration.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequest.proto
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequestAccepted.proto
> feat: TimeSeriesRequest and respons for wholesale

- source/Api/Api.csproj
- source/Application/Application.csproj
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/Tests/Tests.csproj
> updated some nuget packages

- source/Api/Api.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
> build: update packages

- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequestAccepted.proto
> feat: Added resolution to the period of the "aggregated measure data request accepted" protobuf contract.

- source/Infrastructure/IncomingMessages/BaseParsers/JsonBaseParser.cs
> Refac: find invalid evaluation errors

- source/Api/setup/setupazure.ps1
> chore: Added inbox and aggregated to queue declaration

- source/Infrastructure.CimMessageAdapter/ValidationErrors/InvalidReceiverRole.cs
- source/Infrastructure.CimMessageAdapter/ValidationErrors/NotSupportedMessageType.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/XmlMessageParser.cs
- source/Infrastructure/IncomingMessages/RequestChangeAccountingPointCharacteristics/XmlMessageParser.cs
- source/Infrastructure/IncomingMessages/RequestChangeCustomerCharacteristics/XmlMessageParser.cs
- source/Infrastructure/IncomingMessages/RequestChangeOfSupplier/XmlMessageParser.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Notifications/Handlers/NotifyWholesaleWhenAggregatedMeasureProcessIsInitialized.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataReceiverTests.cs
> fix: return xml schema validation error if any when reading the xml doc

- source/Domain/OutgoingMessages/MeteringPointType.cs
- source/Domain/OutgoingMessages/NotifyAggregatedMeasureData/AggregationResultMessage.cs
- source/Domain/OutgoingMessages/ProductType.cs
- source/Domain/Transactions/AggregatedMeasureData/AggregatedTimeSerie.cs
- source/Domain/Transactions/Aggregations/Aggregation.cs
- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultJsonDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultXmlDocumentWriter.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Commands/Handlers/MakeAggregatedMeasureAsAggregationResults.cs
- source/Infrastructure/Transactions/Aggregations/AggregatedTimeSeriesRequestAcceptedEventMapper.cs
- source/IntegrationTests/Infrastructure/InboxEvents/TestAggregatedTimeSeriesRequestAcceptedHandlerSpy.cs
- source/IntegrationTests/Infrastructure/InboxEvents/TestInboxEventMapper.cs
- source/IntegrationTests/Infrastructure/InboxEvents/TestNotificationHandlerSpy.cs
- source/IntegrationTests/Infrastructure/InboxEvents/WhenAggregatedTimeSeriesRequestAcceptedEventIsReceivedTests.cs
- source/IntegrationTests/Infrastructure/InboxEvents/WhenAnInboxEventIsProcessingTests.cs
- source/IntegrationTests/TestBase.cs
> chore: added tests for aggregated time serie accepted response

- source/Infrastructure/OutgoingMessages/Common/Xml/DocumentWriter.cs
> fix: added formatting for xml outputs

- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequestRejected.proto
> chore: AggregatedTimeSeriesRequestRejected protobuf contract

- source/Domain/OutgoingMessages/RejectedRequestAggregatedMeasureData/RejectedAggregationResultMessage.cs
- source/Infrastructure.DocumentValidation/CimXml/CimXmlSchemaProvider.cs
- source/Infrastructure.DocumentValidation/CimXml/Schemas/urn-ediel-org-measure-rejectrequestaggregatedmeasuredata-0-1.xsd
- source/Infrastructure.DocumentValidation/DocumentType.cs
- source/Infrastructure.DocumentValidation/Infrastructure.DocumentValidation.csproj
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/OutgoingMessages/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataXmlDocumentWriter.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Commands/Handlers/ForwardRejectedAggregationResultHandler.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenARejectedResultIsAvailableTests.cs
- source/IntegrationTests/Assertions/AssertOutgoingMessage.cs
- source/Tests/Factories/RejectedTimeSeriesBuilder.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestAggregatedMeasureData/AssertRejectedAggregatedMeasureDataResultXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestAggregatedMeasureData/IAssertRejectedAggregatedMeasureDataResultDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataResultDocumentWriterTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestAggregatedMeasureData/SampleData.cs
- source/Tests/Tests.csproj
> Feat: rejected aggregated request xml document writer

- source/Application/IncomingMessages/RequestAggregatedMeasureData/Serie.cs
- source/Application/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestHandler.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/JsonMessageParser.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/XmlMessageParser.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureDataMessageBuilder.cs
- source/Tests/CimMessageAdapter/Messages/RequestAggregatedMeasureData/MessageParserTests.cs
- source/Tests/CimMessageAdapter/Messages/json/AggregatedMeasure/FailSchemeValidationAggregatedMeasureData.json
- source/Tests/CimMessageAdapter/Messages/json/AggregatedMeasure/RequestAggregatedMeasureData.json
> Removed Bidding Zone ref

- source/Infrastructure/Configuration/IntegrationEvents/IntegrationEventsConfiguration.cs
- source/Infrastructure/Configuration/IntegrationEvents/RemoveIntegrationEventsWhenADaysHasPassed.cs
- source/Infrastructure/Configuration/InternalCommands/InternalCommandProcessing.cs
- source/Infrastructure/Configuration/InternalCommands/RemoveInternalCommandsWhenADayHasPassed.cs
- source/Infrastructure/InboxEvents/InboxEventsConfiguration.cs
- source/Infrastructure/InboxEvents/RemoveInboxEventsWhenADaysHasPassed.cs
> chore: Added cleanup of internal commands, inbox evnets

- source/Application/OutgoingMessages/DocumentFactory.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202308171048 Add ProcessDate index on ReceivedIntegrationEvents.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202308171049 Add ProcessDate index on ReceivedInboxEvents.sql
- source/Domain/OutgoingMessages/Queueing/ActorMessageQueue.cs
> Chore: Indexes on ProcessDate for ReceivedIntegrationEvents and ReceicedInboxEvents

- .github/workflows/ci-dotnet.yml
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1201
> Use new tenant variable

- source/Application/OutgoingMessages/Peek/PeekHandler.cs
- source/Application/SearchMessages/MessageInfo.cs
- source/Application/SearchMessages/QueryBuilder.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202308171013 Add messageId to ArchivedMessages.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202308210829 make receiver and sender nullable ArchivedMessages.sql
- source/Domain/ArchivedMessages/ArchivedMessage.cs
- source/Infrastructure/ArchivedMessages/ArchivedMessageEntityConfiguration.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/ValidateAggregatedMeasureDataRequestHandler.cs
- source/IntegrationTests/Application/ArchivedMessages/WhenADocumentIsRequestedTests.cs
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
> feat: added messageId archived messages

- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Infrastructure/OutgoingMessages/Queueing/MessageEnqueuer.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Commands/Handlers/ForwardRejectedAggregationResultHandler.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Commands/Handlers/MakeAggregatedMeasureAsAggregationResults.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/AggregatedMeasureDataResponseFromWholesaleTests.cs
- source/Tests/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcessTests.cs
> added completed state to aggregated measure data

- source/Api/Api.csproj
- source/Api/IntegrationEventHandler.cs
Until now we have used an alpha package for handling Integration Events. Now i have upgraded to newest version, which basically removes the ShouldHandle handle
* #0000
> Updated package to newest

- source/AcceptanceTests/WhenAggregationResultIsPublishedTests.cs
> Feat: Ensure we can't deploy to T without green acceptance tests

- .github/CODEOWNERS
- .github/workflows/cd.yml
> Change team-phoenix to team-mosaic

- source/Application/Application.csproj
- source/Domain/Domain.csproj
- source/Infrastructure/Infrastructure.csproj
> chore: NuGet update MediatR

- source/global.json
> change to file

- source/AcceptanceTests/WhenAggregatedMeasureDataIsRequestedTests.cs
- source/AcceptanceTests/WhenAggregationResultIsPublishedTests.cs
> test: updated acceptance test naming

- source/AcceptanceTests/TestRunner.cs
> changed kv secret name in tests to make them ✅ again

- source/Api/Api.csproj
- source/Infrastructure/Infrastructure.csproj
Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1383
> Health check response

- source/Api/Program.cs
> refac: swtich back to send request to EDI inbox

- source/Api/Program.cs
> feat: Added health check on wholesale queue for inbox events

- source/Infrastructure.CimMessageAdapter/Messages/MessageReceiver.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataReceiverTests.cs
Sql databases and Azure service bus does not support shared transaction scope
* #0000
> fix: moved service bus commit out of db transaction

- source/Api/Program.cs
- source/Infrastructure/Configuration/HealthCheckRegistration.cs
> fix: remove AzureWebJobsStorage from Queue health checks

- source/Api/Program.cs
- source/Infrastructure/Configuration/HealthCheckRegistration.cs
- source/Infrastructure/Infrastructure.csproj
This PR will make sure that the expected table storage for the EDI functions is present
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-phoenix/76
> refac: blobstorage healthcheck

- .github/workflows/ci-dotnet.yml
- source/AcceptanceTests/AcceptanceTests.csproj
- source/Api/Api.csproj
- source/Application/Application.csproj
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/Domain/Domain.csproj
- source/Infrastructure.CimMessageAdapter/Infrastructure.CimMessageAdapter.csproj
- source/Infrastructure.DocumentValidation/Infrastructure.DocumentValidation.csproj
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/Tests/Tests.csproj
> refac: full project and assembly namespaces

- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Infrastructure/Configuration/InternalCommands/InternalCommandProcessing.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Commands/AcceptedAggregatedTimeSerie.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Commands/Handlers/AcceptProcessWhenAcceptedAggregatedTimeSeriesIsAvailable.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Notifications/AggregatedTimeSerieRequestWasAccepted.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/Notifications/Handlers/WhenAnAcceptedAggregatedTimeSeriesRequestIsAvailable.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/RequestedAggregatedMeasureDataConfiguration.cs
- source/Infrastructure/Transactions/Aggregations/AggregatedTimeSeriesRequestAcceptedEventMapper.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/AggregatedMeasureDataResponseFromWholesaleTests.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenAnAcceptedResultIsAvailableTests.cs
- source/IntegrationTests/Infrastructure/InboxEvents/TestAggregatedTimeSeriesRequestAcceptedHandlerSpy.cs
- source/IntegrationTests/Infrastructure/InboxEvents/WhenAggregatedTimeSeriesRequestAcceptedEventIsReceivedTests.cs
- source/IntegrationTests/TestBase.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequestAccepted.proto
> refac: Updated protobuf expecting a single serie instead of a list

- source/Application/OutgoingMessages/DocumentFactory.cs
> fix: assigned message id on outgoing message

- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/RequestAggregatedMeasureDataTransactionTests.cs
> fix: added missing mapning for time series type as grid operator

- source/Api/IncomingMessages/RequestAggregatedMeasureMessageReceiver.cs
- source/Application/OutgoingMessages/PeekHandler.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202309211415 ArchivedMessage MessageId is longer.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202309211415 ArchivedMessage MessageId is varchar255.sql
- source/Domain/ArchivedMessages/ArchivedMessage.cs
- source/Infrastructure/ArchivedMessages/ArchivedMessageEntityConfiguration.cs
- source/IntegrationTests/Application/ArchivedMessages/WhenADocumentIsRequestedTests.cs
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
The current implementation of `ArchivedMessage` was way too restrictive in its modeling compared to its usage.
This PR will provide the following changes
- Sender/ReceiverId is now just a string (we cannot guarantee it is a correct GLN/EIC)
- All the properties are no longer typed, it's more concise if it consists of `strings`
> refac: ArchivedMessage

- source/Infrastructure.CimMessageAdapter/Messages/ITransactionIdRepository.cs
- source/Infrastructure.CimMessageAdapter/Messages/MessageReceiver.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataReceiver.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestChangeCustomerCharacteristics/RequestChangeCustomerCharacteristicsReceiver.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestChangeOfSupplier/RequestChangeOfSupplierReceiver.cs
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/IncomingMessages/TransactionIdRepositoryRegistry.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataReceiverTests.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestChangeCustomerCharacteristics/RequestChangeCustomerCharacteristicsTests.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestChangeOfSupplier/RequestChangeOfSupplierReceiverTests.cs
> refac: transactionIds into TransactionIdRepository

- source/Domain/OutgoingMessages/Queueing/ActorMessageQueue.cs
- source/Tests/Domain/OutgoingMessages/Queueing/ActorMessageQueueTests.cs
> fix: Reduced aggregated bundle size

- source/Infrastructure.CimMessageAdapter/Messages/IMessageIdRepository.cs
- source/Infrastructure.CimMessageAdapter/Messages/MessageReceiver.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataReceiver.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestChangeCustomerCharacteristics/RequestChangeCustomerCharacteristicsReceiver.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestChangeOfSupplier/RequestChangeOfSupplierReceiver.cs
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/IncomingMessages/MessageIdRepositoryRegistry.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataReceiverTests.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestChangeCustomerCharacteristics/RequestChangeCustomerCharacteristicsTests.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestChangeOfSupplier/RequestChangeOfSupplierReceiverTests.cs
> refac: MessageIds -> MessageIdRepository

- source/Infrastructure/Configuration/IntegrationEvents/ReceivedIntegrationEventsRetention.cs
- source/Infrastructure/InboxEvents/ReceivedInboxEventsRetention.cs
Small amount to be removed + select statement for remain candidates to be deleted is now isolated on its own connection
> fix: TimeOutException for retentions jobs

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202309271021 Remove ResponseData from AggregatedMeasureDataProcesses.sql
- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesHandler.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcessEntityConfiguration.cs
…atedMeasureProcess
xml and json parsers handles missing attributes differently. 
xml passes to an empty string where json passes to null. 
This Pull request makes sure, that we map missing attributes to null,
> fix: support of xml request type

- source/Api/Api.csproj
- source/B2CWebApi/B2CWebApi.csproj
- source/Infrastructure/Infrastructure.csproj
I could not find a title prefix that matches "updating dependency", so I chose "refac:".
Part of:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1435
> refac: Bump App package

- source/Api/IncomingMessages/B2CRequestAggregatedMeasureMessageReceiver.cs
> fix: correct function name for B2CRequestAggregatedMeasureMessageReceiver

- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultEbixDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/Common/Ebix/EbixDocumentWriter.cs
> chore: update ebix document writer to handle expected document type

- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultEbixDocumentWriter.cs
- source/Infrastructure/OutgoingMessages/Common/Ebix/EbixDocumentWriter.cs
> fix: typo in ebix aggregated measure data document writer

- source/B2CWebApi/Factories/TokenBuilder.cs
Currenly the token we get from the frontend does not pass validation checks in our b2b system. This pull request resolves this
> fix: added token attribute to our token towards B2B

- source/B2CWebApi/Controllers/RequestAggregatedMeasureDataController.cs
- source/B2CWebApi/Factories/RequestAggregatedMeasureDataHttpFactory.cs
- source/B2CWebApi/Models/MarketRole.cs
- source/Infrastructure.CimMessageAdapter/Messages/ISenderAuthorizer.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/SenderAuthorizer.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataMarketMessageFactory.cs
- source/RequestResponse/source/RequestResponse/Requests/RequestAggregatedMeasureData.proto
> fix: ensure we map market role to code in B2C api

- source/B2CWebApi/B2CWebApi.csproj
- source/B2CWebApi/Program.cs
- source/B2CWebApi/Startup.cs
Ensure we have logging in b2c app
> feat: add logging to b2c web api

- source/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultEbixDocumentWriter.cs
- source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AssertAggregationResultEbixDocument.cs
> fix: Ebix document writer uses ebixcode translater

- source/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/ProcessTypeValidator.cs
D09 is no longer support for RSM-16
> fix: remove latest available value process type

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202310051510 Change start and end time to strings on AggregatedMeasureDataProcesses.sql
- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/ProcessTypeValidator.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesHandler.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/RequestedAggregatedMeasureDataConfiguration.cs
- source/Infrastructure/Wholesale/WholesaleInbox.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/SampleData.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenAnAcceptedResultIsAvailableTests.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequest.proto
Edi should not look at the payload data but just redirect it to wholesale
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/6
> refac: RequestAggregatedMeasureData period to string values

- source/B2CWebApi/Factories/RequestAggregatedMeasureDataHttpFactory.cs
- source/B2CWebApi/Models/RequestAggregatedMeasureDataMarketDocument.cs
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-phoenix/75
> refac: business reason to enum list of process types in b2cWebApi

- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/Infrastructure/Transactions/Aggregations/AggregatedTimeSeriesRequestRejectedMapper.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenARejectedResultIsAvailableTests.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequestRejected.proto
> fix: Updated rejcted aggregated measure data contract

- source/AcceptanceTests/Drivers/EdiDriver.cs
- source/AcceptanceTests/Messages/json/RequestAggregatedMeasureData.json
> fix: Updated start and end date in acceptance test request

- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequest.proto
Wholesale needs the following information to perform validation:
- Requested by actor id & role
- Energy supplier id
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/11
> feat: Add requested by & energy supplier to AggregatedTimeSeriesRequest

- source/Application/IncomingMessages/RequestAggregatedMeasureDataMarketDocument.cs
- source/Infrastructure.CimMessageAdapter/Messages/IBusinessTypeValidator.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/BusinessTypeValidator.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataMarketMessageValidator.cs
- source/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataValidator.cs
- source/Infrastructure.CimMessageAdapter/ValidationErrors/NotSupportedBusinessType.cs
- source/Infrastructure.DocumentValidation/Ebix/EbixSchemas.cs
- source/Infrastructure/Configuration/IncomingMessageParsingServices.cs
- source/Infrastructure/IncomingMessages/BaseParsers/JsonBaseParser.cs
- source/Infrastructure/IncomingMessages/MessageHeader.cs
- source/Infrastructure/IncomingMessages/MessageHeaderExtractor.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesHandler.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataMarketMessageFactory.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureDataMarketDocumentBuilder.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/BusinessMessageBuilder.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataReceiverTests.cs
- source/IntegrationTests/Infrastructure/Configuration/IntegrationEvents/TestIntegrationEventMapper.cs
- source/IntegrationTests/TestBase.cs
- source/Tests/CimMessageAdapter/Messages/RequestAggregatedMeasureData/MessageParserTests.cs
Currently we do not validate the businessSection.type. This attribute holds information on, whether the request is for electricity (23) or gas (27)
Where we only support support electricity
> feat: Business section is now validated when receiving a xml or json request

- source/Api/EventListeners/IntegrationEventListener.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesCommandTests.cs
> fix: Updated setting of settlement method

- source/AcceptanceTests/Messages/json/RequestAggregatedMeasureData.json
Acceptance Test docs did not have valid evaluation point for settlement method
> fix: Acceptance Test docs did not have valid evaluation point for settlement method

- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
Missing attributes fra xml result in empty strings. Which will pass the null check defined later on
> fix: Not saving empty string in settlement method

- source/Application/IncomingMessages/RequestAggregatedMeasureDataMarketDocument.cs
- source/B2CWebApi/Factories/RequestAggregatedMeasureDataHttpFactory.cs
- source/B2CWebApi/Models/RequestAggregatedMeasureDataMarketDocument.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/JsonMessageParser.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataMarketMessageFactory.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/XmlMessageParser.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureDataMarketDocumentBuilder.cs
- source/RequestResponse/source/RequestResponse/Requests/RequestAggregatedMeasureData.proto
- source/Tests/CimMessageAdapter/Messages/RequestAggregatedMeasureData/MessageParserTests.cs
- source/Tests/CimMessageAdapter/Messages/json/AggregatedMeasure/RequestAggregatedMeasureData.json
- source/Tests/CimMessageAdapter/Messages/xml/AggregatedMeasure/RequestAggregatedMeasureData.xml
We need to inspect the `settlementSeries` property on the `series` when we receive a RSM-16. They naming is taken from this link page 82, https://energinet.dk/media/0nsklumj/20220422-edi-transaktioner-for-danske-elmarkede-cim-ver-1_4.pdf
> refac: settlementVersions added to Request

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202310181233 Add SettlemenVersion to AggregatedMeasuredDataProcess.sql
- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesHandler.cs
- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenARejectedResultIsAvailableTests.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenAnAcceptedResultIsAvailableTests.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequest.proto
I was missing the property I added to the RequestAggregatedMeasureData contract when creating the Process.
> refac: missing support for settlementversion for requesting aggreagated measured data

- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
> fix: only set end date on proto if value is not null

- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequest.proto
> refac: Added grid area to proto buf contract

- README.md
> update code cove

- source/AcceptanceTests/Messages/json/RequestAggregatedMeasureData.json
Settlement version should only be used with a correction request (processtype: D32). Which is not what we're requestion in the acceptance test (D05)
> fix: Removed settlement version

- source/AcceptanceTests/Drivers/EdiDriver.cs
- source/AcceptanceTests/Messages/json/RequestAggregatedMeasureData.json
> fix: business reason on valid aggregated measure data request for accept tests

- source/B2CWebApi/Models/RequestAggregatedMeasureDataMarketDocument.cs
- source/B2CWebApi/Startup.cs
> fix: Made metering point type nullable toward bff

- source/AcceptanceTests/Messages/json/RequestAggregatedMeasureData.json
Fix acceptance test data (end date was equal to start date)
Error: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/6745745510/job/18338393591
> fix: Fix acceptance test period

- source/Api/IntegrationEventHandler.cs
- source/Api/Program.cs
- source/Application/Actors/IActorRepository.cs
- source/Common/Configuration/SqlExtensions.cs
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/Infrastructure/Configuration/DataAccess/SqlDatabaseConnectionFactory.cs
- source/Infrastructure/Configuration/IntegrationEvents/IntegrationEventsConfiguration.cs
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/TestBase.cs
- source/OutgoingMessages.Application/OutgoingMessages.Application.csproj
- source/OutgoingMessages.Application/OutgoingMessages/PeekHandler.cs
- source/Process.Application/Configuration/ProcessConfiguration.cs
- source/Tests/Tests.csproj
> fix: Make Actor repository scoped

- source/B2CWebApi/Startup.cs
> fix: missing ioc configuration for Authenticated Actor

- source/AcceptanceTests/integrationtest.local.settings.sample.json
- source/Process.Application/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeriesRequest.proto
> fix: Matching request contract to that of wholesale

- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/XmlMessageParser.cs
> fix: Grid area is nullable when requesting xml

- source/B2CWebApi/Startup.cs
> feat: add application insight logging

- source/Api/OutgoingMessages/DequeueRequestListener.cs
- source/Api/OutgoingMessages/PeekRequestListener.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenADequeueIsRequestedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenOutgoingMessagesAreCreatedTests.cs
- source/OutgoingMessages.Application/Configuration/ActorMessageQueueConfiguration.cs
- source/OutgoingMessages.Application/OutgoingMessagesClient.cs
- source/OutgoingMessages.Interfaces/IOutgoingMessagesClient.cs
- source/Process.Application/Transactions/AggregatedMeasureData/Notifications/Handlers/EnqueueMessageHandler.cs
- source/Process.Application/Transactions/Aggregations/ForwardAggregationResultHandler.cs
> refac: OutGoingMessagesClient -> OutgoingMessagesClient

- source/AcceptanceTests/AcceptanceTestContext.cs
- source/AcceptanceTests/Tests/B2BErrors/WhenPayloadDataIsDifferentFromTokenDataTests.cs
- source/AcceptanceTests/Tests/TestRunner.cs
- source/AcceptanceTests/WhenAggregatedMeasureDataIsRequestedTests.cs
- source/AcceptanceTests/WhenAggregationResultIsPublishedTests.cs
- source/AcceptanceTests/WhenEbixPeekRequestIsReceivedTests.cs
- source/AcceptanceTests/WhenNewB2BActorIsCreatedTests.cs
- Fix actor role
- Refactor collection name to use same const
> fix: Fix ebix acceptance test actor role

- source/AcceptanceTests/Tests/TestRunner.cs
> feat: ensure we fail fast when configurating accept tests runner

- source/Api/Api.csproj
- source/ArchivedMessages.Application/ArchivedMessages.Application.csproj
- source/ArchivedMessages.Interfaces/ArchivedMessages.Interfaces.csproj
- source/IncomingMessages.Application/IncomingMessages.Application.csproj
- source/IncomingMessages.Interfaces/IncomingMessages.Interfaces.csproj
- source/OutgoingMessages.Application/OutgoingMessages.Application.csproj
- source/OutgoingMessages.Interfaces/OutgoingMessages.Interfaces.csproj
- source/Process.Application/Process.Application.csproj
- source/Process.Interfaces/Process.Interfaces.csproj
Introduce `<PrivateAssets>all</PrivateAssets>` for public sub-projects (Application and Interfaces) of modules
> refac: Ensure domain/infrastructure is considered private assets

- source/AcceptanceTests/AcceptanceTests.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/Tests/Tests.csproj
Introduce the FluentAssertions library to provide us with better assertion functionality. This should hopefully make it easier to write assert statements, and perhaps more importantly, makes it easier to read assert statements and understand why a test fails.
The Analyzers provides us with in-editor help to rewrite existing non-FluentAssertions to FluentAssertions just as it will help us rewrite clumsy assertions writing with FluentAssertions.
See https://fluentassertions.com/ for more details.
> test: Add FluentAssertions and FluentAssertions.Analyzers to test projects

- source/AcceptanceTests/TestData/SynchronousErrorTestData.cs
- source/AcceptanceTests/Tests/B2BErrors/WhenBusinessTypeAndProcessTypeIsNotCorrectTests.cs
- source/AcceptanceTests/Tests/B2BErrors/WhenSchemaIsNotValidTests.cs
- source/AcceptanceTests/Tests/B2BErrors/WhenTransactionIdAndMessageIdIsNotCorrectTests.cs
adding test to ensure that empty and invalid transaction ID is handled correctly
adding test to ensure wrong business sector produces correct error
> test: adding more acceptance test coverage for b2b errors

- NOTICE.md
- README.md
Reference:
https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1813
[MS Teams thread in Developers channel](https://teams.microsoft.com/l/message/19:91c8a12a0ed34734b72b5678596377f5@thread.tacv2/1704894913176?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=e1b7877a-ee7d-4505-a4b2-4989abc2d22a&parentMessageId=1704894913176&teamName=DataHub%203.0&channelName=Developers&createdTime=1704894913176)
> Remove Codecov

- source/AcceptanceTests/Tests/B2BErrors/WhenBusinessTypeAndProcessTypeIsNotCorrectTests.cs
- source/AcceptanceTests/Tests/B2BErrors/WhenTransactionIdAndMessageIdIsNotCorrectTests.cs
> fix: acceptance test asserts

- source/IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/OutgoingMessages.Application/OutgoingMessages/MessagePeeker.cs
> fix: ensure arhived message is created with new id when a market document is created

- source/AcceptanceTests/Drivers/Ebix/EbixDriver.cs
- source/OutgoingMessages.Application/OutgoingMessages/MessageEnqueuer.cs
> test: updating logging for ebix peek

- source/AcceptanceTests/Drivers/WholesaleDriver.cs
- source/Api/Program.cs
> fix: accptance test to create new EnergyResultProducedV2 event

- source/Api/Program.cs
- source/B2CWebApi/Startup.cs
- source/BuildingBlocks.Application/BuildingBlocks.Application.csproj
- source/BuildingBlocks.Application/Configuration/Logging/EnrichExceptionTelemetryInitializer.cs
In order to give a clear overview over domain specific errors we now log an "edi" domain property on all exceptions:
https://teams.microsoft.com/l/message/19:3e48e871-3693-414b-90c9-8556fad401f5_f350ad09-18cb-4937-9900-9f22e332704c@unq.gbl.spaces/1705325202276?context=%7B%22contextType%22%3A%22chat%22%7D
> feat: added domain prop to our exception logging

- source/Api/IntegrationEventHandler.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenAnAggregationResultIsAvailableTests.cs
- source/IntegrationTests/Assertions/AssertOutgoingMessage.cs
- source/OutgoingMessages.Application/OutgoingMessages/MessageEnqueuer.cs
- source/Process.Application/IntegrationEvents/EnergyResultProducedProcessorExtensions.cs
- source/Process.Application/IntegrationEvents/EnergyResultProducedV2Processor.cs
> feat: ignores not supported time serie type for EnergyResult event

- source/AcceptanceTests/TestData/SynchronousErrorTestData.cs
- source/AcceptanceTests/Tests/B2BErrors/WhenBusinessTypeAndProcessTypeIsNotCorrectTests.cs
more coverage for b2b errors ensuring we handle error scenarios correctly
> test: adding acceptance tests for b2b errors relating to type errors

- source/BuildingBlocks.Application/Configuration/BuildingBlockConfiguration.cs
> feat: service bus communication over web socket

- source/ArchivedMessages.Interfaces/GetMessagesQuery.cs
- source/B2CWebApi/Models/SearchArchivedMessagesCriteria.cs
- source/IncomingMessages.Infrastructure/ITransactionIdRepository.cs
- source/IncomingMessages.Infrastructure/Response/XmlResponseFactory.cs
- source/IncomingMessages.Infrastructure/TransactionIdRepository.cs
- source/Infrastructure/InboxEvents/InboxEventsProcessor.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/AggregatedTimeSeriesRequestAcceptedToAggregationResultTests.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenARejectedResultIsAvailableTests.cs
- source/IntegrationTests/Application/Transactions/Aggregations/EnergyResultProducedV2ToAggregationResultTests.cs
- source/IntegrationTests/Factories/OutgoingMessageDtoBuilder.cs
- source/IntegrationTests/Infrastructure/InboxEvents/TestAggregatedTimeSeriesRequestAcceptedHandlerSpy.cs
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/AggregationResultJsonDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/TimeSeriesMarketActivityRecord.cs
- source/OutgoingMessages.Application/MarketDocuments/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataEbixDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataJsonDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/RejectRequestAggregatedMeasureData/RejectedTimeSerieMarketActivityRecord.cs
- source/Process.Application/IntegrationEvents/EnergyResultProducedProcessorExtensions.cs
- source/Process.Application/Transactions/AggregatedMeasureData/Commands/AcceptedAggregatedTimeSerie.cs
- source/Process.Application/Transactions/AggregatedMeasureData/Commands/RejectedAggregatedTimeSeries.cs
- source/Process.Application/Transactions/AggregatedMeasureData/Notifications/AggregatedTimeSerieRequestWasAccepted.cs
- source/Process.Application/Transactions/AggregatedMeasureData/Notifications/AggregatedTimeSeriesRequestWasRejected.cs
- source/Process.Application/Transactions/Aggregations/AggregatedTimeSeriesRequestAcceptedEventMapper.cs
- source/Process.Application/Transactions/Aggregations/AggregatedTimeSeriesRequestRejectedMapper.cs
- source/Process.Application/Transactions/Aggregations/AggregationFactory.cs
- source/Process.Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Process.Domain/Transactions/AggregatedMeasureData/AggregatedTimeSerie.cs
- source/Process.Domain/Transactions/AggregatedMeasureData/OutgoingMessages/RejectedAggregationResultMessage.cs
- source/Process.Domain/Transactions/Aggregations/Aggregation.cs
- source/Process.Domain/Transactions/Aggregations/OutgoingMessage/AggregationResultMessage.cs
- source/Tests/Factories/RejectedTimeSeriesBuilder.cs
> chore: use IReadOnlyCollection as Default

- source/Api/Configuration/ServiceBusExceptionLoggerMiddleware.cs
- source/Api/Program.cs
> feat: only log ServiceBusTrigger calls as exception if its a retry.

- source/Api/Configuration/ServiceBusExceptionLoggerMiddleware.cs
fix based on this commit
https://github.com/Azure/azure-functions-dotnet-worker/pull/1476
> refac: Update ServiceBusExceptionLoggerMiddleware to handle null

- source/Api/host.json
> refac: add retry to host.json

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202402081408 Clear MarketDocuments, Bundles and ActorMessageQueues tables.sql
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/AggregationResultEbixDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/AggregationResultJsonDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/AggregationResultXmlDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/TimeSeriesMarketActivityRecord.cs
Version number is now coming from EnergyResultProducedV2 and Requests for aggregated measure data.
> fix: no more hardcoded version number

- .github/workflows/codeql.yml
- .github/workflows/detect-changes.yml
Ref: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1911
> Remove Node16 deprecation warnings

- source/BuildingBlocks.Domain/Authentication/Restriction.cs
- source/BuildingBlocks.Domain/Models/ActorRole.cs
- source/BuildingBlocks.Domain/Models/BusinessReason.cs
- source/BuildingBlocks.Domain/Models/ChargeType.cs
- source/BuildingBlocks.Domain/Models/Currency.cs
- source/BuildingBlocks.Domain/Models/DocumentFormat.cs
- source/BuildingBlocks.Domain/Models/DocumentType.cs
- source/BuildingBlocks.Domain/Models/EnumerationType.cs
- source/BuildingBlocks.Domain/Models/IncomingDocumentType.cs
- source/BuildingBlocks.Domain/Models/MeasurementUnit.cs
- source/BuildingBlocks.Domain/Models/MessageCategory.cs
- source/BuildingBlocks.Domain/Models/MeteringPointType.cs
- source/BuildingBlocks.Domain/Models/ReasonCode.cs
- source/BuildingBlocks.Domain/Models/Resolution.cs
- source/BuildingBlocks.Domain/Models/SettlementType.cs
- source/BuildingBlocks.Domain/Models/SettlementVersion.cs
> chore: Remove id from enumeration type

- source/BuildingBlocks.Domain/Models/ProductType.cs
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/AggregationResultEbixDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/AggregationResultJsonDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/AggregationResult/AggregationResultXmlDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/WholesaleCalculations/WholesaleCalculationXmlDocumentWriter.cs
Introduced a new domain model for representing the different product type we currently supports. 
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/124
> feat: added new product type

- .github/workflows/cd.yml
- .github/workflows/ci-dotnet.yml
- .github/workflows/ci-orchestrator.yml
Reference: https://app.zenhub.com/workspaces/the-outlaws-6193fe815d79fc0011e741b1/issues/gh/energinet-datahub/team-the-outlaws/1879
> Update .github to v13

- source/IncomingMessages.Infrastructure/RequestAggregatedMeasureDataParsers/JsonMessageParser.cs
- source/Tests/CimMessageAdapter/Messages/RequestAggregatedMeasureData/MessageParserTests.cs
- source/Tests/CimMessageAdapter/Messages/json/AggregatedMeasure/InvalidJsonAggregatedMeasureData.json
- source/Tests/Tests.csproj
> fix: validation json document catched an unhandled exception if fails

- source/Process.Application/Transactions/Aggregations/AggregationMessageResultFactory.cs
> fix: original transaction id for request reponse  was missing

- source/IncomingMessages.Infrastructure/RequestAggregatedMeasureDataParsers/XmlMessageParser.cs
- source/Tests/CimMessageAdapter/Messages/RequestAggregatedMeasureData/MessageParserTests.cs
- source/Tests/CimMessageAdapter/Messages/xml/AggregatedMeasure/VersionIndexOutOfRangeRequestAggregatedMeasureData.xml
- source/Tests/Tests.csproj
> feat: handle missing value in xml version

- source/Tests/Infrastructure/OutgoingMessages/Asserts/AssertXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/WholesaleCalculations/AssertWholesaleCalculationResultEbixDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/WholesaleCalculations/AssertWholesaleCalculationResultJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/WholesaleCalculations/AssertWholesaleCalculationResultXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/WholesaleCalculations/IAssertWholesaleCalculationResultDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/WholesaleCalculations/SampleData.cs
- source/Tests/Infrastructure/OutgoingMessages/WholesaleCalculations/WholesaleCalculationResultDocumentWriterTests.cs
We now also validate the coding scheme for certain fields in CIM for wholesale calculations
#795, #779
> feat: Validate coding scheme for CIM for WholesaleCalculationSeries

- source/Process.Application/IntegrationEvents/AmountPerChargeResultProducedV1Processor.cs
- source/Process.Application/Transactions/Mappers/SettlementTypeMapper.cs
- source/Tests/Application/Process/Transactions/Mappers/BaseEnumMapperTests.cs
- source/Tests/Application/Process/Transactions/Mappers/SettlementTypeMapperTests.cs
> fix: allow nullable mapping of settlement type for amount per charge result

- source/Api/Api.csproj
- source/Api/Program.cs
- source/DataAccess/DataAccess.csproj
- source/DataAccess/Extensions/DependencyInjection/DataAccessExtensions.cs
- source/DataAccess/UnitOfWork.cs
- source/EDI.sln
- source/Infrastructure/Extensions/DependencyInjection/CompositionRoot.cs
- source/Infrastructure/Infrastructure.csproj
- source/IntegrationTests/TestBase.cs
New project structure after introduction of DataAccess:
> refac: Introduce DataAccess module

- source/ArchitectureTests/CompositionRootTests.cs
- source/B2CWebApi/Extensions/DependencyInjection/SwaggerExtensions.cs
- source/B2CWebApi/Program.cs
> refac: Made swagger extension

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/ArchivedMessages.Application/ArchivedMessages.Application.csproj
- source/ArchivedMessages.Infrastructure/ArchivedMessages.Infrastructure.csproj
- source/B2CWebApi/B2CWebApi.csproj
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IncomingMessages.Interfaces/IncomingMessages.Interfaces.csproj
- source/IntegrationEvents/IntegrationEvents.Infrastructure/EventProcessors/MonthlyAmountPerChargeResultProducedV1Processor.cs
- source/IntegrationEvents/IntegrationEvents.Infrastructure/IntegrationEvents.Infrastructure.csproj
- source/OutgoingMessages.Domain/OutgoingMessages.Domain.csproj
- source/Process.Application/Process.Application.csproj
- source/Process.Application/Transactions/Aggregations/AggregationMessageResultFactory.cs
- source/Process.Domain/Process.Domain.csproj
- source/Tests/Tests.csproj
The updated project diagram (excluding tests)
And with tests
> refac: Clean-up project references and dependencies

- source/B2CWebApi/Program.cs
> chore: Removed function logging from webapp 

- source/Api/Program.cs
- source/Infrastructure/Extensions/DependencyInjection/CompositionRoot.cs
- source/Infrastructure/Extensions/DependencyInjection/HealthCheckExtensions.cs
- source/IntegrationTests/TestBase.cs
> refac: Removed bearer auth from composition root

- source/AcceptanceTests/Drivers/Ebix/EbixDriver.cs
- source/AcceptanceTests/Dsl/EbixRequestDsl.cs
> test: Acceptancetest Ebix fix

- source/ArchivedMessages.Infrastructure/QueryBuilder.cs
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/121
> refac: search archived message with sender or receiver

- source/AcceptanceTests/Drivers/MessageFactories/AmountPerChargeResultProducedV1Factory.cs
- source/BuildingBlocks.Domain/Models/Resolution.cs
- source/IntegrationEvents/IntegrationEvents.Infrastructure/EventProcessors/AmountPerChargeResultProducedV1Processor.cs
- source/IntegrationEvents/IntegrationEvents.Infrastructure/Factories/Mappers/ResolutionMapper.cs
- source/IntegrationEvents/IntegrationEvents.Infrastructure/Factories/WholesaleServicesMessageFactory.cs
- source/IntegrationTests/Application/Transactions/WholesaleCalculations/AmountPerChargeResultProducedV1Tests.cs
- source/IntegrationTests/Factories/AmountPerChargeResultProducedV1EventBuilder.cs
- source/OutgoingMessages.Domain/MarketDocuments/EbixCode.cs
- source/Tests/Application/Process/Transactions/Mappers/ResolutionMapperTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/NotifyWholesaleServicesDocumentWriterTests.cs
Support resolution in NotifyWholesaleServices (non-monthly). Adds mapping to `ResolutionMapper` and adds property tests to document writers & integration events
Task: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/136
> feat: Support resolution in NotifyWholesaleServices (non-monthly)

- source/Api/Configuration/Authentication/ClaimsMap.cs
Added missing access to B2B Api for grid and system operator.
> feat: allow b2b access for system operator and grid operator

- source/IntegrationEvents/IntegrationEvents.Application/Configuration/IntegrationEventExtensions.cs
- source/IntegrationEvents/IntegrationEvents.Infrastructure/EventProcessors/AmountPerChargeResultProducedV1Processor.cs
- source/IntegrationEvents/IntegrationEvents.Infrastructure/EventProcessors/MonthlyAmountPerChargeResultProducedV1Processor.cs
- source/IntegrationEvents/IntegrationEvents.Infrastructure/Factories/WholesaleServicesMessageFactory.cs
- source/IntegrationTests/Application/Transactions/WholesaleCalculations/AmountPerChargeResultProducedV1Tests.cs
- source/IntegrationTests/Application/Transactions/WholesaleCalculations/MonthlyAmountPerChargeResultProducedV1Tests.cs
- source/OutgoingMessages.Domain/OutgoingMessages/Queueing/OutgoingMessage.cs
Overwrite charge owner to grid owner if we are dealing with taxrelated wholesale. This is to redirect the messages to the energy supplier and grid owner, as opposed to the energy supplier and TSO.
> feat: Handle IsTax flag for wholesale services

- .editorconfig
> style: Prefer newline before operator

- source/B2CWebApi/Extensions/DependencyInjection/JwtExtensions.cs
- source/B2CWebApi/Program.cs
> Refac: Isolated b2c auth

- source/Api/HostFactory.cs
- source/Api/Program.cs
- source/Api/ProgramHelper.cs
- source/ArchitectureTests/CompositionRootTests.cs
- source/IntegrationTests/TestBase.cs
> refac: API program to minimal hosting model

- source/Api/HostFactory.cs
> fix: Add middlewhere 

- source/IntegrationTests/Fixtures/IntegrationTestFixture.cs
> test: clean up WholesaleServicesProcessChargeTypes and WholesaleServicesProcesses tables

- source/B2CWebApi/Factories/RequestAggregatedMeasureDataHttpFactory.cs
- source/BuildingBlocks.Domain/Models/ChargeType.cs
- source/BuildingBlocks.Domain/Models/ProductType.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataMarketDocumentBuilder.cs
- source/IntegrationTests/Application/Transactions/Aggregations/SampleData.cs
- source/IntegrationTests/Assertions/AssertXmlMessage.cs
- source/OutgoingMessages.Application/DocumentWriters/Json/JsonHeaderWriter.cs
- source/OutgoingMessages.Application/DocumentWriters/Xml/XmlHeaderWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataJsonDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataXmlDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataJsonDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataXmlDocumentWriter.cs
- source/OutgoingMessages.Domain/MarketDocuments/CimCode.cs
- source/Tests/Infrastructure/OutgoingMessages/CimCodeTranslationTests.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/AssertNotifyAggregatedMeasureDataJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/AssertNotifyAggregatedMeasureDataXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestAggregatedMeasureData/AssertRejectRequestAggregatedMeasureDataJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/RejectRequestAggregatedMeasureData/AssertRejectRequestAggregatedMeasureDataXmlDocument.cs
> Chore: Remove cimCode.of and added test to ensure BuildingBlocks codes does not change

- source/RequestResponse/source/RequestResponse/Requests/WholesaleServicesRequestAccepted.proto
> fix: Rename point of wholesaleService contract

- source/BuildingBlocks.Domain/Models/DocumentType.cs
- source/IntegrationTests/Application/OutgoingMessages/DocumentFactory/DocumentFactoryTests.cs
- source/IntegrationTests/Application/Transactions/WholesaleCalculations/WhenARejectedWholesaleServicesIsAvailableTests.cs
- source/IntegrationTests/Infrastructure/Configuration/InternalCommands/InternalCommandRegistrationTests.cs
- source/IntegrationTests/TestBase.cs
- source/OutgoingMessages.Application/OutgoingMessagesClient.cs
- source/OutgoingMessages.Domain/OutgoingMessages/Queueing/OutgoingMessage.cs
- source/OutgoingMessages.Interfaces/IOutgoingMessagesClient.cs
- source/OutgoingMessages.Interfaces/Models/RejectedWholesaleServicesMessageDto.cs
- source/Process.Application/Extensions/DependencyInjection/InternalCommandExtensions.cs
- source/Process.Application/Extensions/DependencyInjection/ProcessExtensions.cs
- source/Process.Application/Transactions/WholesaleServices/Commands/Handlers/RejectProcessWhenRejectedWholesaleServicesIsAvailable.cs
- source/Process.Application/Transactions/WholesaleServices/Commands/RejectedWholesaleServices.cs
- source/Process.Application/Transactions/WholesaleServices/Notifications/Handlers/EnqueueRejectedWholesaleServicesMessageHandler.cs
- source/Process.Application/Transactions/WholesaleServices/Notifications/Handlers/WhenAnRejectedWholesaleServicesRequestIsAvailable.cs
- source/Process.Application/Transactions/WholesaleServices/Notifications/WholesaleServicesRequestRejectedMapper.cs
- source/Process.Application/Transactions/WholesaleServices/Notifications/WholesaleServicesRequestWasRejected.cs
- source/Process.Domain/Transactions/WholesaleServices/ProcessEvents/EnqueueRejectedWholesaleServicesMessageEvent.cs
- source/Process.Domain/Transactions/WholesaleServices/RejectedWholesaleServicesRequest.cs
- source/Process.Domain/Transactions/WholesaleServices/WholesaleServicesProcess.cs
> feat: Handle rejected wholesale services requests

- source/IntegrationEvents/IntegrationEvents.Infrastructure/IntegrationEvents.Infrastructure.csproj
- source/IntegrationTests/Application/Actors/CreateActorsTests.cs
- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingOutgoingMessageTests.cs
- source/IntegrationTests/TestBase.cs
- source/MasterData.Infrastructure/MasterData.Infrastructure.csproj
- source/Process.Infrastructure/Process.Infrastructure.csproj
> refac: Upgrade and use same Dapper version

- source/Process.Infrastructure/Transactions/WholesaleServices/ServiceBusMessageFactory.cs
- source/RequestResponse/source/RequestResponse/Requests/WholesaleServices/WholesaleServicesRequest.proto
Update WholesaleServicesRequest protobuf contract
https://github.com/Energinet-DataHub/opengeh-wholesale/pull/2012
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/101
> feat: Update WholesaleServicesRequest protobuf contract

- source/BuildingBlocks.Domain/Models/Resolution.cs
- source/OutgoingMessages.Domain/OutgoingMessages/Queueing/OutgoingMessage.cs
- source/Process.Infrastructure/Transactions/WholesaleServices/ServiceBusMessageFactory.cs
> fix: avoid sending cim codes for resolution on wholesaleService requests

- source/BuildingBlocks.Domain/Models/ChargeType.cs
- source/Process.Infrastructure/Transactions/WholesaleServices/ServiceBusMessageFactory.cs
> fix: avoid sending cim codes for charge type on wholesaleService requests

- source/IncomingMessages.Application/IncomingMessageClient.cs
> fix: ensure we archive incoming message with correct document type

- source/RequestResponse/source/RequestResponse/IntegrationEvents/MarketParticipant/ProcessDelegationConfigured.cs
- source/RequestResponse/source/RequestResponse/IntegrationEvents/MarketParticipant/ProcessDelegationConfigured.proto
> refac: ProcessDelegationConfigured replaced MessageDelegationCofigured

- source/IntegrationTests/Application/IncomingMessages/RequestWholesaleSettlement.json
- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
> test: ensure data is correct when archiving incoming messages

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202403211328 Create ProcessDelegationConfigured table.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202403211329 Drop MessageDelegationConfigured table.sql
> refac: new table for ProcessDelegationConfigured

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202403211123 Rename ReceiverId and ReceiverRole to DocumentReceiver in OutgoingMessage table.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202403211236 Add ReceiverNumber and ReceiverRole columns to Outgoing Messages.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202403211302 Remove IsPublished from OutgoingMessage table.sql
- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingOutgoingMessageTests.cs
- source/IntegrationTests/Application/Transactions/WholesaleServices/WhenAnAcceptedWholesaleServicesResultIsAvailableTests.cs
- source/IntegrationTests/Assertions/AssertOutgoingMessage.cs
- source/OutgoingMessages.Domain/OutgoingMessages/OutgoingMessageBundle.cs
- source/OutgoingMessages.Domain/OutgoingMessages/Queueing/OutgoingMessage.cs
- source/OutgoingMessages.Infrastructure/OutgoingMessages/OutgoingMessageEntityConfiguration.cs
- source/OutgoingMessages.Infrastructure/OutgoingMessages/OutgoingMessageRepository.cs
> refac: more explixit about the outgoing message receiver and document receiver

- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingOutgoingMessageTests.cs
- source/OutgoingMessages.Domain/OutgoingMessages/Queueing/OutgoingMessage.cs
- source/OutgoingMessages.Interfaces/Models/AcceptedEnergyResultMessageDto.cs
- source/OutgoingMessages.Interfaces/Models/AcceptedWholesaleServicesMessageDto.cs
- source/OutgoingMessages.Interfaces/Models/EnergyResultMessageDto.cs
- source/OutgoingMessages.Interfaces/Models/OutgoingMessageDto.cs
- source/OutgoingMessages.Interfaces/Models/RejectedEnergyResultMessageDto.cs
- source/OutgoingMessages.Interfaces/Models/RejectedWholesaleServicesMessageDto.cs
- source/OutgoingMessages.Interfaces/Models/WholesaleServicesMessageDto.cs
> refac: rename receiver id to be aligned with outgoing message domain model

- source/IntegrationEvents/IntegrationEvents.Application/Configuration/IntegrationEventExtensions.cs
> bug: missing descriptor on ProcessDelegationConfigured

- source/OutgoingMessages.Interfaces/Models/WholesaleServicesMessageDto.cs
> retrigger CD

- source/IntegrationEvents/IntegrationEvents.Infrastructure/Factories/Mappers/EicFunctionMapper.cs
- source/OutgoingMessages.Interfaces/Models/WholesaleServicesMessageDto.cs
> bug: Add Delegated mapping for EicFunction

- source/Api/Authentication/ClaimsMap.cs
> refac: allow actors with delegated role

- .gitignore
- source/AcceptanceTests/AcceptanceTestFixture.cs
- source/AcceptanceTests/AcceptanceTests.csproj
- https://github.com/Energinet-DataHub/dh3-dev-secrets/pull/36
> test: run acceptance tests against dev00x

- .github/workflows/detect-changes.yml
> refac: deploy if changes are made within source or workflows

- source/BuildingBlocks.Domain/Models/SettlementVersion.cs
- source/IntegrationTests/Application/IncomingMessages/WholesaleServices/WhenWholesaleServicesIsRequestedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/IntegrationTests/Factories/EnergyResultMessageDtoBuilder.cs
- source/IntegrationTests/TestBase.cs
- source/Process.Application/Transactions/AggregatedMeasureData/InitializeAggregatedMeasureDataProcessesHandler.cs
- source/Process.Application/Transactions/WholesaleServices/InitializeWholesaleServicesProcessesHandler.cs
- source/Process.Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcessEntityConfiguration.cs
- source/Process.Infrastructure/Transactions/WholesaleServices/WholesaleServicesProcessEntityConfiguration.cs
- source/Tests/BuildingBlocks/Models/SettlementVersionTests.cs
Allow unused settlement versions, to comply with allowed schema values
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/46
> refac: Allow unused settlement versions

- source/OutgoingMessages.Application/MarketDocuments/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataEbixDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataJsonDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataXmlDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/NotifyWholesaleServices/NotifyWholesaleServicesEbixDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/NotifyWholesaleServices/NotifyWholesaleServicesJsonDocumentWriter.cs
- source/OutgoingMessages.Application/MarketDocuments/NotifyWholesaleServices/NotifyWholesaleServicesXmlDocumentWriter.cs
- source/OutgoingMessages.Domain/MarketDocuments/CimCode.cs
- source/OutgoingMessages.Domain/MarketDocuments/EbixCode.cs
- source/Tests/Domain/OutgoingMessages/MarketDocuments/CimCodeTests.cs
- source/Tests/Domain/OutgoingMessages/MarketDocuments/EbixCodeTests.cs
- source/Tests/Infrastructure/OutgoingMessages/Asserts/AssertXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/NotifyWholesaleServicesDocumentWriterTests.cs
> fix: ensure we write quantity quality correct

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202404081346 Update unique key constraint on BusinessTransactionId in AggregatedMeasureDataProcesses.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202404081352 Add unique key constraint on BusinessTransactionId in WholesaleServicesProcesses.sql
- source/IntegrationTests/Application/Transactions/WholesaleServices/WhenAnAcceptedWholesaleServicesResultIsAvailableTests.cs
- source/IntegrationTests/Application/Transactions/WholesaleServices/WholesaleServicesProcessBuilder.cs
> fix: Transaction id on processes should only be unique for the requested by actor

- source/IncomingMessages.Application/IncomingMessages.Application.csproj
> chore: Added explicit dapper reference in IncomingMessages.Application

- source/IntegrationTests/Behaviors/ExcludeFromNameConventionCheckAttribute.cs
- source/IntegrationTests/Behaviors/MetaTests.cs
- source/IntegrationTests/TestBase.cs
> feat: Add test for name convention in integration test

- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestTests.cs
- source/IntegrationTests/EventBuilders/AggregatedTimeSeriesRequestAcceptedEventBuilder.cs
- source/IntegrationTests/EventBuilders/RequestAggregatedMeasureDataEventBuilder.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/AssertNotifyAggregatedMeasureDataJsonDocument.cs
> test: Add behaviour test example for a request

- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestTests.cs
> fix: Incorrect naming of behaviour test/helper method

- source/Api/IncomingMessages/IncomingMessageReceiver.cs
- source/BuildingBlocks.Application/FeatureFlag/IFeatureFlagManager.cs
- source/BuildingBlocks.Application/FeatureFlag/MicrosoftFeatureFlagManager.cs
- source/IntegrationEvents.Infrastructure/EventProcessors/AmountPerChargeResultProducedV1Processor.cs
- source/IntegrationEvents.Infrastructure/EventProcessors/MonthlyAmountPerChargeResultProducedV1Processor.cs
- source/IntegrationTests/Application/Transactions/WholesaleCalculations/AmountPerChargeResultProducedV1Tests.cs
- source/IntegrationTests/Application/Transactions/WholesaleCalculations/MonthlyAmountPerChargeResultProducedV1Tests.cs
- source/IntegrationTests/TestDoubles/FeatureFlagManagerStub.cs
- source/OutgoingMessages.Application/MessageEnqueuer.cs
An attempt to address the InvalidOperationException: Collection was modified; enumeration operation may not execute.
(https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD003.md)
> refac: feature manager to use methods

- .editorconfig
> style: Disable "Mark members as static" recommendation.

- source/AcceptanceTests/AcceptanceTests.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/ArchivedMessages.Application/ArchivedMessages.Application.csproj
- source/B2BApi/B2BApi.csproj
- source/BuildingBlocks.Application/BuildingBlocks.Application.csproj
- source/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/Tests/Tests.csproj
> chore: Update TestCommon package (and it's dependencies)

- .github/workflows/ci-dotnet.yml
> build: Add job name when running tests

- source/AcceptanceTests/Drivers/EdiProcessesDriver.cs
> fix: acceptance tests to set processes state to finally state to avoid creating messages

- source/AcceptanceTests/Drivers/EdiProcessesDriver.cs
> test: Fix table columns for WholesaleServicesProcesses in subsystem tests

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202404241647 Add WholesaleServicesProcessGridAreas foreign key.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202404241647 Create AggregatedMeasureDataProcessGridAreas table.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202404241708 Rename MeteringGridAreaDomainId to RequestedGridArea for AggregatedMeasureDataProcesses table.sql
- source/IncomingMessages.Infrastructure/Factories/InitializeAggregatedMeasureDataProcessDtoFactory.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesCommandTests.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataMarketDocumentBuilder.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/AggregatedTimeSeriesRequestAcceptedToAggregationResultTests.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenARejectedResultIsAvailableTests.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenAnAcceptedResultIsAvailableTests.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestTests.cs
- source/IntegrationTests/EventBuilders/AggregatedTimeSeriesRequestAcceptedEventBuilder.cs
- source/IntegrationTests/Fixtures/IntegrationTestFixture.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/IncomingMessageReceiverTests.cs
- source/Process.Application/Transactions/AggregatedMeasureData/InitializeAggregatedMeasureDataProcessesHandler.cs
- source/Process.Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Process.Domain/Transactions/AggregatedMeasureData/WholesaleServicesProcessGridArea.cs
- source/Process.Domain/Transactions/WholesaleServices/WholesaleServicesProcess.cs
- source/Process.Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcessEntityConfiguration.cs
- source/Process.Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/Process.Infrastructure/Transactions/WholesaleServices/WholesaleServicesRequestFactory.cs
- source/Process.Interfaces/InitializeAggregatedMeasureDataProcessDto.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeries/AggregatedTimeSeriesRequest.proto
- source/Tests/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactoryTests.cs
Support multiple grid areas for aggregated measure data process
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/148
> feat: Support multiple grid areas for aggregated measure data process

- source/AcceptanceTests/Drivers/EdiProcessesDriver.cs
> test: Fix process acceptance test

- source/B2BApi/EventListeners/InboxEventListener.cs
- source/B2BApi/EventListeners/IntegrationEventListener.cs
- source/B2BApi/EventListeners/ProcessInitializationListener.cs
> chores: added retry comments on service bus listners

- source/AcceptanceTests/AcceptanceTests.csproj
- source/IntegrationEvents.Application/IntegrationEvents.Application.csproj
- source/IntegrationEvents.Infrastructure/Factories/Mappers/ResolutionMapper.cs
- source/IntegrationEvents.Infrastructure/IntegrationEvents.Infrastructure.csproj
Ensure we can support hourly resolution for energy result producedd
Depends on:
- https://github.com/Energinet-DataHub/opengeh-wholesale/pull/2195
> feat: support hourly resolution for energy result produced

- source/AcceptanceTests/AcceptanceTests.csproj
- source/AcceptanceTests/Drivers/Ebix/EbixReference.cs
- source/B2BApi/B2BApi.csproj
- source/BuildingBlocks.Application/BuildingBlocks.Application.csproj
- source/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
- source/DataAccess/DataAccess.csproj
- source/IntegrationTests/B2BApi/Mocks/FunctionContextMock.cs
- source/IntegrationTests/DocumentAsserters/NotifyAggregatedMeasureDataDocumentAsserter.cs
- source/IntegrationTests/DocumentAsserters/RejectRequestAggregatedMeasureDataDocumentAsserter.cs
- source/IntegrationTests/DocumentAsserters/RejectRequestWholesaleSettlementDocumentAsserter.cs
- source/OutgoingMessages.Application/OutgoingMessages.Application.csproj
- source/Process.Application/Process.Application.csproj
- source/Process.Infrastructure/Process.Infrastructure.csproj
- source/Tests/CimMessageAdapter/Messages/RequestAggregatedMeasureData/MessageParserTests.cs
> chore: Update nugets

- source/B2BApi/B2BApi.csproj
- source/B2CWebApi/B2CWebApi.csproj
- source/B2CWebApi/Program.cs
> refac: Remove use of NuGet package Logging from geh-core

- source/IntegrationTests/Behaviours/AggregatedMeasureDataBehaviourTestBase.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestWithDelegationTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestWithDelegationTests.cs
- source/IntegrationTests/Behaviours/IntegrationEvents/GivenAmountPerChargeResultProducedV1ReceivedTests.cs
- source/IntegrationTests/Behaviours/WholesaleServicesBehaviourTestBase.cs
- source/IntegrationTests/DocumentAsserters/NotifyAggregatedMeasureDataDocumentAsserter.cs
- source/IntegrationTests/EventBuilders/WholesaleServicesResponseEventBuilder.cs
- Refactor BehaviourTestBase to separate wholesale services and aggregated measure data
- Add `GivenWholesaleServicesRequestTests` behaviour tests
> test: Behaviour test for RequestWholesaleServices (without delegation)

- source/ArchitectureTests/RegistrationTests.cs
- source/B2BApi/EventListeners/InboxEventListener.cs
- source/B2BApi/EventListeners/IntegrationEventListener.cs
- source/B2BApi/EventListeners/ProcessInitializationListener.cs
- source/B2BApi/local.settings.sample.json
- source/B2CWebApi/appsettings.sample.json
- source/BuildingBlocks.Application/Extensions/Options/ServiceBusOptions.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/TestBase.cs
> fix: Add service bus connection string to listeners

- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesCommandTests.cs
- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
- source/IntegrationTests/Application/IncomingMessages/WholesaleServices/WhenWholesaleServicesIsRequestedTests.cs
- source/IntegrationTests/Behaviours/AggregatedMeasureDataBehaviourTestBase.cs
- source/IntegrationTests/Behaviours/AggregatedTimeSeriesMessageAssertionInput.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestWithDelegationTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestWithDelegationTests.cs
- source/IntegrationTests/Behaviours/WholesaleServicesBehaviourTestBase.cs
- source/IntegrationTests/Behaviours/WholesaleServicesMessageAssertionInput.cs
- source/IntegrationTests/TestDoubles/ServiceBusSenderSpy.cs
> test: Add behaviour test for requests with multiple series

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202405031407 Update AggregatedMeasureDataProcesses columns.sql
> refac: Remove nullable from columns in AggregatedMeasureDataProcesses table

- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedWithDelegationTests.cs
- source/MasterData.Infrastructure/ProcessDelegation/ProcessDelegationRepository.cs
> fix: Fix incoming messages with stopped delegations

- source/B2BApi/HostFactory.cs
> chore: Removed redundant logging registration

- source/OutgoingMessages.Application/UseCases/EnqueueMessage.cs
> refac: log event id when message has been enqueued

- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestTests.cs
- source/IntegrationTests/EventBuilders/WholesaleServicesResponseEventBuilder.cs
> test: behaviour test for incorrect energy supplier for wholesale settlement requests

- source/B2BApi/host.json
The loglevels are extracted from appsetting and not from host.json. Hence these values doesn't do anything
> chore: Remove logLevel from host.json

- source/IntegrationTests/Behaviours/IntegrationEvents/GivenTotalMonthlyAmountResultProducedV1ReceivedTests.cs
- source/OutgoingMessages.Interfaces/Models/WholesaleServicesTotalSumMessageDto.cs
> fix: If Amount is missing for total sum, then quality is missing

- source/IncomingMessages.Application/IncomingMessageClient.cs
> fix: validation error logging

- source/Process.Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeries/AggregatedTimeSeriesRequest.proto
> fix: Updated meteringPointType in aggregated request proto

- source/AcceptanceTests/AcceptanceTests.csproj
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/B2BApi.AppTests/B2BApi.AppTests.csproj
- source/B2BApi/B2BApi.csproj
- source/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/OutgoingMessages.Domain/OutgoingMessages.Domain.csproj
- source/Process.Application/Process.Application.csproj
- source/Process.Domain/Process.Domain.csproj
- source/SystemTests/SystemTests.csproj
- source/Tests/Tests.csproj
> chore: Nuget updates

- source/B2CWebApi/B2CWebApi.csproj
> chore: update nuget core web app

- source/IntegrationEvents.Infrastructure/EventProcessors/EnergyResultProducedV2Processor.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenAnEnergyResultIsAvailableTests.cs
> feat: skip EnergyResult events to es_brp_ga from Wholesale Calculation

- source/B2CWebApi/Controllers/RequestAggregatedMeasureDataController.cs
- source/B2CWebApi/Controllers/RequestWholesaleSettlementController.cs
- source/IncomingMessages.Application/IncomingMessageClient.cs
- source/IncomingMessages.Infrastructure/ValidationErrors/ValidationError.cs
> feat: Add errors in B2C response

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202406071044 Lowercase MessageId for old bundles.sql
- source/B2BApi/OutgoingMessages/DequeueRequestListener.cs
- source/IntegrationTests/Factories/EnergyResultMessageDtoBuilder.cs
- source/OutgoingMessages.Domain/Models/ActorMessagesQueues/ActorMessageQueue.cs
- source/Tests/Domain/OutgoingMessages/Queueing/ActorMessageQueueTests.cs
> fix: Script to lowercase old messageIds of bundles

- source/IncomingMessages.Application/IncomingMessageClient.cs
- source/IncomingMessages.Infrastructure/ValidationErrors/ValidationError.cs
> fix: Add explicit .ToString on errors in IncomingMessages

- source/ArchitectureTests/ArchitectureTests.csproj
- source/ArchitectureTests/RegistrationTests.cs
- source/BuildingBlocks.Domain/Models/IncomingDocumentType.cs
- source/IncomingMessages.Application/Extensions/DependencyInjection/IncomingMessagesExtensions.cs
- source/IncomingMessages.Application/IncomingMessageClient.cs
- source/IncomingMessages.Application/MessageParser/AggregatedMeasureDataRequestMessageParsers/B2CJsonMessageParser.cs
- source/IncomingMessages.Application/MessageParser/AggregatedMeasureDataRequestMessageParsers/XmlMessageParser.cs
- source/IncomingMessages.Application/MessageParser/BaseParsers/JsonBaseParser.cs
- source/IncomingMessages.Application/MessageParser/MarketMessageParser.cs
- source/IncomingMessages.Application/MessageParser/WholesaleSettlementMessageParsers/B2CJsonMessageParser.cs
- source/IncomingMessages.Application/MessageParser/WholesaleSettlementMessageParsers/JsonMessageParser.cs
- source/IncomingMessages.Interfaces/IIncomingMessageClient.cs
- source/Tests/CimMessageAdapter/Messages/RequestAggregatedMeasureData/MessageParserTests.cs
- source/Tests/CimMessageAdapter/Messages/WholesaleSettlementMessageParsers/MessageParserTests.cs
> fix: Corrected document type for b2c wholesale requests

- source/ApplyDBMigrationsApp/Helpers/DbUpgradeRunner.cs
- source/ApplyDBMigrationsApp/Helpers/UpgradeFactory.cs
> fix: Change timeout of DBUP to 5 min

- source/OutgoingMessages.Application/Extensions/DependencyInjection/OutgoingMessagesExtensions.cs
Part of:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/199
> refac: Re-enable health check

- source/IncomingMessages.Application/IncomingMessageClient.cs
- source/IncomingMessages.Infrastructure/IncomingMessageReceiver.cs
> feat: log when request is received

- source/IncomingMessages.Application/IncomingMessageDelegator.cs
- source/IntegrationEvents.Infrastructure/Factories/Mappers/MeasurementUnitMapper.cs
- source/OutgoingMessages.Infrastructure/Databricks/DeltaTableMappers/MeasurementUnitMapper.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/EnergyResultPerBrpGridArea.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/EnergyResultPerEnergySupplierBrpGridArea.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/EnergyResultPerGridArea.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Factories/EnergyResultMessageDtoFactory.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Factories/EnergyResultPerGridAreaFactory.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Models/AggregatedTimeSeries.cs
- source/Tests/Application/OutgoingMessages/EnergyResultPerGridAreaFactoryTests.cs
> fix: Getting measurement unit from databricks

- source/ArchivedMessages.Infrastructure/QueryBuilder.cs
- source/IntegrationTests/Application/ArchivedMessages/WhenArchivedMessageIsCreatedTests.cs
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
> fix: Archived messages search query had or-statement without parenthesis

- source/IntegrationEvents.Application/IntegrationEventHandler.cs
> feat: read uncommitted changes on integration event handler transaction

- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Queries/EnergyResultPerBrpGridAreaQuery.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Queries/EnergyResultPerEnergySupplierBrpGridAreaQuery.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Queries/EnergyResultPerGridAreaQuery.cs
Part of:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/199
> refac: Rename databricks views

- source/AcceptanceTests/AcceptanceTestFixture.cs
- source/AcceptanceTests/Drivers/MessageFactories/CalculationCompletedV1Factory.cs
- source/AcceptanceTests/Drivers/MessageFactories/EnergyResultProducedV2Factory.cs
- source/AcceptanceTests/Drivers/WholesaleDriver.cs
- source/AcceptanceTests/Dsl/CalculationCompletedDsl.cs
- source/AcceptanceTests/Tests/WhenCalculationCompletedIsPublishedTests.cs
- source/AcceptanceTests/acceptancetest.local.settings.sample.json
- source/B2BApi/Functions/EnqueueMessages/Activities/SendActorMessagesEnqueuedActivity.cs
- source/IntegrationEvents.Infrastructure/EventProcessors/CalculationCompletedV1Processor.cs
- Add acceptance test for `CalculationCompletedEvent` balance fixing
- Fix `ActorMessagesEnqueued` missing reference id
- Add extra logging
- Acceptance test variables: https://github.com/Energinet-DataHub/dh3-automation/pull/414
- Dev secrets: https://github.com/Energinet-DataHub/dh3-dev-secrets/pull/55
- Enable feature flags: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/1632 https://github.com/Energinet-DataHub/dh3-infrastructure/pull/1637
> feat: Enable CalculationCompletedEvent for balance fixing calculations

- source/BuildingBlocks.Domain/Models/MeteringPointType.cs
- source/IntegrationTests/EventBuilders/RequestWholesaleServicesRequestBuilder.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/BusinessMessageBuilder.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/RequestAggregatedMeasureData/IncomingMessageReceiverTests.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/TestData/SampleData.cs
- source/IntegrationTests/Infrastructure.CimMessageAdapter/Messages/WholesaleServices/IncomingWholesaleServiceTests.cs
- source/Tests/CimMessageAdapter/Response/XmlResponseFactoryTests.cs
> feat: add test to ensure correct message type for wholesale services requests

- source/Contracts/Requests/AggregatedTimeSeries/AggregatedTimeSeriesRequestAccepted.proto
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenAnAcceptedResultIsAvailableTests.cs
- source/IntegrationTests/Behaviours/AggregatedMeasureDataBehaviourTestBase.cs
- source/IntegrationTests/DocumentAsserters/NotifyWholesaleServicesDocumentAssertionInput.cs
- source/IntegrationTests/EventBuilders/AggregatedTimeSeriesResponseEventBuilder.cs
- source/IntegrationTests/Infrastructure/Authentication/MarketActors/JwtBuilder.cs
- source/Process.Application/Transactions/AggregatedMeasureData/Notifications/AggregatedTimeSeriesRequestWasAccepted.cs
- source/Process.Application/Transactions/AggregatedMeasureData/Notifications/Handlers/NotifyWholesaleThatAggregatedMeasureDataIsRequestedHandler.cs
- source/Process.Application/Transactions/AggregatedMeasureData/Notifications/Handlers/WhenAnAcceptedAggregatedTimeSeriesRequestIsAvailable.cs
- source/Process.Application/Transactions/Aggregations/AcceptedEnergyResultMessageDtoFactory.cs
- source/Process.Application/Transactions/Aggregations/EnergyResultTimeSeriesRequestAcceptedEventMapper.cs
- source/Process.Application/Transactions/WholesaleServices/WholesaleServicesRequestAcceptedMapper.cs
- source/Process.Domain/Transactions/AggregatedMeasureData/AcceptedEnergyResultTimeSeries.cs
- source/Process.Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/AssertNotifyAggregatedMeasureDataXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/IAssertNotifyAggregatedMeasureDataDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesEbixDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/IAssertNotifyWholesaleServicesDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/NotifyWholesaleServicesDocumentWriterTests.cs
> feat: Add settlement version for aggregated request

- .github/workflows/ci-dotnet.yml
- global.json
As written in MS Teams developers channel we should bump dotnet workflows to v14
Also align global.json spanning Wholesale + EDI
> build: Bump dotnet workflows to v14

- .github/CODEOWNERS
> chore: Removing Dan as code owner, since he is part of mosaic

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202406261000 Bundle PeekedAt.sql
- source/OutgoingMessages.Domain/Models/ActorMessagesQueues/ActorMessageQueue.cs
- source/OutgoingMessages.Domain/Models/Bundles/Bundle.cs
- source/OutgoingMessages.Infrastructure/Repositories/ActorMessageQueues/ActorMessageQueueEntityConfiguration.cs
To be more explicit of when a `Bundle` actually have been peeked by an actor - this PR will add a `PeekedAt` property to `Bundle` which will be updated with a `Instant` of when the Actor peeked the `Bundle`
> refac: Bundle PeekedAt

- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueEnergyResultsForBalanceResponsiblesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueEnergyResultsForBalanceResponsiblesAndEnergySuppliersActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueEnergyResultsForGridAreaOwnersActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueWholesaleResultsForAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueWholesaleResultsForMonthlyAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueWholesaleResultsForTotalAmountsActivity.cs
> chore: Add progress counters to enqueue messages logs

- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueEnergyResultsForBalanceResponsiblesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueEnergyResultsForBalanceResponsiblesAndEnergySuppliersActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueEnergyResultsForGridAreaOwnersActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueWholesaleResultsForAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueWholesaleResultsForMonthlyAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueWholesaleResultsForTotalAmountsActivity.cs
> fix: Fix activity log statements

- source/B2BApi.AppTests/Functions/EnqueueMessages/EnqueueMessagesOrchestrationTests.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueWholesaleResultsForMonthlyAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/EnqueueWholesaleResultsForTotalAmountsActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/GetActorsForWholesaleResultsForMonthlyAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/GetActorsForWholesaleResultsForTotalAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/EnqueueMessagesOrchestration.cs
- source/IntegrationTests/Behaviours/IntegrationEvents/GivenCalculationCompletedV1ReceivedForWholesaleFixingTests.cs
- source/OutgoingMessages.Infrastructure/Databricks/WholesaleResults/Queries/WholesaleMonthlyAmountPerChargeQuery.cs
- source/OutgoingMessages.Infrastructure/Databricks/WholesaleResults/Queries/WholesaleTotalAmountQuery.cs
> refac: Enqueue total/monthly amount pr. charge pr. actor

- source/B2BApi.AppTests/Functions/EnqueueMessages/EnqueueMessagesOrchestrationTests.cs
> test: re-enable orchestration tests

- source/OutgoingMessages.Infrastructure/Databricks/Factories/PeriodFactory.cs
- source/Tests/Infrastructure/OutgoingMessages/Databricks/Factories/PeriodFactoryTests.cs
> fix: monthly period for wholesale results

- source/IncomingMessages.Application/UseCases/ReceiveIncomingMarketMessage.cs
> fix: Fix logging incoming message validation errors

- source/B2BApi.AppTests/Functions/EnqueueMessages/EnqueueMessagesOrchestrationTests.cs
- source/B2CWebApi/Factories/RequestWholesaleSettlementDtoFactory.cs
- source/B2CWebApi/Models/PriceType.cs
- source/B2CWebApi/Models/RequestWholesaleServicesMarketDocument.cs
- source/Tests/B2CWebApi/RequestWholesaleSettlement/RequestWholesaleSettlementFactoryTests.cs
- source/Tests/CimMessageAdapter/Messages/WholesaleSettlementMessageParsers/MessageParserTests.cs
- Add new `PriceType` to Wholesale B2C request
- Keep `resolution` while UI hasn't been updatet yet, but mark as obsolete
- Increase timeout in orchestrator tests to fix false negative test
- Issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/235
- BFF PR: https://github.com/Energinet-DataHub/greenforce-frontend/pull/3356
> feat: Add new PriceType to Wholesale B2C request

- source/AcceptanceTests/AcceptanceTests.csproj
- source/AcceptanceTests/Factories/RequestAggregatedMeasureXmlBuilder.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/B2BApi.AppTests/B2BApi.AppTests.csproj
- source/B2BApi/B2BApi.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/SystemTests/SystemTests.csproj
- source/Tests/Tests.csproj
> chore: updated nuget packages

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202407311435 Create index for ReceivedIntegrationEvents OccurredOn.sql
- source/IntegrationEvents.Application/IntegrationEventHandler.cs
- source/IntegrationEvents.Infrastructure/ReceivedIntegrationEventRepository.cs
> feat: new index used when finding ReceivedIntegrationEvents to be removed in retention job

- source/BuildingBlocks.Infrastructure/FileStorage/DataLakeFileStorageClient.cs
- source/IntegrationTests/Infrastructure/Retention/RemoveOldDequeuedBundlesWhenADayHasPassedTests.cs
We now observe the max batch size when we delete blobs.
> fix: blob batch supports a maximum of 256 blobs.

- source/B2BApi.AppTests/Functions/EnqueueMessages/EnqueueMessagesOrchestrationTests.cs
- source/B2BApi/IncomingMessages/IncomingMessageReceiver.cs
- source/B2BApi/OutgoingMessages/PeekRequestListener.cs
- source/BuildingBlocks.Application/FeatureFlag/FeatureFlagName.cs
- source/BuildingBlocks.Application/FeatureFlag/IFeatureFlagManager.cs
- source/BuildingBlocks.Application/FeatureFlag/MicrosoftFeatureFlagManager.cs
- source/IncomingMessages.Application/UseCases/ReceiveIncomingMarketMessage.cs
- source/IntegrationEvents.Infrastructure/EventProcessors/CalculationCompletedV1Processor.cs
- source/OutgoingMessages.Application/UseCases/EnqueueMessage.cs
This PR will remove the current featureflags. All features are already enabled on every environment as of now - which makes the flags obsolete. 
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/217
> refactor: Removed featureflags

- source/Contracts/Requests/WholesaleServices/WholesaleServicesRequestAccepted.proto
- source/IntegrationTests/EventBuilders/WholesaleServicesResponseEventBuilder.cs
- source/Process.Application/Transactions/WholesaleServices/WholesaleServicesRequestAcceptedMapper.cs
Ensure wholesale accepted contract is up to date.
> fix: align wholesale accepted contract

- source/BuildingBlocks.Infrastructure/FileStorage/DataLakeFileStorageClient.cs
Containers are now a part of the tf state. 
https://github.com/Energinet-DataHub/dh3-infrastructure/blob/main/edi/terraform/main/st-documents.tf
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/217
> refac: remove unused code to create containers

- .github/workflows/cd.yml
- .github/workflows/ci-orchestrator.yml
- .github/workflows/detect-changes.yml
> Support conditional deployments

- .github/workflows/cd.yml
> CD: add the missing closing curly brackets }} 

- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
> test: ensure we use correct actor role when testing duplicated incoming requests

- source/IntegrationTests/Behaviours/IntegrationEvents/GivenCalculationCompletedV1ReceivedForWholesaleFixingTests.cs
Added tests for business cases
> test: added tests for gaps in fees

- source/IntegrationTests/Behaviours/IntegrationEvents/GivenCalculationCompletedV1ReceivedForBalanceFixingTests.cs
- source/IntegrationTests/Behaviours/IntegrationEvents/GivenCalculationCompletedV1ReceivedForWholesaleFixingTests.cs
Added tests for gaps in energy results to ensure we have covered the business requirements.
> test: added tests for gaps in energy results

- source/AcceptanceTests/AcceptanceTests.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/B2BApi.AppTests/B2BApi.AppTests.csproj
- source/B2BApi.AppTests/Monitor/HealthCheckEndpointTests.cs
- source/B2BApi/B2BApi.csproj
- source/B2CWebApi/B2CWebApi.csproj
- source/B2CWebApi/Program.cs
- source/BuildingBlocks.Application/BuildingBlocks.Application.csproj
- source/DataAccess/DataAccess.csproj
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/SystemTests/SystemTests.csproj
- source/Tests/Tests.csproj
> chore: Bump NuGet packages

- source/AuditLog/AuditLogClient/AuditLogHttpClient.cs
Fix `AuditLogHttpClient` http request to use `StringContent` instead of `JsonContent`, since that is what works with the audit log http API
> fix: Fix audit log http request content

- source/AuditLog/AuditLogClient/AuditLogClientDependencyInjectionExtensions.cs
- source/AuditLog/AuditLogClient/AuditLogHttpClient.cs
- source/AuditLog/AuditLogClient/AuditLogOptions.cs
- source/AuditLog/AuditLogClient/AuditLogRequestBody.cs
- source/AuditLog/AuditLogClient/IAuditLogClient.cs
- source/AuditLog/AuditUser/AuditUser.cs
> docs: Enhance audit log documentation

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202409021105 Create index on MarketDocuments BundleId.sql
Recommended index after the performance test.
> feat: add index on market documents bundleId

- source/B2CWebApi/Controllers/OrchestrationsController.cs
> fix: Update orchestration admin guard

- .github/workflows/ci-dotnet.yml
- source/AcceptanceTests/AcceptanceTests.csproj
- source/B2BApi.AppTests/B2BApi.AppTests.csproj
- source/B2CWebApi.AppTests/B2CWebApi.AppTests.csproj
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/EdiDatabaseManager.cs
- source/IntegrationTests/Fixtures/IntegrationTestFixture.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/IntegrationTests/TestBase.cs
- source/SystemTests/SystemTests.csproj
Before improvements: **14m19s** (slowest test: 9m8s, integration test count: 946 test)
https://github.com/Energinet-DataHub/opengeh-edi/actions/runs/10679100654
After improvements round 1: **12m29s** (slowest test: 7m36s)
https://github.com/Energinet-DataHub/opengeh-edi/actions/runs/10680488474
After improvements round 2: **11m2s** (slowest test: 6m14s)
https://github.com/Energinet-DataHub/opengeh-edi/actions/runs/10680724586
After improvements round 3: **8m48s** (slowest test: 4m11s, integration test count: 437+11+11+3+484 = 946 tests)
https://github.com/Energinet-DataHub/opengeh-edi/actions/runs/10681610270
> test: Speed up integration test in CI

- source/OutgoingMessages.Application/UseCases/DequeueMessage.cs
- source/OutgoingMessages.Domain/DocumentWriters/DocumentFactory.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/CIM/CimCode.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/CIM/Json/CimJsonHeaderWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/CIM/Json/CimJsonWriterHelper.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/CIM/Xml/CimXmlDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/CIM/Xml/CimXmlHeaderWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/Ebix/EbixCode.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/Ebix/EbixDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/IDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/MarketDocumentWriterMemoryStream.cs
- source/OutgoingMessages.Domain/DocumentWriters/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataCimJsonDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataEbixDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/NotifyAggregatedMeasureData/TimeSeriesMarketActivityRecord.cs
- source/OutgoingMessages.Domain/DocumentWriters/NotifyWholesaleServices/NotifyWholesaleServicesCimJsonDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/NotifyWholesaleServices/NotifyWholesaleServicesCimXmlDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/NotifyWholesaleServices/NotifyWholesaleServicesEbixDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataCimJsonDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataCimXmlDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataEbixDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/RejectRequestAggregatedMeasureData/RejectedTimeSerieMarketActivityRecord.cs
- source/OutgoingMessages.Domain/DocumentWriters/RejectRequestWholesaleSettlement/RejectRequestWholesaleSettlementCimJsonDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/RejectRequestWholesaleSettlement/RejectRequestWholesaleSettlementCimXmlDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/RejectRequestWholesaleSettlement/RejectRequestWholesaleSettlementEbixDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/RejectRequestWholesaleSettlement/RejectedWholesaleServicesRecord.cs
- source/OutgoingMessages.Domain/Models/ActorMessagesQueues/ActorMessageQueue.cs
- source/OutgoingMessages.Domain/Models/ActorMessagesQueues/ReceiverMismatchException.cs
- source/OutgoingMessages.Domain/Models/OutgoingMessages/IOutgoingMessageRepository.cs
- source/OutgoingMessages.Domain/Models/OutgoingMessages/OutgoingMessageException.cs
- source/Process.Application/ProcessInitializationHandlers/InitializeAggregatedMeasureDataHandler.cs
> chore: Removed unused usings and a bundle delete method

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202409111315 Rebuild OutgoingMessages indexes.sql
> perf: rebuild OutgoingMessages indexes

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202409111300 Rebuild Bundle indexs.sql
> perf: rebuild bundle indexs

- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestTests.cs
- source/Process.Infrastructure/Processing/UnitOfWorkBehaviour.cs
Add test to show that a too long charge code id will result in a DbUpdateException as expected.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/300
> test: Add test to cover dead-letter case for charge code id

- source/OutgoingMessages.Application/UseCases/EnqueueMessage.cs
See title.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/229
> refac: Add Role when logging when Enqueueing messages

- source/B2CWebApi/Program.cs
Removed because of https://teams.microsoft.com/l/message/19:91c8a12a0ed34734b72b5678596377f5@thread.tacv2/1725616956931?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=e1b7877a-ee7d-4505-a4b2-4989abc2d22a&parentMessageId=1725616956931&teamName=DataHub%203.0&channelName=Developers&createdTime=1725616956931
https://github.com/Energinet-DataHub/Internal-Repo/issues/1319
> chore: Removed JsonStringEnumConverter

- source/B2CWebApi/Controllers/ArchivedMessageSearchController.cs
> fix: added missing document type for fields to sort by

- source/B2BApi/Configuration/SystemTimer.cs
- An error on Azure with timeout on retention jobs
> feat: Invoke a-day-has-passed at noon

- source/B2BApi.AppTests/Fixtures/B2BApiAppFixture.cs
- source/BuildingBlocks.Application/FeatureFlag/FeatureFlagName.cs
- source/BuildingBlocks.Application/FeatureFlag/IFeatureFlagManager.cs
- source/BuildingBlocks.Application/FeatureFlag/MicrosoftFeatureFlagManager.cs
- source/BuildingBlocks.Tests/TestDoubles/FeatureFlagManagerStub.cs
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/351
> feat: Add ReceiveMeteredDataForMeasurementPoints feature flag

- source/Tests/Domain/Transactions/Mappers/CalculatedQuantityQualityMapperTests.cs
> test: Add test to ensure all values are present in test input

- source/SubsystemTests/SubsystemTestFixture.cs
> test: use iam to get service bus client in subsystem tests

- source/IncomingMessages.Infrastructure/Response/EbixResponseFactory.cs
- source/Tests/CimMessageAdapter/Response/EbixResponseFactoryTests.cs
> refac: updated ebix response factory

- source/ArchivedMessages.IntegrationTests/ArchivedMessages.IntegrationTests.csproj
- source/B2BApi.AppTests/B2BApi.AppTests.csproj
- source/B2CWebApi.AppTests/B2CWebApi.AppTests.csproj
- source/BuildingBlocks.Tests/BuildingBlocks.Tests.csproj
- source/Edi.UnitTests/Edi.UnitTests.csproj
- source/IncomingMessages.IntegrationTests/IncomingMessages.IntegrationTests.csproj
- source/IntegrationEvents.IntegrationTests/IntegrationEvents.IntegrationTests.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/MasterData.IntegrationTests/MasterData.IntegrationTests.csproj
- source/ProcessManager.Core.Tests/ProcessManager.Core.Tests.csproj
- source/ProcessManager.Orchestrations.Tests/ProcessManager.Orchestrations.Tests.csproj
- source/ProcessManager.SubsystemTests/ProcessManager.SubsystemTests.csproj
- source/ProcessManager.Tests/ProcessManager.Tests.csproj
- source/SubsystemTests/SubsystemTests.csproj
- source/SystemTests/SystemTests.csproj
> chore: Bump TestCommon

- source/IncomingMessages.Domain/Validation/ValidationErrors/AuthenticatedUserDoesNotHoldRequiredRoleType.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/AuthenticatedUserDoesNotMatchSenderId.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/DuplicateMessageIdDetected.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/DuplicateTransactionIdDetected.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/EmptyMessageId.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/EmptyTransactionId.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/InvalidBusinessReasonOrVersion.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/InvalidMessageIdSize.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/InvalidMessageStructure.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/InvalidReceiverId.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/InvalidReceiverRole.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/InvalidSchemaOrNamespace.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/InvalidTransactionIdSize.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/NotSupportedBusinessType.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/NotSupportedMessageType.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/NotSupportedProcessType.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/SenderRoleTypeIsNotAuthorized.cs
- source/IncomingMessages.Domain/Validation/ValidationErrors/ValidationError.cs
- source/IncomingMessages.Infrastructure/Response/EbixResponseFactory.cs
- source/IncomingMessages.IntegrationTests/IncomingMessages/GivenIncomingMessagesTests.cs
- source/IncomingMessages.IntegrationTests/IncomingMessages/GivenIncomingMessagesWithDelegationTests.cs
- source/SubsystemTests/Tests/WhenMeteredDataForMeasurementPointIsReceivedTests.cs
- source/Tests/CimMessageAdapter/Response/EbixResponseFactoryTests.cs
> feat: new sync validation errors for ebix

- .github/dependabot.yml
> chore: depandabot runs every week

- .github/actions/dotnet-prepare-outputs/action.yml
> chore: move process manager migration dll to subfolder 

- source/ArchitectureTests/RegistrationTests.cs
- source/IncomingMessages.Application/Extensions/DependencyInjection/IncomingMessagesExtensions.cs
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IncomingMessages.Infrastructure/MessageParsers/AggregatedMeasureDataRequestMessageParsers/AggregatedMeasureDataJsonMessageParser.cs
- source/IncomingMessages.Infrastructure/MessageParsers/AggregatedMeasureDataRequestMessageParsers/OldAggregatedMeasureDataJsonMessageParser.cs
- source/IncomingMessages.Infrastructure/MessageParsers/JsonMessageParserBase.cs
- source/IncomingMessages.Infrastructure/MessageParsers/WholesaleSettlementMessageParsers/OldWholesaleSettlementJsonMessageParser.cs
- source/IncomingMessages.Infrastructure/MessageParsers/WholesaleSettlementMessageParsers/WholesaleSettlementJsonMessageParser.cs
- source/Tests/CimMessageAdapter/Messages/RequestAggregatedMeasureData/MessageParserTests.cs
- source/Tests/CimMessageAdapter/Messages/WholesaleSettlementMessageParsers/MessageParserTests.cs
- source/Tests/CimMessageAdapter/Messages/xml/AggregatedMeasure/InvalidRequestAggregatedMeasureData.xml
- source/Tests/Tests.csproj
> feat: move json parser to new pattern

- source/Process.Application/ProcessInitializationHandlers/InitializeMeteredDataForMeasurementPointHandler.cs
> fix: Allow nullable quantities for RSM-12

- source/B2BApi/OutgoingMessages/PeekRequestListener.cs
- source/BuildingBlocks.Infrastructure/FeatureFlag/FeatureFlagName.cs
- source/BuildingBlocks.Infrastructure/FeatureFlag/IFeatureFlagManager.cs
- source/BuildingBlocks.Infrastructure/FeatureFlag/MicrosoftFeatureFlagManager.cs
- source/BuildingBlocks.Tests/TestDoubles/FeatureFlagManagerStub.cs
=> https://github.com/Energinet-DataHub/dh3-environments/actions/runs/12181332079
> feat: feature flag for peek time series messages

- source/IncomingMessages.Application/UseCases/ValidateIncomingMessage.cs
> feat: added execution time logging when validating incoming messages

- .github/workflows/ci-orchestrator.yml
> chore: Update .github references to v14

- source/Edi.UnitTests/Validators/AggregatedTimeSeriesRequest/PeriodValidatorTests.cs
- source/SubsystemTests/LoadTest/ForwardMeteredData.cs
> test: remove calculation id from metered data load test

- source/B2BApi/B2BApi.csproj
- source/B2CWebApi.AppTests/B2CWebApi.AppTests.csproj
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IncomingMessages.Infrastructure/ProcessManager/MeteredDataOrchestrationStarter.cs
- source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
> chore: Update Process Manager package

- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_026/EnqueueBrs026MessagesTests.cs
- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_028/EnqueueBrs028MessagesTests.cs
- source/B2BApi.AppTests/IncomingMessages/Requests/RequestAggregatedMeasureDataTests.cs
- source/B2BApi.AppTests/IncomingMessages/Requests/RequestWholesaleServicesTests.cs
- source/B2BApi/B2BApi.csproj
- source/B2BApi/Functions/EnqueueMessages/BRS_023_027/EnqueueHandler_Brs_023_027_V1.cs
- source/B2BApi/Functions/EnqueueMessages/BRS_026/EnqueueHandler_Brs_026_V1.cs
- source/B2BApi/Functions/EnqueueMessages/BRS_028/EnqueueHandler_Brs_028_V1.cs
- source/B2BApi/Functions/EnqueueMessages/EnqueueActorMessagesHandlerBase.cs
- source/B2BApi/Functions/EnqueueMessages/EnqueueActorMessagesValidatedHandlerBase.cs
- source/B2CWebApi.AppTests/B2CWebApi.AppTests.csproj
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IncomingMessages.Infrastructure/ProcessManager/RequestProcessOrchestrationStarter.cs
- source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
- Update EDI to use new Process Manager package
- Use new methods to set/get data
- Update idempotency key
> feat: Use new Process Manager package with notify events

- source/IncomingMessages.Infrastructure/IncomingMessagePublisher.cs
- source/SubsystemTests/Tests/WhenMeteredDataForMeteringPointIsReceivedTests.cs
> feat: send incoming metered data to process manager

- source/IncomingMessages.Infrastructure/IncomingMessagePublisher.cs
- source/IncomingMessages.Infrastructure/ProcessManager/MeteredDataOrchestrationStarter.cs
- source/IncomingMessages.IntegrationTests/IncomingMessages/GivenIncomingMessagesTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenMeteredDataForMeteringPointTests.cs
- source/SubsystemTests/Drivers/EdiDatabaseDriver.cs
- source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
> test: disable enqueuing metered data directly

- source/ArchitectureTests/ArchitectureTests.csproj
- source/B2BApi.AppTests/B2BApi.AppTests.csproj
- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_026/EnqueueBrs026MessagesTests.cs
- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_028/EnqueueBrs028MessagesTests.cs
- source/B2BApi/B2BApi.csproj
- source/B2CWebApi.AppTests/B2CWebApi.AppTests.csproj
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IncomingMessages.Infrastructure/ProcessManager/RequestProcessOrchestrationStarter.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
- source/Tests/Tests.csproj
> feat: Use new BRS-028 input & enqueue types from Process Manager

- source/B2BApi/Configuration/Middleware/UnHandledExceptionMiddleware.cs
- source/B2BApi/OutgoingMessages/PeekRequestListener.cs
> fix: object disposed when peek is called

- source/B2BApi/OutgoingMessages/PeekRequestListener.cs
> fix: object disposed ex in peek request handler

- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestV2Tests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestV2WithDelegationTests.cs
Copied all tests from GivenWholesaleServicesRequestWithDelegationTests into GivenWholesaleServicesRequestV2WithDelegationTests and refactored to use Process Manager instead of the old Process Module and wholesale.
> test: wholesale delegation via pm behaviour tests

- .github/workflows/ci-dotnet.yml
Splitting long-running ci tests to improve overall CI execution time.
Before:
~30min
Now: 
~ 20min
> chore: improve ci by splitting incomingRequests behaviour tests

- source/IntegrationTests/Behaviours/AggregatedMeasureDataBehaviourTestBase.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataV2RequestTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestV2Tests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestV2WithDelegationTests.cs
- source/IntegrationTests/Behaviours/IntegrationEvents/GivenCalculationCompletedV1ReceivedForBalanceFixingTests.cs
- source/IntegrationTests/Behaviours/IntegrationEvents/TestData/EnergyResultPerBrpGridAreaDescription.cs
- source/IntegrationTests/Behaviours/IntegrationEvents/TestData/EnergyResultPerEnergySupplierBrpGridAreaDescription.cs
- source/IntegrationTests/Behaviours/IntegrationEvents/TestData/EnergyResultPerGridAreaDescription.cs
- source/IntegrationTests/Behaviours/RequestCalculatedEnergyTimeSeriesInputV1AssertionInput.cs
- source/IntegrationTests/Behaviours/WholesaleServicesBehaviourTestBase.cs
- source/IntegrationTests/EventBuilders/AggregatedTimeSeriesResponseEventBuilder.cs
This Pr contains a rewrite of the first request aggregated measure data in GivenAggregatedMeasureDataV2RequestTests to Process Manager.
> test: updated first reqeust aggregated measure data behaviour test via PM

- source/BuildingBlocks.Domain/Models/Quality.cs
- source/IncomingMessages.Infrastructure/ProcessManager/MeteredDataOrchestrationStarter.cs
> fix: Add quantityQuality mapper for ebix

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/AuditLog/AuditLog.csproj
- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_021/EnqueueBrs21ForwardMeteredDataMessagesTests.cs
- source/B2BApi/B2BApi.csproj
- source/B2BApi/Functions/EnqueueMessages/BRS_021/EnqueueHandler_Brs_021_ForwardMeteredData_V1.cs
- source/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj
- source/BuildingBlocks.Tests/BuildingBlocks.Tests.csproj
- source/DataAccess/DataAccess.csproj
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IncomingMessages.Infrastructure/ProcessManager/ForwardMeteredDataOrchestrationStarter.cs
- source/IntegrationTests/Behaviours/ForwardMeteredDataInputV1AssertionInput.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenMeteredDataForMeteringPointV2Tests.cs
- source/IntegrationTests/Behaviours/MeteredDataForMeteringPointBehaviourTestBase.cs
- source/IntegrationTests/EventBuilders/MeteredDataForMeteringPointEventBuilder.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/OutgoingMessages.Application/OutgoingMessages.Application.csproj
- source/OutgoingMessages.Application/OutgoingMessagesClient.cs
- source/OutgoingMessages.Infrastructure/OutgoingMessages.Infrastructure.csproj
- source/OutgoingMessages.IntegrationTests/OutgoingMessages/WhenEnqueueingMultipleOutgoingMessagesIdempotencyTests.cs
- source/OutgoingMessages.IntegrationTests/OutgoingMessagesTestBase.cs
- source/OutgoingMessages.Interfaces/IOutgoingMessagesClient.cs
- source/SubsystemTests/SubsystemTests.csproj
- source/SystemTests/SystemTests.csproj
- source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
- source/Tests/Tests.csproj
- Update Process Manager (and required dependencies) NuGet packages.
- Update enqueue `NotifyValidatedMeasureData` with the new Process Manager models
- Update test to contain multiple receivers
- Link to assignment: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/598
- https://github.com/Energinet-DataHub/team-mosaic/issues/598
- PM PR: https://github.com/Energinet-DataHub/opengeh-process-manager/pull/268
> feat: Enqueue accepted RSM-012 using new Process Manager models

- source/IncomingMessages.Domain/IncomingMessages.Domain.csproj
- source/IncomingMessages.Domain/MessageParsers/EbixMessageParserBase.cs
- source/IncomingMessages.Domain/MessageParsers/RSM012/MeteredDateForMeteringPointEbixMessageParser.cs
- source/Tests/CimMessageAdapter/Messages/MeteredDataForMeteringPointMessageParserTests/MessageParserTests.cs
> invest: added logging in EbixMessageParserBase to find cause of ex

- source/ArchitectureTests/RegistrationTests.cs
- source/OutgoingMessages.Domain/DocumentWriters/RSM009/AcknowledgementXmlDocumentWriter.cs
> Fix: correct schema location for acknowledgement

- source/IncomingMessages.Domain/MessageParsers/EbixMessageParserBase.cs
> invest: more logging in EbixMessageParserBase to find cause of ex

- source/B2BApi/Functions/EnqueueMessages/BRS_021/EnqueueHandler_Brs_021_ForwardMeteredData_V1.cs
> Chore: Add null check for original transactionId

- source/OutgoingMessages.Domain/DocumentWriters/DocumentFactory.cs
- source/OutgoingMessages.Domain/DocumentWriters/IDocumentWriter.cs
- source/OutgoingMessages.Domain/DocumentWriters/RSM009/AcknowledgementJsonDocumentWriter.cs
Ensure the json writer for rsm009 can handle multiple series, aka bundling.
> fix: Rsm009 jsonwriter to allow handling mulitiple series

- source/SubsystemTests/Tests/WhenForwardMeteredDataIsReceivedTests.cs
> chore: Ordering on forward metered data subsystemtest

- source/SubsystemTests/Drivers/B2C/B2CEdiDriver.cs
> fix: Upddated business reason for wholesale request

- source/SubsystemTests/Drivers/B2C/B2CEdiDriver.cs
- source/SubsystemTests/Drivers/B2C/Client/B2CEdiClient.cs
- source/SubsystemTests/Drivers/B2C/Client/swagger.json
- source/SubsystemTests/Drivers/B2C/Client/swaggerV3.json
- source/SubsystemTests/Dsl/ArchivedMessageDsl.cs
- source/SubsystemTests/Tests/ArchivedMessages/WhenArchivedMessageIsRequestedTests.cs
> Test: Subsystem test for archived metering point messages

- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_021/EnqueueBrs21CalculationMessagesTests.cs
- source/B2BApi.AppTests/SubsystemHttpTrigger/EnqueueHttpEndpointTests.cs
- source/B2BApi/Functions/EnqueueMessages/BRS_021/EnqueueTrigger_Brs_021_CalculatedMeasurements.cs
- source/SubsystemTests/Drivers/EdiDriver.cs
- source/SubsystemTests/Drivers/SubsystemDriver.cs
- source/SubsystemTests/Dsl/EnqueueActorMessagesHttpDsl.cs
- source/SubsystemTests/SubsystemTestFixture.cs
- source/SubsystemTests/SubsystemTests.csproj
- source/SubsystemTests/Tests/ArchivedMessages/WhenArchivedMessageIsRequestedTests.cs
- source/SubsystemTests/Tests/WhenEnqueueActorMessagesViaHttpTests.cs
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/741
> test: Add subsystem test for enqueue http endpoint

- source/OutgoingMessages.UnitTests/Domain/RSM018/AssertMissingMeasurementEbixDocument.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/AssertMissingMeasurementJsonDocument.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/IAssertMissingMeasurementDocument.cs
Updates the IAssertMissingMeasurementDocument interface, such that the inteface does not expect the methods to be async
> Chore: Update IAssertMissingMeasurementDocument

- source/OutgoingMessages.Domain/DocumentWriters/RSM018/MissingMeasurementJsonDocumentWriter.cs
- source/OutgoingMessages.UnitTests/Domain/RSM009/AssertAcknowledgementJsonDocument.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/AssertMissingMeasurementJsonDocument.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/MissingMeasurementTests.cs
Add the JSON document writer for RSM-018.
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/742
~- [ ] Subsystem test executed [deploy to dev_002/dev_003](https://github.com/Energinet-DataHub/dh3-environments/actions/workflows/edi-cd.yml)~
> feat: RSM-018 JSON document writer

- source/BuildingBlocks.Domain/Models/BusinessReason.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/Ebix/EbixCode.cs
- source/OutgoingMessages.Domain/DocumentWriters/RSM018/MissingMeasurementEbixDocumentWriter.cs
- source/OutgoingMessages.Infrastructure/Extensions/DependencyInjection/OutgoingMessagesExtensions.cs
- source/OutgoingMessages.IntegrationTests/OutgoingMessages/DocumentFactory/DocumentFactoryTests.cs
- source/OutgoingMessages.UnitTests/Domain/OutgoingMessageTests.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/AssertMissingMeasurementDocumentProvider.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/AssertMissingMeasurementEbixDocument.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/AssertMissingMeasurementJsonDocument.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/IAssertMissingMeasurementDocument.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/MissingMeasurementTests.cs
- source/OutgoingMessages.UnitTests/Domain/Schemas/Ebix/EbixSchemaProvider.cs
- source/Tests/BuildingBlocks/Models/BusinessReasonTests.cs
This pull request implements the missing measurement log ebix writer and the corresponding test
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/744
> Feat: Ebix missing measurement log writer

- source/BuildingBlocks.Domain/Models/BusinessReason.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/AssertMissingMeasurementJsonDocument.cs
- source/OutgoingMessages.UnitTests/Domain/RSM018/MissingMeasurementTests.cs
- source/Tests/BuildingBlocks/Models/BusinessReasonTests.cs
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/742
> test: Implement missing RSM-018 JSON document writer assertions

- source/ArchitectureTests/RegistrationTests.cs
- source/B2BApi/RuntimeEnvironment.cs
> chore: remove unused settings

- source/IncomingMessages.Application/UseCases/ValidateIncomingMessage.cs
- source/IncomingMessages.Domain/Validation/SenderAuthorizer.cs
This pull request refactors the `ValidateIncomingMessage` class and related components to improve code consistency by standardizing the use of private readonly fields for dependencies and updating logger calls. It also introduces minor updates to the `SenderAuthorizer` class to align with these changes.
* **Dependency Injection Standardization**: Added private readonly fields for all injected dependencies (`ILogger`, `ISenderAuthorizer`, `IReceiverValidator`, etc.) to ensure consistent usage throughout the class.
* **Logger Updates**: Updated logger calls to use the private `_logger` field instead of the previously used `logger` variable. This change applies across multiple methods, including `ValidateAsync`, `AuthorizeSenderAsync`, and others. …
> refac: Use fields for primary constructor arguments

- source/BuildingBlocks.Tests/TestDoubles/FeatureManagerStub.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenRequestMeasurementsTests.cs
- source/IntegrationTests/Behaviours/RequestMeasurementsBehaviourTestBase.cs
- source/IntegrationTests/EventBuilders/RequestMeasurementsResponseBuilder.cs
- source/OutgoingMessages.UnitTests/Domain/RSM012/AssertMeteredDataForMeteringPointDocumentProvider.cs
Add the second part to the behavior test of brs024 accept flow. 
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/792
> test: complete brs024 accepted behavior test

- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_024/EnqueueBrs024MessagesTests.cs
- source/B2BApi/Functions/EnqueueMessages/BRS_024/EnqueueHandler_Brs_024_V1.cs
- source/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IntegrationTests/Behaviours/IncomingRequests/GivenRequestMeasurementsTests.cs
- source/IntegrationTests/EventBuilders/RequestMeasurementsResponseBuilder.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/OutgoingMessages.Infrastructure/OutgoingMessages.Infrastructure.csproj
- source/SubsystemTests/Drivers/MessageFactories/EnqueueBrs024AcceptedMeasurementsFactory.cs
- source/SubsystemTests/SubsystemTests.csproj
> feat: update edi to use new brs024 accept event

- source/IncomingMessages.Application/UseCases/ReceiveIncomingMarketMessage.cs
- source/IncomingMessages.Domain/IncomingMessages.Domain.csproj
- source/IncomingMessages.Domain/MessageParsers/RSM015/RequestMeasurementsEbixMessageParser.cs
- source/IncomingMessages.Domain/Schemas/Ebix/Schemas/document/DK_RequestMeteredDataValidated/ebIX_AggregatedBusinessInformationEntities-2.xsd
- source/IncomingMessages.Domain/Schemas/Ebix/Schemas/document/DK_RequestMeteredDataValidated/ebIX_BusinessDataType-2.xsd
- source/IncomingMessages.Domain/Schemas/Ebix/Schemas/document/DK_RequestMeteredDataValidated/ebIX_DK_RequestMeteredDataValidated-2.xsd
- source/IncomingMessages.Infrastructure/Extensions/DependencyInjection/IncomingMessagesExtensions.cs
- source/IncomingMessages.IntegrationTests/Builders/RequestMeasurementsBuilder.cs
- source/IncomingMessages.IntegrationTests/IncomingMessages.IntegrationTests.csproj
- source/IncomingMessages.IntegrationTests/MessageParsers/Ebix/RequestValidatedMeasurements/BadVersionRequestValidatedMeasurements.xml
- source/IncomingMessages.IntegrationTests/MessageParsers/Ebix/RequestValidatedMeasurements/InvalidRequestValidatedMeasurements.xml
- source/IncomingMessages.IntegrationTests/MessageParsers/Ebix/RequestValidatedMeasurements/ValidRequestValidatedMeasurements.xml
- source/IncomingMessages.IntegrationTests/MessageParsers/Ebix/RequestValidatedMeasurements/ValidRequestValidatedMeasurementsWithTwoTransactions.xml
- source/IncomingMessages.IntegrationTests/MessageParsers/GivenNewDocumentTypeTests.cs
- source/IncomingMessages.IntegrationTests/MessageParsers/RequestMeasurementsMessageParser.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenRequestMeasurementsTests.cs
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/825
> feat: Request measurements in ebix

- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_024/EnqueueBrs024MessagesTests.cs
- source/B2BApi/Functions/EnqueueMessages/BRS_024/EnqueueHandler_Brs_024_V1.cs
- source/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj
- source/BuildingBlocks.Domain/Models/BusinessReason.cs
- source/IncomingMessages.Domain/Messages/RequestMeasurementsMessage.cs
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IncomingMessages.IntegrationTests/Builders/RequestMeasurementsBuilder.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenRequestMeasurementsTests.cs
- source/IntegrationTests/Behaviours/RequestMeasurementsBehaviourTestBase.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/Ebix/EbixCode.cs
- source/OutgoingMessages.Infrastructure/OutgoingMessages.Infrastructure.csproj
- source/SubsystemTests/SubsystemTests.csproj
- source/Tests/BuildingBlocks/Models/BusinessReasonTests.cs
> feat: Ensure we support business reason E30 in BRS024

- source/BuildingBlocks.Domain/Models/BusinessReason.cs
- source/OutgoingMessages.Domain/DocumentWriters/Formats/Ebix/EbixCode.cs
- source/Tests/BuildingBlocks/Models/BusinessReasonTests.cs
> feat: Change business reason for RSM-018 documents

- source/B2BApi/Functions/EnqueueMessages/BRS_024/EnqueueHandler_Brs_024_V1.cs
> invest: why subsystem is broken
