- source/Infrastructure/OutgoingMessages/Common/Xml/HeaderWriter.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggreagtedMeasureData/NotifyAggregatedMeasureDataDocumentWriterTests.cs
Bugfix: Read sender role from message header
> Bugfix: Read sender role from message header

- source/Api/Program.cs
- source/Api/RuntimeEnvironment.cs
Use environment variable ALLOW_TEST_TOKENS 
since previously used variable is now used to determine were the PerformanceTest is deployed
> Use environment variable ALLOW_TEST_TOKENS 

- source/Application/Transactions/Aggregations/IAggregationResults.cs
- source/Application/Transactions/Aggregations/TransactionScheduler.cs
- source/Domain/Transactions/Aggregations/AggregationResult.cs
- source/Infrastructure/Transactions/Aggregations/AggregationResultsOverHttp.cs
- source/Infrastructure/Transactions/HttpClientAdapter.cs
- source/Infrastructure/Transactions/IHttpClientAdapter.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenResultsAreRetrievedTests.cs
- source/IntegrationTests/Factories/AggregationResultBuilder.cs
- source/IntegrationTests/TestDoubles/AggregationResultsStub.cs
- source/IntegrationTests/TestDoubles/HttpClientSpy.cs
- source/LearningTests/Infrastructure/Transactions/Aggregations/AggregationResultOverHttpTests.cs
Total non-profiled consumption is sent to balance responsible
> Total non-profiled consumption is sent to balance responsible

- source/DocumentValidation/DocumentValidation.csproj
- source/Infrastructure/IncomingMessages/RequestChangeOfSupplier/JsonMessageParser.cs
- source/Tests/Infrastructure/OutgoingMessages/Asserts/AssertJsonMessage.cs
> Upgrade package version

- source/Infrastructure/Infrastructure.csproj
- source/Infrastructure/Transactions/Aggregations/CalculationResultCompletedEventMapper.cs
- source/IntegrationTests/Application/Transactions/Aggregations/WhenAnAggregationResultIsAvailableTests.cs
This PR will:
1) Update the Nuget package with the newest version of the `Calculation_result_completed` contract.
2) Add a test to ensure the grid area operator is informed when a result of this time-series-type is received.
* Som netvirksomhed vil jeg kunne modtage Total forbrug per netområde 27
> feat: support for total consumption

- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/SampleData.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenARejectedResultIsAvailableTests.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenAnAcceptedResultIsAvailableTests.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/WhenAnRejectedResultIsAvailableTests.cs
- source/IntegrationTests/Assertions/AssertOutgoingMessage.cs
- source/IntegrationTests/TestBase.cs
> chore: added tests to ensure outgoing message is created for aggreated measure data inbox events

- source/Application/OutgoingMessages/Dequeue/DequeueHandler.cs
- source/Domain/OutgoingMessages/Queueing/ActorMessageQueue.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenADequeueIsRequestedTests.cs
- source/Tests/Domain/OutgoingMessages/Queueing/ActorMessageQueueTests.cs
Dequeue should return unsuccessful if an actor doesn't have an open bundle. 
This can be reproduced if an Actor with an existing Actor Queue dequeue with an unknown messageId.
* #0000
> Test: unsuccessful dequeue for actor queue with no open bundles

- source/AcceptanceTests/AcceptanceTests.csproj
- source/AcceptanceTests/Drivers/EdiDriver.cs
- source/AcceptanceTests/Dsl/AggregatedMeasureDataRequestDsl.cs
- source/AcceptanceTests/WhenAggregatedMeasureDataIsRequestedTests.cs
- source/AcceptanceTests/WhenAggregationResultIsPublishedTests.cs
> refac: empty queues before running acceptancetests

- source/AcceptanceTests/AcceptanceTests.csproj
- source/AcceptanceTests/Drivers/EdiDriver.cs
- source/AcceptanceTests/Messages/json/RequestAggregatedMeasureData.json
- source/AcceptanceTests/Messages/json/RequestAggregatedMeasureDataWithBadPeriod.json
- source/AcceptanceTests/Messages/json/RequestAggregatedMeasureDataWithWrongMarketEvaluationPoint.json
After the removal of mocked data in wholesale we need to update our acceptance test requests.
We ensure a failed request by setting starting-time after end-time.
We ensure a good response by update the timeslots to timeslots where we know data exists.
By picking a relative new timeslot, we ensure, that we do not have to update this, in the short future.
* #0000
> chore: Updated acceptance test request to ensure expected response from wholesale

- source/Application/OutgoingMessages/DocumentFactory.cs
- source/Application/OutgoingMessages/IOutgoingMessageRepository.cs
- source/Application/OutgoingMessages/PeekHandler.cs
- source/Domain/OutgoingMessages/OutgoingMessageBundle.cs
- source/Infrastructure/OutgoingMessages/OutgoingMessageRepository.cs
When all messages are enqueued they are from the same process and document-type. Meaning they go into the same bundle and have all the same metadata.
So when we retrieve OutGoingMessages they are now packed in an OutgoingMessageBundle and the metadata from the bundle is set on the type.
> refac: Outgoingmessages are retrieved in a bundle

- source/Domain/OutgoingMessages/Queueing/ActorMessageQueue.cs
- source/Tests/Domain/OutgoingMessages/Queueing/ActorMessageQueueTests.cs
Currently bundles containing aggregations may contain 6 different messages. This is reduced to 1 to ensure we do not get "out of memory" exceptions
> fix: Reduced aggregation bundle size to 1

- source/Api/Program.cs
- source/Api/RuntimeEnvironment.cs
The queue was removed from infrastructure in this commit:
https://github.com/Energinet-DataHub/dh3-infrastructure/commit/3d2fec1b903e5643278952a2b6b9fb136f5e6971#diff-ab63f0dcf4543b52070c7736d1f98cd9b1031c92f46ddd79febfc365a957a1fd
The health check needs to be removed
> fix: remove healthcheck for domain relay queue

- source/Infrastructure/Configuration/IntegrationEvents/ReceivedIntegrationEventsRetention.cs
- source/Infrastructure/Configuration/InternalCommands/InternalCommandsRetention.cs
- source/Infrastructure/DataRetention/ExecuteDataRetentionsWhenADayHasPassed.cs
- source/Infrastructure/InboxEvents/ReceivedInboxEventsRetention.cs
- source/IntegrationTests/Infrastructure/Retention/RemoveInternalCommandsWhenADayHasPassedTests.cs
We are still getting some timeouts in our nigthly clean ups. 
This should address Sql connection time out after 30 sec because of smaller batch size for commands and a longer wait between retries if db is asleep.
> fix: sql timeouts in our retention job

- source/Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesCommandTests.cs
The mapping of the settlement method to time series type did not match the documentation.
> fix: Updated settlement method to match documentation 

- source/B2CWebApi/Startup.cs
In order for nswag to generate readable values for enums, we must ensure our swagger document is created with the named values. 
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-phoenix/75
> feat: added enum names to swagger docs

- source/B2CWebApi/Controllers/RequestAggregatedMeasureDataController.cs
This PR will ensure that only users with the correct permission will be allowed to create requests for aggregated measured data.
Its builds on a PR created in MarkPart here: https://github.com/Energinet-DataHub/geh-market-participant/pull/635
> feat: add permission to B2C RequestAggMeaData

- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesCommandTests.cs
`task02` in the integration test `Duplicated_message_id_across_commands_one_aggregated_measure_data_process_is_created` sometimes completes before `task01` locally, which causes the test to fail. The test now checks which task was successful, and uses that task for assertion.
> fix: Test of duplicated message id's

- source/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Infrastructure/IncomingMessages/MessageHeaderExtractor.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/XmlMessageParser.cs
The json parser and xml parser at see missing attributes differently. Currently json gives "null" when an attribute is missing where xml return empty string.
This pr changes the xml parser to return null instead of empty string.
> fix: Missing attributes are set to null when requesting in xml

- source/B2CWebApi/Configuration/DateTimeConfiguration.cs
- source/B2CWebApi/Configuration/JwtConfiguration.cs
- source/B2CWebApi/Configuration/Options/DateTimeOptions.cs
- source/B2CWebApi/Controllers/RequestAggregatedMeasureDataController.cs
- source/B2CWebApi/Factories/RequestAggregatedMeasureDataHttpFactory.cs
- source/B2CWebApi/Models/RequestAggregatedMeasureDataMarketDocument.cs
- source/B2CWebApi/Startup.cs
- source/Infrastructure/IncomingMessages/RequestAggregatedMeasureData/RequestAggregatedMeasureDataMarketMessageFactory.cs
- Ensure proto doesn't set empty string when it should be null 
- End and Start date should be at midnight local time. 
PR: 
https://github.com/Energinet-DataHub/dh3-infrastructure/pull/540
https://github.com/Energinet-DataHub/greenforce-frontend/pull/2162
> fix handling of optional fields and time is at midnight in b2c

- source/B2CWebApi/Factories/InstantFormatFactory.cs
- source/B2CWebApi/Factories/RequestAggregatedMeasureDataHttpFactory.cs
- source/Tests/B2CWebApi/RequestAggregatedMeasureData/InstantFormatFactoryTests.cs
- source/Tests/Tests.csproj
We should take instant format and not local datetime.
> fix: wrong date format for b2c requests

- source/B2CWebApi/Factories/InstantFormatFactory.cs
- source/B2CWebApi/Factories/RequestAggregatedMeasureDataHttpFactory.cs
- source/Tests/B2CWebApi/RequestAggregatedMeasureData/InstantFormatFactoryTests.cs
- source/Tests/B2CWebApi/RequestAggregatedMeasureData/RequestAggregatedMeasureDataFactoryTests.cs
Currently when we set our enddate to midnight. This midnight are sometimes the day before the requested day. 
This ensures that we get the midnight of the requested day
> fix: Ensure that we set to midnight the same day

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202311140927 Make EventPayload to varbinary for inboxEvents.sql
- source/Infrastructure/InboxEvents/IInboxEventMapper.cs
- source/Infrastructure/InboxEvents/InboxEventReceiver.cs
- source/Infrastructure/InboxEvents/InboxEventsConfiguration.cs
- source/Infrastructure/InboxEvents/InboxEventsProcessor.cs
- source/Infrastructure/InboxEvents/ReceivedInboxEventsRetention.cs
- source/Infrastructure/InboxEvents/ReceivedIntegrationEvent.cs
- source/IntegrationTests/Application/Transactions/AggregatedMeasureData/SampleData.cs
- source/IntegrationTests/Infrastructure/InboxEvents/TestInboxEventMapper.cs
- source/IntegrationTests/Infrastructure/InboxEvents/WhenAggregatedTimeSeriesRequestAcceptedEventIsReceivedTests.cs
- source/IntegrationTests/Infrastructure/InboxEvents/WhenAnInboxEventIsProcessingTests.cs
- source/Process.Application/Transactions/Aggregations/AggregatedTimeSeriesRequestAcceptedEventMapper.cs
- source/Process.Application/Transactions/Aggregations/AggregatedTimeSeriesRequestRejectedMapper.cs
It has happened that an inbox event had no data in "eventPayload". Which we cannot backtrace with the current implementation
This pull request removes the mapping from byte data to a json formatted string, keeping all the information received by the service bus
> feat: Removing json serializing from inbox events

- source/Api/Program.cs
- source/BuildingBlocks.Application/Configuration/SqlExtensions.cs
- source/BuildingBlocks.Infrastructure/Configuration/SqlConnectionSource.cs
- source/IncomingMessages.Application/Configuration/IncomingMessagesConfiguration.cs
- source/Infrastructure/Configuration/CompositionRoot.cs
- source/IntegrationTests/TestBase.cs
- source/OutgoingMessages.Application/Configuration/ActorMessageQueueConfiguration.cs
- source/OutgoingMessages.Application/OutgoingMessages.Application.csproj
- source/Process.Application/Configuration/ProcessConfiguration.cs
- source/Process.Application/Process.Application.csproj
No service for type 'Energinet.DataHub.EDI.BuildingBlocks.Infrastructure.Configuration.SqlConnectionSource' has been 
registered.
> fix: missing SqlConnectionSource configuration in B2C app

- .github/workflows/ci-dotnet.yml
Our test runs right now waits 3 minutes for the build to complete, then aborts. This PR increases it to 5 minutes. I think the only disadvantage on increasing the timeout is that if the build fails then the run will take longer to complete.
An alternative is to make the steps depend on the build, but then the tests overall time will be longer, since each test job won't start before the entire build is complete.
> build: Increase tests build timeout period

- .editorconfig
EditorConfig is updated for Rider/ReSharper to:
- Chop arguments to method calls and declarations if too long
- Allow trailing commas in multiline lists
- Chop chained method calls if too long
Additionally, there seemed to be an error wrt a range operator inspection, so this has been corrected too.
> style: Update Rider/ReSharper with (some of) the StyleCop formatting

- source/AcceptanceTests/Drivers/EdiDriver.cs
- source/AcceptanceTests/Dsl/AggregatedMeasureDataRequestDsl.cs
- source/AcceptanceTests/Tests/B2BErrors/WhenPayloadDataIsDifferentFromTokenDataTests.cs
Ensure HTTP status code is correct when performing B2B error acceptance tests, so we get the correct exception if the HTTP request fails
> test: Ensure success status code for request aggregated measure data with XML used in acceptance tests

- source/Api/IntegrationEventHandler.cs
- source/Infrastructure/Configuration/IntegrationEvents/IReceivedIntegrationEventRepository.cs
- source/Infrastructure/Configuration/IntegrationEvents/ReceivedIntegrationEventRepository.cs
- source/IntegrationTests/Infrastructure/Configuration/IntegrationEvents/TestFailingIntegrationEventProcessor.cs
- source/IntegrationTests/Infrastructure/Configuration/IntegrationEvents/WhenAnIntegrationEventIsReceivedTests.cs
The previous implementation would always save an entry into the `ReceivedIntegrationEvents` table, even if the underlying processing would fail. This PR refactors the `ReceivedIntegrationEventRepository` to take an `IDBConnection` and  `IDBTransaction` to ensure that a rollback is possible if processing the event fails.
> refac: integrationevents should not be saved when processing fails

- source/ArchivedMessages.Interfaces/ArchivedMessage.cs
- source/ArchivedMessages.Interfaces/ArchivedMessageType.cs
- source/IncomingMessages.Application/IncomingMessageClient.cs
- source/IntegrationTests/Application/ArchivedMessages/WhenArchivedMessageIsCreatedTests.cs
- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/IntegrationTests/Application/SearchMessages/SearchMessagesTests.cs
- source/IntegrationTests/TestBase.cs
- source/OutgoingMessages.Application/OutgoingMessages/MessagePeeker.cs
ArchivedMessages file storage reference is now dependent on whether the archived message is an incoming message (sender actor number) or outgoing message (receiver actor number)
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/33
> feat: ArchivedMessage file storage path based on incomming/outgoing type

- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesCommandTests.cs
- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureDataMarketDocumentBuilder.cs
- source/Process.Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/Tests/Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactoryTests.cs
If an actor leaves out the metering point point type, it is interpreted as:
- EnergySupplier: All production and consumption
- Balance responsible party: All production and consumption
- Metered data responsible: All production, consumption, and exchange
> feat: Allow empty metering point type declaration in aggregation request

- source/Api/OutgoingMessages/PeekRequestListener.cs
When Actors peek they need to be informed when we are missing required headers, before this PR a 500 was returned if the content-type header was not set.
> refac: ensure actors are informed when missing Content-Type header

- source/OutgoingMessages.Application/MarketDocuments/NotifyWholesaleServices/NotifyWholesaleServicesEbixDocumentWriter.cs
We are getting a null reference exception on Test-001, because outgoing messages was created with out any points for notify wholesale in ebix format.
> fix: null reference exception for outgoing message created before points was introduced

- source/AcceptanceTests/AcceptanceTests.csproj
- source/Api/Api.csproj
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/B2CWebApi/B2CWebApi.csproj
- source/BuildingBlocks.Application/BuildingBlocks.Application.csproj
- source/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
- source/IntegrationEvents/IntegrationEvents.Application/IntegrationEvents.Application.csproj
- source/IntegrationEvents/IntegrationEvents.Infrastructure/IntegrationEvents.Infrastructure.csproj
- source/IntegrationTests/IntegrationTests.csproj
- source/OutgoingMessages.Application/OutgoingMessages.Application.csproj
- source/OutgoingMessages.Infrastructure/OutgoingMessages.Infrastructure.csproj
- source/Process.Infrastructure/Process.Infrastructure.csproj
We have implicit reference to different version of  Microsoft.Bcl.AsyncInterfaces in our healtchecks, which means that some checks can't find this assembly in excepted version and fails when health check is requested.
> fix: ensure we use same version accross our modules of Microsoft.Bcl.AsyncInterfaces

- source/IntegrationTests/Application/IncomingMessages/WholesaleServices/WhenWholesaleServicesIsRequestedTests.cs
- source/IntegrationTests/TestBase.cs
- source/IntegrationTests/TestDoubles/ServiceBusSenderSpy.cs
- source/Process.Application/Extensions/DependencyInjection/InternalCommandExtensions.cs
- source/Process.Application/Extensions/DependencyInjection/ProcessExtensions.cs
- source/Process.Application/Transactions/WholesaleServices/Commands/Handlers/SendWholesaleServicesToWholesale.cs
- source/Process.Application/Transactions/WholesaleServices/Commands/SendWholesaleServicesRequestToWholesale.cs
- source/Process.Application/Transactions/WholesaleServices/Notifications/NotifyWholesaleThatWholesaleServicesIsRequestedHandler.cs
- source/Process.Application/Transactions/WholesaleServices/Notifications/NotifyWholesaleWhenWholesaleServicesProcessIsInitialized.cs
- source/Process.Domain/Transactions/AggregatedMeasureData/AggregatedMeasureDataProcess.cs
- source/Process.Domain/Transactions/WholesaleServices/ProcessEvents/NotifyWholesaleThatWholesaleServicesIsRequested.cs
- source/Process.Domain/Transactions/WholesaleServices/ProcessEvents/WholesaleServicesProcessIsInitialized.cs
- source/Process.Domain/Transactions/WholesaleServices/WholesaleServicesProcess.cs
- source/Process.Domain/Wholesale/IWholesaleInbox.cs
- source/Process.Infrastructure/Transactions/WholesaleServices/ServiceBusMessageFactory.cs
- source/Process.Infrastructure/Transactions/WholesaleServices/WholesaleServicesProcessFactory.cs
- source/Process.Infrastructure/Wholesale/WholesaleInbox.cs
Extend the wholesale services process to sent request to wholesale when initialized. 
Next PR will contain the handling of a rejected response
> feat: send wholesale services request to wholesale

- source/OutgoingMessages.Domain/OutgoingMessages/Queueing/OutgoingMessage.cs
When we are going to support delegation we need to be able to distinguish between the receiver in the message and which queue should receive the message
> feat: use receiver on outgoing message to determind the message receiver

- source/B2CWebApi/Factories/RequestAggregatedMeasureDataHttpFactory.cs
- source/B2CWebApi/Models/RequestAggregatedMeasureDataMarketDocument.cs
- source/Tests/B2CWebApi/RequestAggregatedMeasureData/RequestAggregatedMeasureDataFactoryTests.cs
Rename ProcessType to CalculationType
- Don't rename `RequestAggregatedMeasureDataMarketRequest.ProcessType`, since that requires a change in the BFF. We will make that change when we implement RequestWholesaleSettlement in the BFF & B2C api
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/46
> refac: Rename ProcessType to CalculationType

- source/BuildingBlocks.Domain/Models/ActorRole.cs
- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingOutgoingMessageWithDelegationTests.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/MasterData.Application/MasterDataClient.cs
We need to ensure that messages to metered data repsonsible is also delageted to a new receiver if there is a delegation relationship setup for the actor as a grid operator.
> feat: metered data responsible should also check delegation relations as grid operator

- source/OutgoingMessages.Application/MessageEnqueuer.cs
Add to actor message queue before uploading outgoing message to file storage, to (hopefully) fix the `Collection was modified; enumeration operation may not execute` exception that happens when adding OutgoingMessage to DbContext and querying ActorMessageQueue's in parallel.
Task: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/176
Microsoft documentation: https://learn.microsoft.com/da-dk/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues
> fix: Fix error when adding to actor message queue by awaiting immediately

- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingOutgoingMessageWithDelegationTests.cs
- source/IntegrationTests/Assertions/AssertOutgoingMessage.cs
- source/OutgoingMessages.Domain/Models/OutgoingMessages/OutgoingMessage.cs
- source/OutgoingMessages.Infrastructure/OutgoingMessages/OutgoingMessageEntityConfiguration.cs
We should ensure that the file storage reference for outgoing messages is matching the receiver.
> bug: ensure outgoing message file storage reference is updated to match delegation

- source/IntegrationTests/Application/IncomingMessages/RequestAggregatedMeasureData/InitializeAggregatedMeasureDataProcessesCommandTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestTests.cs
- source/IntegrationTests/EventBuilders/AggregatedTimeSeriesRequestAcceptedEventBuilder.cs
- source/Process.Infrastructure/Transactions/AggregatedMeasureData/AggregatedMeasureDataRequestFactory.cs
- source/RequestResponse/source/RequestResponse/Requests/AggregatedTimeSeries/AggregatedTimeSeriesRequest.proto
Allow multiple grid areas when sending a `AggregatedTimeSeriesRequest`, in preparation for using delegation for the request
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/148
> feat: Add multiple grid areas to AggregatedTimeSeriesRequest

- source/B2BApi/IncomingMessages/IncomingMessageReceiver.cs
- source/B2CWebApi/Controllers/RequestAggregatedMeasureDataController.cs
- source/IncomingMessages.Application/IncomingMessageClient.cs
- source/IncomingMessages.Interfaces/IIncomingMessageClient.cs
- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestWithDelegationTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestWithDelegationTests.cs
- source/IntegrationTests/EventBuilders/RequestWholesaleServicesRequestBuilder.cs
- Refactor `IncomingMessageClient.RegisterAndSendAsync()` `responseFormat` to make it more intuitive
- Add behaviour tests for synchronous validation error when delegation can't find the original actor number (for example if the role is energy supplier and energy supplier is not supplied in the message)
> test: Add behaviour test for delegation synchronous error

- .editorconfig
- Directory.Build.props
- source/AcceptanceTests/Drivers/EdiB2CDriver.cs
- source/AcceptanceTests/Dsl/ArchivedMessageDsl.cs
- source/AcceptanceTests/Responses/json/ArchivedMessageSearchResponse.cs
- source/AcceptanceTests/Responses/xml/SynchronousError.cs
- source/AcceptanceTests/Tests/B2BErrors/Asserters/ErrorAsserter.cs
- source/AcceptanceTests/Tests/B2BErrors/WhenBusinessTypeAndProcessTypeIsNotCorrectTests.cs
- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ArchitectureTests/ArchitectureTests.csproj
- source/B2BApi/B2BApi.csproj
- source/B2CWebApi/Models/RequestAggregatedMeasureDataMarketDocument.cs
- source/BuildingBlocks.Domain/Models/Period.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/Tests/Tests.csproj
- Update c# language version to 12 (enables collection initializers 🎉)
- Update stylecop version (required for language version 12.0)
- Remove stylecop reference from project files (it is already referenced in a shared `Directory.Build.props` file)
Updating stylecop version requires configuring the stylecop rule https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1402.md, since it was updated to not allow records in the same file as classes. This would be a big refactor in our repository, so we've reconfigured the rule to be a suggestion instead.
> chore: Update c# language version to 12

- source/IncomingMessages.Application/MessageParser/WholesaleSettlementMessageParsers/XmlMessageParser.cs
- source/Tests/CimMessageAdapter/Messages/WholesaleSettlementMessageParsers/MessageParserTests.cs
- source/Tests/CimMessageAdapter/Messages/json/WholesaleSettlement/RequestWholesaleSettlement.json
- source/Tests/CimMessageAdapter/Messages/xml/WholesaleSettlement/RequestWholesaleSettlement.xml
- source/Tests/CimMessageAdapter/Messages/xml/WholesaleSettlement/RequestWholesaleSettlementTwoSeries.xml
- source/Tests/Tests.csproj
For some ungodly reason a xml request with resolution = "P1M" was translated to "P30D"
This is fixed now such that we do not alter the input, which we should not.
> fix: Altered reading method of resolution for wholesale services

- source/IntegrationTests/Application/OutgoingMessages/TestData/EnergyResultPerBrpGridAreaDescription.cs
- source/IntegrationTests/Application/OutgoingMessages/TestData/EnergyResultPerEnergySupplierBrpGridAreaDescription.cs
- source/IntegrationTests/Application/OutgoingMessages/TestData/EnergyResultPerGridAreaDescription.cs
- source/IntegrationTests/Application/OutgoingMessages/TestData/EnergyResultTestDataDescription.cs
- source/IntegrationTests/Application/OutgoingMessages/TestData/ExampleDataForActor.cs
- source/IntegrationTests/Application/OutgoingMessages/TestData/ExampleEnergyResultMessageForActor.cs
- source/IntegrationTests/Application/OutgoingMessages/TestData/ExampleMessageForActor.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenAggregatedMeasureDataRequestWithDelegationTests.cs
- source/IntegrationTests/Behaviours/IntegrationEvents/GivenCalculationCompletedV1ReceivedForBalanceFixingTests.cs
- source/IntegrationTests/DocumentAsserters/NotifyAggregatedMeasureDataDocumentAsserter.cs
- source/IntegrationTests/DocumentAsserters/NotifyAggregatedMeasureDataDocumentAssertionInput.cs
- source/IntegrationTests/Factories/TimeSeriesPointsFactory.cs
- source/Tests/Infrastructure/OutgoingMessages/Asserts/TimeSeriesPointAssertionInput.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/AssertNotifyAggregatedMeasureDataEbixDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/AssertNotifyAggregatedMeasureDataJsonDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/AssertNotifyAggregatedMeasureDataXmlDocument.cs
- source/Tests/Infrastructure/OutgoingMessages/NotifyAggregatedMeasureData/IAssertNotifyAggregatedMeasureDataDocument.cs
- Add behaviour test that tests the calculaton orchestration activities aggregation levels and asserts an actor can peek a correct document
- Change time series point assertion for `IAssertNotifyAggregatedMeasureDataDocument` to use a `TimeSeriesPointAssertionInput` instead of the `TimeSeriesPoint` from protobuf contracts
- Change quality assertion for `IAssertNotifyAggregatedMeasureDataDocument` to use the calculated quality as input instead of the `QuantityQuality` from protobuf contracts
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/199
> test: Add behavior test for calculation orchestration activities

- source/B2CWebApi/Models/MarketRole.cs
- source/B2CWebApi/Security/FrontendUserProvider.cs
- source/Tests/B2CWebApi/FrontendUserProviderTests.cs
- source/Tests/B2CWebApi/RequestWholesaleSettlement/RequestWholesaleSettlementFactoryTests.cs
- source/Tests/TestLogger.cs
EDI tried to map B2C front-end user roles using the `ActorRole` names, however these names are not equal to the names written in the B2C front-end user claims. The correct role claim values are written in the `MarketRole` class.
- Use `MarketRole` names to map B2C front-end user claim values to `ActorRole`
- Refactor `MarketRole` to use `DataHubType`
- Add tests to ensure `FrontendUserProvider` maps to correct authenticated actor
- Add logging to enable tracing the B2C user roles in application insights
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/150
> fix: Fix mapping B2C market roles to correct actor roles

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
A vulnerability has been discovered (and fixed) in the System.Text.Json v8.0.3 NuGet package, which means that the CI analyzer fails. This updates the package to fix the vulnerability, and make the pipeline able to build again.
Failed analyzer CI job: https://github.com/Energinet-DataHub/opengeh-edi/actions/runs/9870108201/job/27256590568?pr=1116
> chore: Update System.Text.Json to fix vulnerability

- source/B2CWebApi/B2CWebApi.csproj
- source/B2CWebApi/Controllers/OrchestrationsController.cs
- source/B2CWebApi/Extensions/DependencyInjection/DurableClientExtensions.cs
- source/B2CWebApi/Program.cs
- source/B2CWebApi/appsettings.sample.json
Expose endpoints (to datahub admins) to get status and terminate running orchestrations, since Durable Function Monitor cannot be used in production. The endpoints can only be accessed if the user:
- Belongs to actor `5790001330583`, which is `Energinet DataHub A/S (DataHub systemadministrator)`
- Has Azp `00000000-0000-0000-0000-000000000001`
- Has role `DataHubAdministrator`
- Has role claim `calculations:manage`
- Infrastructure PR: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/1738
- Issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/217
- D-002 deploy run: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/9875157629
> feat: Add orchestration control admin endpoints

- source/Contracts/Contracts.csproj
Because of issue https://github.com/grpc/grpc/issues/36518 we have to revert to v. 2.62.0 for all developers to be able to build locally.
> chore: Revert Grps.Tools to v 2.62.0

- source/B2BApi/Functions/EnqueueMessages/Activities/GetActorsForWholesaleResultsForAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/GetActorsForWholesaleResultsForMonthlyAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/Activities/GetActorsForWholesaleResultsForTotalAmountPerChargesActivity.cs
- source/B2BApi/Functions/EnqueueMessages/EnqueueMessagesOrchestration.cs
- source/OutgoingMessages.Infrastructure/Databricks/WholesaleResults/Queries/WholesaleMonthlyAmountPerChargeQuery.cs
- source/OutgoingMessages.Infrastructure/Databricks/WholesaleResults/Queries/WholesaleTotalAmountQuery.cs
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/217
> refac: Cleanup orchestrations

- source/B2CWebApi/Factories/RequestAggregatedMeasureDataDtoFactory.cs
- source/B2CWebApi/Factories/RequestWholesaleSettlementDtoFactory.cs
- source/B2CWebApi/Models/MarketRole.cs
- source/B2CWebApi/Security/FrontendUserProvider.cs
- source/Tests/B2CWebApi/RequestWholesaleSettlement/RequestWholesaleSettlementFactoryTests.cs
MarketRole (b2c) didn't have a representation of a DataHubAdministrator, which made it log a warring with an exception each time a DataHubAdministrator User was making a request. 
This PR contains the following: 
- Change MarketRole to EnumerationType, since not all roles have a code.
- Added DataHubAdministrator to MarketRole
- Avoid resolving an ActorRole for DataHubAdministrator, since they don't have any. 
- https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/257
> fix: avoid resolving actor roles for b2b DataHubAdministrator

- source/IntegrationTests/Infrastructure/Retention/RemoveOldDequeuedBundlesWhenADayHasPassedTests.cs
- source/OutgoingMessages.Domain/Models/ActorMessagesQueues/IActorMessageQueueRepository.cs
- source/OutgoingMessages.Domain/Models/Bundles/IBundleRepository.cs
- source/OutgoingMessages.Infrastructure/DequeuedBundlesRetention.cs
- source/OutgoingMessages.Infrastructure/Repositories/ActorMessageQueues/ActorMessageQueueRepository.cs
- source/OutgoingMessages.Infrastructure/Repositories/Bundles/BundleRepository.cs
This PR will change the way that bundles are removed because of the sheer amount of potential undequeued bundles (as of now there is around 4 million bundles on production).
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/258
> refac: Bundles are removed outside of the ActorMessageQueue

- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingOutgoingMessageTests.cs
- source/OutgoingMessages.Application/OutgoingMessageFactory.cs
- source/OutgoingMessages.Application/OutgoingMessagesClient.cs
- source/OutgoingMessages.Domain/Models/OutgoingMessages/OutgoingMessage.cs
- source/Tests/Domain/OutgoingMessages/Queueing/ActorMessageQueueTests.cs
- source/Tests/Domain/OutgoingMessages/Queueing/OutgoingMessageTests.cs
This will lighten the `OutgoingMessage` domain model and seek to move its coupling to DTO's and factory patterns into a `OutgoingMessageFactory` located in `OutgoingMessage.Application`.
My next PR will remove the reference to `OutgoingMessage.Interfaces` from the `OutgoingMessage.Domain` project.
> refac: OutgoingMessageFactory

- source/OutgoingMessages.Infrastructure/Databricks/WholesaleResults/Factories/QuantityQualitiesFactor.cs
- source/Process.Application/Transactions/Mappers/CalculatedQuantityQualityMapper.cs
- source/Process.Application/Transactions/WholesaleServices/WholesaleServicesRequestAcceptedMapper.cs
- source/Tests/Domain/Transactions/Mappers/CalculatedQuantityQualityMapperTests.cs
We didn't map quality correctly for amount results when charge types were fees and subscriptions. 
This PR updates the mapping of quality both for request and new calculation results according to this article: 
https://energinet.atlassian.net/wiki/spaces/D3/pages/529989633/QuantityQuality
> The subscription and fee has no QuantityQuality. Therefore, the QuantityQuality in RSM-019 is always 'calculated' unless the price is missing (null), in which case the QuantityQuality is 'Incomplete'.
> in general if the “Price” for a charge is not available (null), then the QuantityQuality must be “Incomplete (A05)” in CIM.
Be aware that CalculatedQuantityQuality.Missing is written as Incompleted in CIM
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/intern …
> fix: wholesale request quality mappers

- .github/workflows/ci-dotnet.yml
- source/Tests/Tests.csproj
Use matrix for execution of tests in CI.
PoC'ed splitting the IntegrationTests execution up, but it didn't improve the build time much, so decided not to add it ATM.
Part of:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/279
> build: Use matrix for execution of tests in CI

- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
Refactor flaky test so we get more precise information in CI log if it fails.
Example of new output:
Part of:
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/279
> refac: Refactor flaky test

- source/IncomingMessages.Domain/Validation/ValidationErrors/DuplicateTransactionIdDetected.cs
- source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
When DuplicateMessageIdDetected is triggered tests are green. However, since DuplicateTransactionIdDetected had a wrong error code in one of the two constructors tests will then be red.
> test: fix flaky test to use correct error code

- source/ApplyDBMigrationsApp/Scripts/Model/202408141237 Add IdempotentId to OutgoingMessages.sql
FIX: The CREATE UNIQUE INDEX statement terminated because a duplicate key was found for the object name 'dbo.OutgoingMessages' and the index name 'IDX_OutgoingMessageIdempotency'. The duplicate key value is (449478DA-516A-47B7-B7B0-63294771485C).
> fix: external id is not unique for idempotent field

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202408201253 Add PeriodStartedAt to OutgoingMessages.sql
- source/ApplyDBMigrationsApp/Scripts/Model/202408201254 Add Idempontent index to OutgoingMessages.sql
- source/IntegrationTests/Application/OutgoingMessages/WhenEnqueueingOutgoingMessageTests.cs
- source/OutgoingMessages.Application/UseCases/EnqueueMessage.cs
- source/OutgoingMessages.Domain/Models/OutgoingMessages/IOutgoingMessageRepository.cs
- source/OutgoingMessages.Domain/Models/OutgoingMessages/OutgoingMessage.cs
- source/OutgoingMessages.Infrastructure/Repositories/OutgoingMessages/OutgoingMessageEntityConfiguration.cs
- source/OutgoingMessages.Infrastructure/Repositories/OutgoingMessages/OutgoingMessageRepository.cs
4mio outgoing messages in db
Perf with Idempotent id field on outgoing messages 
=> Enqueue 291 messages => Orchestration completed in 00:01:27.4812993
Perf with this PR 
=> Enqueue 291 messages => Orchestration completed in 00:00:22.0314863
> feat: improve performance on idempotent check for outgoing messages

- source/ArchitectureTests/ArchitectureTests.csproj
- source/ArchivedMessages.Infrastructure/ArchivedMessages.Infrastructure.csproj
- source/DataAccess/DataAccess.csproj
- source/DataAccess/Extensions/DependencyInjection/DatabaseExtensions.cs
- source/IncomingMessages.Application/IncomingMessages.Application.csproj
Use `AdaskoTheBeAsT.Dapper.NodaTime` instead of the deprecated `Dapper-NodaTime`.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/246
https://github.com/Energinet-DataHub/dh3-environments/actions/runs/10504272641
> chore: Use AdaskoTheBeAsT.Dapper.NodaTime instead of Dapper-NodaTime

- source/BuildingBlocks.Domain/Models/ExternalId.cs
- source/OutgoingMessages.Domain/Models/OutgoingMessages/OutgoingMessage.cs
This PR will aim to provide more insight of the importance of `ExternalId` for `OutgoingMessage` idempotency
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/242
> docs: A bit better guidance for OutgoingMessage idempotency

- source/ArchitectureTests/ArchitectureTests.csproj
- source/ArchitectureTests/RegistrationTests.cs
- source/B2BApi.AppTests/Fixtures/B2BApiAppFixture.cs
- source/B2BApi/local.settings.sample.json
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/TestBase.cs
- source/OutgoingMessages.Infrastructure/Databricks/CalculationResultQueryBase.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Queries/EnergyResultPerBalanceResponsiblePerGridAreaQuery.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Queries/EnergyResultPerEnergySupplierPerBalanceResponsiblePerGridAreaQuery.cs
- source/OutgoingMessages.Infrastructure/Databricks/EnergyResults/Queries/EnergyResultPerGridAreaQuery.cs
- source/OutgoingMessages.Infrastructure/Extensions/Options/EdiDatabricksOptions.cs
Use unity catalog instead of hive metastore when getting data from views in databricks
- Use `CatalogName` appsetting when running in Azure (populated from infrastructure)
- Use `hive_metastore` as `CatalogName` when running tests
I've verified that the subsystem test queries on dev002 actually are querying the unity catalog instead of hive metastore:
`ctl_shres_d_we_002` is the name of the unity catalog on d002
- Task: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/252 => https://github.com/Energinet-DataHub/dh3-environments/actions/runs/10524051443/job/29160300618
- ~~[ ] Should the change be behind a feature flag?~~
> feat: Use unity catalog instead of hive metastore

- source/AcceptanceTests/AcceptanceTests.csproj
- source/ArchitectureTests/RegistrationTests.cs
- source/B2BApi.AppTests/B2BApi.AppTests.csproj
- source/B2BApi.AppTests/Fixtures/B2BApiAppFixture.cs
- source/B2BApi/EventListeners/InboxEventListener.cs
- source/B2BApi/EventListeners/IntegrationEventListener.cs
- source/B2BApi/EventListeners/ProcessInitializationListener.cs
- source/B2CWebApi.AppTests/B2CWebApi.AppTests.csproj
- source/B2CWebApi.AppTests/Fixture/B2CWebApiFixture.cs
- source/BuildingBlocks.Application/BuildingBlocks.Application.csproj
- source/BuildingBlocks.Application/Extensions/DependencyInjection/BuildingBlockExtensions.cs
- source/BuildingBlocks.Application/Extensions/DependencyInjection/HealtCheckExtensions.cs
- source/BuildingBlocks.Application/Extensions/DependencyInjection/ServiceBusExtensions.cs
- source/BuildingBlocks.Application/Extensions/Options/ServiceBusOptions.cs
- source/IncomingMessages.Application/Extensions/DependencyInjection/IncomingMessagesExtensions.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/IntegrationTests.csproj
- source/IntegrationTests/TestBase.cs
- source/Process.Application/Extensions/DependencyInjection/ProcessExtensions.cs
- source/SystemTests/SystemTests.csproj
Refactor any use of ServiceBus to identity access management (IAM) instead of shared access policies (connection strings).
**Important changes:**
- When using `ServiceBusTrigger` we must configure a setting with the name `<SectionName>_FullyQualifiedNamespace` and configure the trigger parameter `Connection` with the `<SectionName>` value.
- When configuring `AddAzureClients()` we must use the `UseCredential()` and `AddServiceBusClientWithNamespace()` to configure the top level `ServiceBusClient`. Any place where we need a service bus sender/receiver/processor we must inject `ServiceBusClient` and use it to create the lower level clients.
- When configuring health checks we must use the overloads where we specify the parameters `fullyQualifiedNamespaceFactory` and …
> refac: Use ServiceBus IAM

- source/B2BApi/Functions/EnqueueMessages/EnqueueMessagesOrchestration.cs
- source/B2BApi/MetricTracker/CustomMetricConstants.cs
Collect the avg duration of enqueueing a message
> feat: collect avg message enqueue duration for metric

- source/B2BApi/Functions/EnqueueMessages/EnqueueMessagesOrchestration.cs
> feat: track EnqueueMessageAvgDuration in nano seconds

- source/ApplyDBMigrationsApp/Scripts/Model/202409121115 Change Id length for ChargeType.sql
The charge type id cannot be longer than 10. However, it is possible for an actor to provide a request of an id of arbitrary length. In order to ensure, or at least for the most part ensure, that the actor receives the corresponding "too long" async message, EDI needs to be able to store these long ids in order to send them to wholesale.
To avoid the case of "arbitrary long" we have settled on UUID + 1, i.e. 37 chars. If the request contains an id longer than this, the request will end up on the dead-letter queue without notifying the actor. This is agreed upon behaviour, as the dead-letter queue is monitored by DataHub.
- As we increase the length of the field, there should be no data loss. In the case we have to shrink it again, any stored id longer than the new length would cause …
> fix: Allow longer charge type ids in the database

- source/B2BApi/OutgoingMessages/PeekRequestListener.cs
When external actors peeks, we should not return 404 but 204 instead to tell their connection is established.
> fix: return no-content when peek is disabled

- source/B2BApi.AppTests/IncomingMessages/IncomingMessageReceiverTests.cs
- source/B2BApi/IncomingMessages/IncomingMessageReceiver.cs
Payload values from requests were not logged in the audit log.
> fix: request payload is logged in audit log

- source/Process.Application/Extensions/DependencyInjection/WholesaleInboxExtensions.cs
The health check (introduced in #1210) has been removed from EDI and added to the wholesale subsystem where it belongs.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/303
> fix: Remove dead-letter health check from wholesale inbox

- .github/workflows/ci-dotnet.yml
These IntegrationTests project were never implanted in the CI which was a major blunder. The PR will introduce the `MasterData` and `IntegrationEvents` integrationtests into the CI
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/308
> enable MasterData/IntegrationEvents IntegrationTests in CI

- source/MasterData.IntegrationTests/Fixture/MasterDataFixture.cs
Fixtures should delete the database generated for the testrun after execution.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/308
> refac: MasterDataFixture deletes DB after run

- source/ArchivedMessages.Infrastructure/QueryBuilder.cs
- source/ArchivedMessages.IntegrationTests/SearchMessagesWithoutRestrictionTests.cs
> fix: returned to many records when sorting with a filter on

- source/ArchivedMessages.Infrastructure/QueryBuilder.cs
- source/ArchivedMessages.IntegrationTests/ArchivedMessagesWithoutRestrictionTests.cs
- source/ArchivedMessages.Interfaces/GetMessagesQuery.cs
- source/B2CWebApi/Controllers/ArchivedMessageSearchController.cs
- source/B2CWebApi/Models/SearchArchivedMessagesCriteria.cs
Add ReceiverRole and SenderRole filter options which can be used by the FAS user when searching archived message
The related PRs will contain the following:
> feat: sender and receiver role code filter on archived messages

- source/SubsystemTests/Drivers/EdiDatabaseDriver.cs
- source/SubsystemTests/Drivers/EdiDriver.cs
- Cleanup before load test threw a sql timeout exception, since deleting messages could take more than the default 30 seconds timeout. This PR increased the timeout to 2 minutes.
- Cleanup after load test didn't correctly stop the orchestration, which is now fixed
> test: Increase outgoing message deletion timeout for load tests

- source/BuildingBlocks.Domain/Models/IncomingDocumentType.cs
- source/IncomingMessages.Application/Extensions/DependencyInjection/IncomingMessagesExtensions.cs
- source/IncomingMessages.Infrastructure/MessageParsers/MarketMessageParser.cs
- source/IncomingMessages.Infrastructure/MessageParsers/MeteredDateForMeasurementPointParsers/MeteredDateForMeasurementPointEbixMessageParser.cs
- source/IncomingMessages.IntegrationTests/MessageParsers/GivenNewDocumentTypeTests.cs
- source/Tests/B2CWebApi/Mappers/DocumentTypeMapperTests.cs
Grid operators (MDR), should be able to send metered data for a measurement point to EDI in the Ebix format, as described in the referenced task. Below is a list of the excepted PRs needed to prepare IncomingMessageClient to handle this new message
Previous PRs:
- (none)
This PR contains:
Following PRs:
> feat: introduce new MeteredDataForMeasurementPoint IncomingDocumentType

- source/B2BApi/Common/HttpRequestDataExtensions.cs
- source/B2BApi/IncomingMessages/EbixIncomingMessageReceiver.cs
- source/B2BApi/IncomingMessages/IncomingMessageReceiver.cs
Introduces a new receiver for incoming messages. The route contains no document type or format. The route is assumed to only be used with metered data for measurement points in the ebix format. We allow this strong assumption, as to the best of our knowledge, no other type of incoming ebix messages exists.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/351
> feat: Introduce receiver for incoming ebix messages

- source/IncomingMessages.Infrastructure/Response/EbixResponseFactory.cs
- source/IncomingMessages.Infrastructure/Response/JsonResponseFactory.cs
- source/IncomingMessages.Infrastructure/Response/ResponseFactory.cs
- source/IncomingMessages.Infrastructure/Response/XmlResponseFactory.cs
- source/Tests/CimMessageAdapter/Response/EbixResponseFactoryTests.cs
- source/Tests/CimMessageAdapter/Response/JsonResponseFactoryTests.cs
- source/Tests/CimMessageAdapter/Response/ResponseFactoryTests.cs
- source/Tests/CimMessageAdapter/Response/XmlResponseFactoryTests.cs
- source/Tests/Tests.csproj
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/351
> test: Align and extend XyzResponseFactoryTests with verbatim comparison

- source/Process.Application/Extensions/DependencyInjection/ProcessExtensions.cs
- source/Process.Application/ProcessInitializationHandlers/InitializeMeteredDataForMeasurementPointHandler.cs
Grid operators (DDM), should be able to send metered data for a measurement point to EDI in the Ebix format, as described in the referenced task. Below is a list of the excepted PRs needed to prepare IncomingMessageClient to handle this new message
Previous PRs:
This PR contains:
Following PRs:
> feat: stub impl of InitializeMeteredDataForMeasurementPointHandler to avoid errors

- source/IncomingMessages.Application/DelegateIncomingMessage.cs
- source/IncomingMessages.Domain/Abstractions/BaseDelegatedSeries.cs
- source/IncomingMessages.Domain/Abstractions/IDelegatedIncomingMessageSeries.cs
- source/IncomingMessages.Domain/MeteredDataForMeasurementPointMessage.cs
- source/IncomingMessages.Infrastructure/Factories/InitializeMeteredDataForMeasurementPointProcessDtoFactory.cs
- source/IncomingMessages.Infrastructure/IncomingMessagePublisher.cs
- source/IncomingMessages.IntegrationTests/IncomingMessages/GivenIncomingMessagesTests.cs
- source/IncomingMessages.IntegrationTests/IncomingMessages/GivenIncomingMessagesWithDelegationTests.cs
- source/IntegrationEvents.Infrastructure/EventProcessors/ProcessDelegationConfiguredEventProcessor.cs
- source/Process.Interfaces/InitializeMeteredDataForMeasurementPointMessageProcessDto.cs
Grid operators (DDM), should be able to send metered data for a measurement point to EDI in the Ebix format, as described in the referenced task. Below is a list of the excepted PRs needed to prepare IncomingMessageClient to handle this new message
Previous PRs:
This PR contains:
Following PRs:
> feat: added delegation handling for metered data messages

- source/SubsystemTests/LoadTest/LoadTestFixture.cs
Fix load test service bus connection after change to IAM.
> test: Fix load test service bus connection

- .github/workflows/ci-dotnet.yml
- source/OutgoingMessages.Application/UseCases/PeekMessage.cs
- source/OutgoingMessages.IntegrationTests/OutgoingMessages/WhenAPeekIsRequestedTests.cs
When archiving outgoing messages, We store the business reason name instead of the code. 
Therefore, when searching for archived messages the business reason filter can't find any outgoing messages.
> fix: wrong value for business reason when archiving outgoing messages

- source/BuildingBlocks.Domain/Models/MessageType.cs
- source/IncomingMessages.Application/UseCases/ValidateIncomingMessage.cs
- source/IncomingMessages.Domain/Abstractions/IIncomingMessage.cs
- source/IncomingMessages.Domain/MessageParsers/RSM012/MeteredDateForMeasurementPointEbixMessageParser.cs
- source/IncomingMessages.Domain/MessageParsers/RSM012/MeteredDateForMeasurementPointJsonMessageParser.cs
- source/IncomingMessages.Domain/MessageParsers/RSM012/MeteredDateForMeasurementPointXmlMessageParser.cs
- source/IncomingMessages.Domain/MeteredDataForMeasurementPointMessage.cs
- source/IncomingMessages.Domain/RequestAggregatedMeasureDataMessage.cs
- source/IncomingMessages.Domain/RequestWholesaleServicesMessage.cs
- source/IncomingMessages.Domain/Validation/MessageTypeValidator.cs
- source/IncomingMessages.Domain/Validation/ProcessTypeValidator.cs
- source/IncomingMessages.Domain/Validation/SenderAuthorizer.cs
- source/IncomingMessages.Infrastructure/Factories/InitializeMeteredDataForMeasurementPointProcessDtoFactory.cs
- source/IncomingMessages.Infrastructure/IncomingMessagePublisher.cs
- source/IncomingMessages.IntegrationTests/IncomingMessages/GivenIncomingMeteredDataForMeasurementMessageTests.cs
- source/Tests/CimMessageAdapter/Messages/MeteredDataForMeasurementPointMessageParserTests/MessageParserTests.cs
- source/Tests/Infrastructure/IncomingMessages/SenderAuthorizerTests.cs
I refactored the IIncomingMessage interface to include properties for specifying allowed values for business validation in the sync flow:
- IReadOnlyCollection<string> AllowedMessageTypes { get; }
- IReadOnlyCollection<BusinessReason> AllowedBusinessReasons { get; }
- IReadOnlyCollection<ActorRole> AllowedSenderRoles { get; }
With this refactoring, any new implementation of IIncomingMessage must define the allowed values for these properties. The validation framework will then automatically validate the document against these values. As a result, it is no longer necessary to extend the validation framework when introducing a new IIncomingMessage implementation.
> refac: move incoming message validation requirement into domain models

- source/SubsystemTests/Drivers/EdiDatabaseDriver.cs
> fix: Include all bundles in clean-up in load test SQL statement

- source/SubsystemTests/Drivers/EdiDatabaseDriver.cs
We had a timeout of our load test. Since it does enqueue a lot of messages, the timeout has been extended.
> test: Extend timeout for clean-up in load test

- source/IncomingMessages.Domain/MessageParsers/RSM012/MeteredDateForMeasurementPointJsonMessageParser.cs
- source/IncomingMessages.IntegrationTests/Builders/MeteredDataForMeasurementPointBuilder.cs
- source/IncomingMessages.IntegrationTests/IncomingMessages/GivenIncomingMeteredDataForMeasurementMessageTests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenMeteredDataForMeasurementPointTests.cs
- source/IntegrationTests/Behaviours/MeteredDataForMeasurementPointBehaviourTestBase.cs
- source/Process.Application/ProcessInitializationHandlers/InitializeMeteredDataForMeasurementPointHandler.cs
- source/Tests/CimMessageAdapter/Messages/MeteredDataForMeasurementPointMessageParserTests/MessageParserTests.cs
- source/Tests/Infrastructure/OutgoingMessages/RSM012/AssertMeteredDateForMeasurementPointXmlDocument.cs
- We accidentally read the points from the `Series` element, instead of the `Period` for JSON.
- We assumed that a `Point` always had all its values for JSON. This is incorrect, as two of them are nullable.
- We created a lot of points for our behaviour tests. This is now reduced to four: one for each structural case.
- We did not handle decimals correctly wrt assertion and temporary serialisation.
- `GivenIncomingMessagesWithDelegationTests` relies on eBix for RSM-12. It should work for XML/JSON too, but it does not. We should fix this in another PR.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/377
> fix: Read Point from Period and not Series elements

- .github/workflows/cd.yml
This pull request includes a correction to the `dispatch_deployment_event` job name in the `.github/workflows/cd.yml` file to ensure proper workflow execution.
* [`.github/workflows/cd.yml`](diffhunk://#diff-ea3ea8c9932adc7ba8161ceda844fedd43b006848ef1140c050cbd7ea0788a18L46-R46): Corrected the job name from `dispatch_deploment_event` to `dispatch_deployment_event` in two places to fix a typo. [[1]](diffhunk://#diff-ea3ea8c9932adc7ba8161ceda844fedd43b006848ef1140c050cbd7ea0788a18L46-R46) [[2]](diffhunk://#diff-ea3ea8c9932adc7ba8161ceda844fedd43b006848ef1140c050cbd7ea0788a18L75-R75)
> Update cd: fix typo in job name

- source/ArchivedMessages.IntegrationTests/Fixture/ArchivedMessagesFixture.cs
- source/ArchivedMessages.IntegrationTests/WhenArchivedMessageIsCreatedTests.cs
This PR moves the `WhenArchivedMessageIsCreatedTests` from the "old" `IntegrationTest `project into the `ArchivedMessage.IntegrationTest`.
- Some tests have been rewritten to a simpler approach
- A single test have been removed.
- This was dont because `ArchivedMessage`s FileStorageReference Id is now always made with a unique id when using the `ArchivedMessageDto`
This change has no reference, its simply boyscout'ing 🫡
> refac: WhenArchivedMessageIsCreatedTests

- source/SubsystemTests/Drivers/EdiDatabaseDriver.cs
- source/SubsystemTests/Drivers/EdiFileStorageDriver.cs
- source/SubsystemTests/LoadTest/ForwardMeteredData.cs
- source/SubsystemTests/LoadTest/LoadTestFixture.cs
- source/SubsystemTests/SubsystemTests.csproj
- source/SubsystemTests/loadtests.local.settings.sample.json
All data from the previous performance test is being cleaned up. 
This is executed before the test in case the Azure Load test has been started manually and after to ensure we free up space as soon as possible. 
- https://github.com/Energinet-DataHub/dh3-environments/pull/1320
- https://github.com/Energinet-DataHub/dh3-environments/actions/runs/12597916588
- https://github.com/Energinet-DataHub/dh3-environments/actions/runs/12597931062
> test: clean up file storage during performance test

- source/SubsystemTests/Drivers/EdiDatabaseDriver.cs
- source/SubsystemTests/LoadTest/ForwardMeteredData.cs
> fix: ensure old load test data is not included for metered data result

- source/BuildingBlocks.Domain/Models/MeteringPointType.cs
- source/Process.Application/Transactions/WholesaleServices/Mappers/MeteringPointTypeMapper.cs
- source/Tests/BuildingBlocks/Models/MeteringPointTypeTests.cs
MeteringPointType EffectSettlement has been renamed to CapacitySettlement in the calculation results
> fix: capacitysettlement is not a valid MeteringPointType name

- source/Edi.UnitTests/Validators/WholesaleServicesRequest/PeriodValidationRuleTests.cs
- source/Edi/Validation/WholesaleServicesRequest/Rules/PeriodValidationRule.cs
This PR will fix a bug with requesting `WholesaleServices` over a period when a year changes. It is copied from `Wholesale` repo's changes in this PR: 
https://github.com/Energinet-DataHub/opengeh-wholesale/commit/d42ae1c23302191c5035a476e06529a1b4dbcd8b
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/internal-repo/1535
> refac: PeriodValidationRule for WholesaleRequsts

- source/ArchivedMessages.Infrastructure/QueryBuilder.cs
B2C app, BFF and Frontend is not prepared to receive NotifyValidatedMeasureData. 
This PR contains a workaround to fix this: Document type not supported: NotifyValidatedMeasureData The unsupported member type is located on type 'Energinet.DataHub.EDI.B2CWebApi.Models.ArchivedMessageResultV3'. Path: $.Messages. Document type not supported: NotifyValidatedMeasureData
> fix: added arhived message filter to ignore NotifyValidatedMeasureData

- source/ArchitectureTests/RegistrationTests.cs
- source/ArchivedMessages.IntegrationTests/Fixture/ArchivedMessagesFixture.cs
- source/B2BApi.AppTests/Fixtures/B2BApiAppFixture.cs
- source/B2CWebApi.AppTests/Fixture/B2CWebApiFixture.cs
- source/BuildingBlocks.Infrastructure/Configuration/Options/BlobServiceClientConnectionOptions.cs
- source/BuildingBlocks.Infrastructure/DataLakeFileStorageClient.cs
- source/BuildingBlocks.Infrastructure/Extensions/DependencyInjection/FileStorageExtensions.cs
- source/BuildingBlocks.Infrastructure/FeatureFlag/FeatureFlagName.cs
- source/BuildingBlocks.Infrastructure/FeatureFlag/IFeatureFlagManager.cs
- source/BuildingBlocks.Infrastructure/FeatureFlag/MicrosoftFeatureFlagManager.cs
- source/BuildingBlocks.Tests/TestDoubles/FeatureFlagManagerStub.cs
- source/Edi.UnitTests/EdiTestBase.cs
- source/IncomingMessages.IntegrationTests/IncomingMessagesTestBase.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/TestBase.cs
- source/MasterData.IntegrationTests/Fixture/MasterDataTestBase.cs
- source/OutgoingMessages.IntegrationTests/OutgoingMessagesTestBase.cs
- source/Tests/BuildingBlocks/FileStorageClient/DataLakeFileStorageClientTests.cs
- infra: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/2793
> feat: extend DataLakeFileStorageClient with a client to the new storage account

- source/B2BApi.AppTests/B2BApi.AppTests.csproj
- source/B2BApi/B2BApi.csproj
- source/B2CWebApi.AppTests/B2CWebApi.AppTests.csproj
- source/IncomingMessages.Infrastructure/IncomingMessages.Infrastructure.csproj
- source/IncomingMessages.Infrastructure/ProcessManager/MeteredDataOrchestrationStarter.cs
- source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
Add actor number and role to BRS-021 input for the PM.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/490
> feat: Add actor identification to MeteredDataForMeteringPointMessageInputV1

- source/BuildingBlocks.Infrastructure/DataLakeFileStorageClient.cs
- source/Tests/BuildingBlocks/FileStorageClient/DataLakeFileStorageClientTests.cs
This logging is to help ensure that the migration of the obsolete document storage is succesful, will be removed when we have verified the migration and the `DataLakeFileStorageClient` is cleaned up.
> feat: log if DataLakeFileStorageClient uses obsolete blobclient

- .github/workflows/ci-dotnet.yml
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestV2Tests.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenWholesaleServicesRequestV2WithDelegationTests.cs
- source/IntegrationTests/CalculationResults/RequestCalculationResult/WholesaleServicesQueriesCsvTests.cs
- source/OutgoingMessages.Infrastructure/Databricks/CalculationResults/Statements/WholesaleServicesQuerySnippetProvider.cs
This PR fix incident: INC0429484, where the grid operator could get not tax charges from SYO.
The wholesale query has been updated to ensure only taxes are queried for grid operators + spilt the integration tests into multiple runs.
> fix: where grid operator received not tax charges from syo

- source/B2BApi/OutgoingMessages/PeekRequestListener.cs
- source/BuildingBlocks.Domain/Models/DocumentType.cs
- source/BuildingBlocks.Domain/Models/MessageCategory.cs
Rename `TimeSeries` category to `MeasureData`.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/585
- d002 deploy without infra: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13761276193
- d002 deploy with infra: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/13761308079 (https://github.com/Energinet-DataHub/dh3-infrastructure/pull/3105)
> refac: Rename TimeSeries to MeasureData

- source/IncomingMessages.Infrastructure/ProcessManager/MeteredDataOrchestrationStarter.cs
- source/IntegrationTests/Behaviours/IncomingRequests/GivenMeteredDataForMeteringPointV2Tests.cs
- source/IntegrationTests/EventBuilders/MeteredDataForMeteringPointEventBuilder.cs
- source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
We should not send the quality code for brs021, but instead translate it to a quality name.
> fix: issue where quality code is send instead of name to PM

- source/B2BApi.AppTests/Fixtures/B2BApiAppFixture.cs
- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_021/EnqueueBrs21ForwardMeteredDataMessagesTests.cs
The log output from tests running in CI and locally are very extensive, which makes it harder to find what we need, and slow to load in GitHub.
> chore: Disable extensive logging from EF Core

- source/IncomingMessages.Domain/Schemas/Ebix/EbixSchemaProvider.cs
There is a race condition when multiple requests try to store any ebix schema in a cache simultaneously. The first one wins and the second fails. 
Now we are trying to add the loaded schema without throwing exceptions when the second request is trying to update the cache with the loaded schema
> fix: duplicated with key argument exception in ebix schema provider

- source/IncomingMessages.Infrastructure/ProcessManager/ForwardMeteredDataOrchestrationStarter.cs
We should not parse the registeredAt to an Instant in the sync process. This should be done in the async flow in Process Manager. 
Fix: NodaTime.Text.UnparsableValueException Operation ID: 4d18c42a1a33849ce18eac0ba3a47409
> fix: UnparsableValueException when receiving rsm012 with invalid registeredAt value

- source/OutgoingMessages.Domain/DocumentWriters/RSM012/MeteredDataForMeteringPointEbixDocumentWriter.cs
Use `NumberFormatInfo.InvariantInfo` to always write the ebIX energy quantity with periods for decimals.
> fix: Always write RSM-012 quantity decimal with periods for ebIX

- source/BuildingBlocks.Domain/Models/FileStorageFile.cs
- source/OutgoingMessages.Application/UseCases/PeekMessage.cs
- source/OutgoingMessages.Domain/DocumentWriters/DocumentFactory.cs
- source/OutgoingMessages.Domain/Models/OutgoingMessages/OutgoingMessageBundle.cs
- source/OutgoingMessages.Infrastructure/Repositories/OutgoingMessages/OutgoingMessageRepository.cs
- source/OutgoingMessages.IntegrationTests/OutgoingMessages/WhenAPeekIsRequestedTests.cs
- source/OutgoingMessages.IntegrationTests/OutgoingMessages/WhenEnqueueingOutgoingMessageTests.cs
We are getting OutOfMemoryException when bundles are peeked. 
Operation ID: 7ed6d6e979d90aa45dca6abd35bb64f7, where we try to bundle 300 RSM009 together and end up using 1.3gb. ([our Function App has 3.5 gb memory](https://learn.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#available-instance-skus))
Memory usages:
Before
After
- **Refactored `FileStorageFile.cs`**  
Replaced the use of `StreamReader` with a `StringBuilder` for reading blob content. Previously, a new `StreamReader` was created for each message in the bundle, which could lead to increased memory usage due to cumulative overhead.
- **Modified `Bundles` structure**  
Removed `OutgoingMessages` from `Bundles`. The class now only contains the serialized content of the outgoing messages.
- …
> fix: Reduce memory usage when a bundle is peeked

- source/SubsystemTests/Drivers/EdiDatabaseDriver.cs
- source/SubsystemTests/LoadTest/ForwardMeteredData.cs
Ensure we count and clean up correctly after perf test. 
Counts all outgoing messages with "perf_test" message id prefix in not-dequeued bundles
And cleans up by dequeueing all bundles that contain messages from the performance test.
> test: count enqueued outgoing message from perf test

- source/SubsystemTests/Tests/ArchivedMessages/WhenArchivedMessageIsRequestedTests.cs
> fix: Skip the subsystem that generates an outgoing message which interferes with other subsystem tests

- source/SubsystemTests/Drivers/EdiDriver.cs
`EmptyQueueAsync()` would only peek/dequeue one measurements message, and then afterwards dequeue other aggregations (because the `messageCategory` defaults to `Aggregations` and wasn't provided in the recursive method call).
> test: Fix BRS-021 subsystem tests

- source/ArchitectureTests/RegistrationTests.cs
- source/B2BApi.AppTests/Fixtures/B2BApiAppFixture.cs
- source/B2CWebApi.AppTests/Fixture/B2CWebApiFixture.cs
- source/BuildingBlocks.Domain/Extensions/TestMessageIdExtensions.cs
- source/IncomingMessages.Infrastructure/Configuration/Options/IncomingMessagesOptions.cs
- source/IncomingMessages.Infrastructure/Extensions/DependencyInjection/IncomingMessagesExtensions.cs
- source/IncomingMessages.Infrastructure/IncomingMessagePublisher.cs
- source/IncomingMessages.Infrastructure/ProcessManager/ForwardMeteredDataOrchestrationStarter.cs
- source/IncomingMessages.Infrastructure/ProcessManager/IProcessManagerClientFactory.cs
- source/IncomingMessages.Infrastructure/ProcessManager/IProcessManagerMessageClientFactory.cs
- source/IncomingMessages.Infrastructure/ProcessManager/ProcessManagerClientFactory.cs
- source/IncomingMessages.Infrastructure/ProcessManager/ProcessManagerMessageClientFactory.cs
- source/IncomingMessages.Infrastructure/ProcessManager/RequestProcessOrchestrationStarter.cs
- source/IncomingMessages.IntegrationTests/IncomingMessagesTestBase.cs
- source/IntegrationTests/Behaviours/BehavioursTestBase.cs
- source/IntegrationTests/TestBase.cs
- source/SubsystemTests/Drivers/Ebix/EbixDriver.cs
- source/SubsystemTests/Drivers/EdiDriver.cs
- source/SubsystemTests/Drivers/MessageFactories/EnqueueBrs021ForwardMeteredDataFactory.cs
- source/SubsystemTests/Drivers/MessageFactories/EnqueueBrs026MessageFactory.cs
- source/SubsystemTests/Drivers/MessageFactories/EnqueueBrs028MessageFactory.cs
- source/SubsystemTests/Dsl/AggregatedMeasureDataRequestDsl.cs
- source/SubsystemTests/Dsl/ForwardMeteredDataDsl.cs
- source/SubsystemTests/Dsl/WholesaleSettlementRequestDsl.cs
- source/SubsystemTests/Tests/ArchivedMessages/WhenArchivedMessageIsRequestedTests.cs
- source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
This PR updates test dependencies to use special test UUIDs and improves testability by mocking dependencies in subsystem tests. Key changes include:
- Replacing Guid.ToString() calls with Guid.ToTestMessageUuid() for consistent test message identifiers.
- Changing return types from Guid to string for test methods where message identifiers are returned.
- Renaming and updating configuration options from IncomingMessagesQueueOptions to IncomingMessagesOptions and adding a new ProcessManagerClientFactory to support mock dependencies.
- Infrastructure PR: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/3564
- D002 run: https://github.com/Energinet-DataHub/dh3-environments/actions/runs/14910113600/job/41882830343
- https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/ …
> test: Mock dependencies when running subsystem tests

- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_021/EnqueueBrs21CalculationMessagesTests.cs
- source/B2BApi.AppTests/Functions/EnqueueMessages/BRS_021/EnqueueBrs21ForwardMeteredDataMessagesTests.cs
- source/BuildingBlocks.Infrastructure/FeatureFlag/FeatureFlagName.cs
- source/BuildingBlocks.Infrastructure/FeatureFlag/MicrosoftFeatureFlagManager.cs
- source/BuildingBlocks.Tests/TestDoubles/FeatureFlagManagerStub.cs
- source/OutgoingMessages.IntegrationTests/OutgoingMessages/WhenAPeekIsRequestedTests.cs
Imødekomme renaming I dette pr: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/3568
> fix: rename peek measurement messages flag

- source/SubsystemTests/Drivers/EdiDatabaseDriver.cs
Fix query to fetch number of enqueued outgoing messages after a load test.
> fix: number of enqueued rsm021 query (load test)

- source/ArchivedMessages.IntegrationTests/Fixture/ArchivedMessagesFixture.cs
- source/ArchivedMessages.IntegrationTests/WhenArchivedMessageIsCreatedTests.cs
As of right now, we do not have a test which ensures that all the archived messages are stored in the expected table.
This pr introduces such a test
> Test: Ensure archived messages are saved in expected table

- source/B2BApi/Functions/EnqueueMessages/BRS_045/EnqueueHandler_Brs_045_MissingMeasurementsLog.cs
- source/BuildingBlocks.Domain/Models/ExternalId.cs
- source/OutgoingMessages.IntegrationTests/OutgoingMessages/WhenEnqueueingMultipleOutgoingMessagesIdempotencyTests.cs
- source/OutgoingMessages.Interfaces/Models/MissingMeasurementMessages/MissingMeasurementMessageDto.cs
- source/OutgoingMessages.UnitTests/Domain/ExternalIdTests.cs
Set missing measurement logs external id from orchestration instance id and metering point id. The external id has a max length of 36 characters in the database, so a hash is created that has a max 36 character length.
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/758
> fix: Set Missing Measurements Log external id from input

- source/OutgoingMessages.Application/ActorRequestsClient.cs
Update the reject reason for `E0H` to better state, that there is no data available for the provided grid area.
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/internal-repo/1656
> feat: Update reject reason error for energy/wholesale requests

- source/B2CWebApi/Mappers/DocumentTypeMapper.cs
- source/B2CWebApi/Models/DocumentTypes.cs
- source/SubsystemTests/Drivers/B2C/Client/B2CEdiClientV3.cs
- source/SubsystemTests/Drivers/B2C/Client/swaggerV3.json
- source/Tests/B2CWebApi/Mappers/DocumentTypeMapperTests.cs
This pull request exposes the document type `ReminderOgMissingMeasureData` in the `archivedMessagesSearchController`
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/749
> feat: Add missing measure data to document types for archived messages client

- source/B2CWebApi/Factories/V1/RequestAggregatedMeasureDataDtoFactoryV1.cs
- source/Tests/B2CWebApi/Factories/RequestAggregatedMeasureDataDtoFactoryV1Test.cs
This pull request introduces changes to enhance date handling in the `RequestAggregatedMeasureDataDtoFactoryV1` class and adds unit tests for validation. 
Converting `DateTimeOffset` to `Instant` for ISO UTC compliance and introducing a new test class to ensure the correctness of the DTO creation.
https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/internal-repo/1746
https://energinet.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3Df3a64213c339aa10f73f2bf0e00131f6
> fix: Start and End should be in correct format when RequestingEnergy

- source/ApplyDBMigrationsApp/ApplyDBMigrationsApp.csproj
- source/ApplyDBMigrationsApp/Scripts/Model/202506041337 Update index IX_Bundles_NextBundleToPeek on Bundles table.sql
- source/OutgoingMessages.Infrastructure/Repositories/Bundles/BundleRepository.cs
Since ebIX peek does not include message category, it is more performant to have a separate index for the ebIX query. This should improve peek performance, since `Created` is now the last column in the index, and it is only used for sorting in the queries.
> perf: Add specific ebIX index for peek bundle

- source/B2CWebApi.AppTests/B2CWebApiRequests.cs
- source/B2CWebApi.AppTests/Tests/SendMeasurementsRequestTests.cs
- source/B2CWebApi.AppTests/Tests/SendMeasurementsTests.cs
- source/B2CWebApi/Controllers/SendMeasurementsController.cs
- source/B2CWebApi/Extensions/DependencyInjection/SendMeasurementsExtensions.cs
- source/B2CWebApi/Factories/V1/SendMeasurementsDtoFactory.cs
- source/B2CWebApi/Models/V1/Quality.cs
- source/B2CWebApi/Models/V1/Resolution.cs
- source/B2CWebApi/Models/V1/SendMeasurementsRequestV1.cs
- source/B2CWebApi/Program.cs
- source/BuildingBlocks.Domain/Models/IncomingDocumentType.cs
- source/BuildingBlocks.Domain/Models/MessageId.cs
- source/IncomingMessages.Application/DelegateIncomingMessage.cs
- source/IncomingMessages.Application/UseCases/ReceiveIncomingMarketMessage.cs
- source/IncomingMessages.Domain/MessageParsers/RSM012/SendMeasurementsB2CJsonMessageParser.cs
- source/IncomingMessages.Infrastructure/Extensions/DependencyInjection/IncomingMessagesExtensions.cs
- source/IncomingMessages.IntegrationTests/MessageParsers/GivenNewDocumentTypeTests.cs
- source/IncomingMessages.Interfaces/Models/SendMeasurementsDto.cs
- source/Tests/B2CWebApi/Mappers/DocumentTypeMapperTests.cs
Add support for BRS-021 Send Measurements from the UI/BFF to EDI, through the B2C app.
- Add controller & endpoint for send measurements.
- Add send measurements request & incoming message DTO.
- Add document type and parser.
- Add app test for the request.
This pull request is related to this issue: https://app.zenhub.com/workspaces/mosaic-60a6105157304f00119be86e/issues/gh/energinet-datahub/team-mosaic/843
> feat: Implement walking skeleton of Send Measurements from the UI
